### ISSUE TITLE
ImportError: No module named _core_

### ISSUE THREAD

**Issue by siliconplains44** [pyinstaller/pyinstaller#1300]
I have a wxpython based app that I am trying to compile into a linux 64 bit exe with this tool.  Before I ran pyinstaller I can open pycharm and run my target app code with wxpython 3.0.2.0 that I built fresh on this linux 14.04 ubuntu os that is in python code format.  I go to build the app with pyinstaller and the tool does not import wxpython it appears.  I get the following message when the exe is trying to load....
```
File "/home/name/projects/tool/toolpy/build/main/out00-PYZ.pyz/wx._core", line 4, in <module>
ImportError: No module named _core_
```
How do I fix pyinstaller not including wxpython

**Comment by htgoebel** [comment]
Please follow the instructions at https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong and https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs and submit more infos. thanks.

**Comment by htgoebel** [comment]
@siliconplains44 Any news on this?

**Comment by siliconplains44** [comment]
You are the Man!!!! I pulled down the fir develop version on Linux and I
was able to build successfully!

On Thursday, July 23, 2015, Hartmut Goebel <notifications@github.com> wrote:

> @siliconplains44 <https://github.com/siliconplains44> Any news on this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyinstaller/pyinstaller/issues/1300#issuecomment-124241296>
> .
>


-- 
W Allan Edwards
214-289-2959

**Comment by rsnape** [comment]
Hi - I have just [answered a stack overflow question](http://stackoverflow.com/a/32334301/838992) on this.

I think this gives more info - basically the pyinstaller version installed by `pip install pyinstaller` on Ubuntu 14.04 will exhibit this issue even with a very basic `wxpython` app.  I used the "Hello world" app from the [wxpython website](http://wiki.wxpython.org/Getting%20Started#A_First_Application:_.22Hello.2C_World.22) and the standard pyinstaller tools (`pyi-makespec` followed by `pyinstaller`) and could repro the problem.

If I install from the github develop branch, the problem goes away.  I guess this makes it a problem with the version that is currently on `pypi`.  I can't state whether it affects programs using packages other than `wxpython`

**Comment by matysek** [comment]
@rsnape This just confirms that it is fixed. Could you try this with `python3` branch?

**Comment by rsnape** [comment]
@matysek Agreed this confirms it's fixed on develop. I was just adding the comment to elaborate on the symptoms/steps to reproduce and the fact that it still occurs on the current pypi version installed by `pip`.  I will test the `python3` branch as soon as I can get onto an appropriately configured Linux box.
