### ISSUE TITLE
ImportError: No module named jnpr.junos - Namespace package

### ISSUE THREAD

**Issue by akbhat** [pyinstaller/pyinstaller#1346]
I am running into an import error and can't figure how to get around it. I tried using a hook file named hook-jnpr.junos.py with hiddenimports = ['junpr.junos'] but that did not resolve the issue. Can somebody suggest what is wrong here? I can share any log files if needed.

The imports are as below:
from jnpr.junos.utils.start_shell import StartShell
from jnpr.junos.utils.fs import FS
from jnpr.junos.utils.scp import SCP

Build Log:
PS C:\DLs\Python\Telnet scripts> pyinstaller.exe --onefile .\jdata.py --additional-hooks-dir=hooks --debug
23 INFO: wrote C:\DLs\Python\Telnet scripts\jdata.spec
39 INFO: Testing for ability to set icons, version resources...
49 INFO: ... resource update available
52 INFO: UPX is not available.
75 INFO: Processing hook hook-os
190 INFO: Processing hook hook-time
196 INFO: Processing hook hook-cPickle
263 INFO: Processing hook hook-_sre
383 INFO: Processing hook hook-cStringIO
476 INFO: Processing hook hook-encodings
490 INFO: Processing hook hook-codecs
861 INFO: Processing hook hook-httplib
867 INFO: Processing hook hook-email
973 INFO: Processing hook hook-email.message
1199 WARNING: library python%s%s required via ctypes not found
1332 INFO: Extending PYTHONPATH with C:\DLs\Python\Telnet scripts
1334 INFO: checking Analysis
1335 INFO: building Analysis because out00-Analysis.toc non existent
1335 INFO: running Analysis out00-Analysis.toc
1338 INFO: Adding Microsoft.VC90.CRT to dependent assemblies of final executable
1421 INFO: Searching for assembly x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.21022.8_none ...
1423 INFO: Found manifest C:\Windows\WinSxS\Manifests\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.21022.8_none_bcb86ed6ac711f91.manifest
1427 INFO: Searching for file msvcr90.dll
1427 INFO: Found file C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.21022.8_none_bcb86ed6ac711f91\msvcr90.dll
1430 INFO: Searching for file msvcp90.dll
1431 INFO: Found file C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.21022.8_none_bcb86ed6ac711f91\msvcp90.dll
1434 INFO: Searching for file msvcm90.dll
1436 INFO: Found file C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.21022.8_none_bcb86ed6ac711f91\msvcm90.dll
1518 INFO: Analyzing C:\python27\lib\site-packages\PyInstaller\loader\_pyi_bootstrap.py
1532 INFO: Processing hook hook-os
1549 INFO: Processing hook hook-site
1572 INFO: Processing hook hook-encodings
1687 INFO: Processing hook hook-time
1693 INFO: Processing hook hook-cPickle
1763 INFO: Processing hook hook-_sre
1895 INFO: Processing hook hook-cStringIO
2002 INFO: Processing hook hook-codecs
2381 INFO: Processing hook hook-httplib
2385 INFO: Processing hook hook-email
2495 INFO: Processing hook hook-email.message
2729 WARNING: library python%s%s required via ctypes not found
2895 INFO: Processing hook hook-pydoc
2957 INFO: Analyzing C:\python27\lib\site-packages\PyInstaller\loader\pyi_importers.py
3065 INFO: Analyzing C:\python27\lib\site-packages\PyInstaller\loader\pyi_archive.py
3168 INFO: Analyzing C:\python27\lib\site-packages\PyInstaller\loader\pyi_carchive.py
3270 INFO: Analyzing C:\python27\lib\site-packages\PyInstaller\loader\pyi_os_path.py
3279 INFO: Analyzing .\jdata.py
3305 INFO: Processing hook hook-lxml.etree
3443 INFO: Hidden import 'codecs' has been found otherwise
3444 INFO: Hidden import 'encodings' has been found otherwise
3444 INFO: Looking for run-time hooks
3933 INFO: Using Python library C:\Windows\system32\python27.dll
3997 INFO: Warnings written to C:\DLs\Python\Telnet scripts\build\jdata\warnjdata.txt
4003 INFO: checking PYZ
4006 INFO: rebuilding out00-PYZ.toc because out00-PYZ.pyz is missing
4006 INFO: building PYZ (ZlibArchive) out00-PYZ.toc
4950 INFO: checking PKG
4953 INFO: rebuilding out00-PKG.toc because out00-PKG.pkg is missing
4953 INFO: building PKG (CArchive) out00-PKG.pkg
6278 INFO: checking EXE
6279 INFO: rebuilding out00-EXE.toc because jdata.exe missing
6280 INFO: building EXE from out00-EXE.toc
6285 INFO: Appending archive to EXE C:\DLs\Python\Telnet scripts\dist\jdata.exe

The traceback
PS C:\DLs\Python\Telnet scripts> .\dist\jdata.exe -h
LOADER: executable is C:\DLs\Python\TELNET~1\dist\jdata.exe
LOADER: homepath is C:\DLs\Python\TELNET~1\dist
LOADER: _MEIPASS2 is NULL
LOADER: archivename is C:\DLs\Python\TELNET~1\dist\jdata.exe
LOADER: Extracting binaries
LOADER: Executing self as child
LOADER: Setting up to run child
LOADER: Creating child process
LOADER: Waiting for child process to finish...
LOADER: executable is C:\DLs\Python\TELNET~1\dist\jdata.exe
LOADER: homepath is C:\DLs\Python\TELNET~1\dist
LOADER: _MEIPASS2 is C:\Users\akbhat\AppData\Local\Temp\_MEI90362
LOADER: archivename is C:\DLs\Python\TELNET~1\dist\jdata.exe
LOADER: Already in the child - running user's code.
LOADER: manifestpath: C:\Users\akbhat\AppData\Local\Temp\_MEI90362\jdata.exe.manifest
LOADER: Activation context created
LOADER: Activation context activated
LOADER: Python library: C:\Users\akbhat\AppData\Local\Temp\_MEI90362\python27.dll
LOADER: Manipulating evironment
LOADER: PYTHONPATH=C:\Users\akbhat\AppData\Local\Temp\_MEI90362
LOADER: PYTHONHOME=C:\Users\akbhat\AppData\Local\Temp\_MEI90362
LOADER: Manipulating Python's sys.path
LOADER: importing modules from CArchive
LOADER: extracted struct
LOADER: extracted pyi_os_path
LOADER: extracted pyi_archive
LOADER: extracted pyi_importers
LOADER: Installing import hooks
LOADER: out00-PYZ.pyz
LOADER: Running scripts
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "C:\python27\Lib\site-packages\PyInstaller\loader\pyi_importers.py", line 270, in load_module
    exec(bytecode, module.__dict__)
  File "C:\DLs\Python\Telnet scripts\build\jdata\out00-PYZ.pyz\jnpr_cmds", line 2, in <module>
ImportError: No module named jnpr.junos
LOADER: RC: -1 from jdata
LOADER: OK.
LOADER: Deactivating activation context
LOADER: Releasing activation context
LOADER: Done
LOADER: Cleaning up Python interpreter.
LOADER: Back to parent
LOADER: Doing cleanup
LOADER: Freeing archive status for C:\DLs\Python\TELNET~1\dist\jdata.exe

**Comment by htgoebel** [comment]
You don't need to give hidden imports, because you are importing the module unconcealed. Please try the solutions described in https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong.

**Comment by akbhat** [comment]
HT
I tried --onedir and --noupx but ran into the same import error.

The module is located in site-packages but I tried building by copying the module in the local directory and that did not help either.

Based on the error, ImportError: No module named jnpr.junos, it is apparent that this module is not getting packaged. I just cant figure why!

**Comment by akbhat** [comment]
Can somebody suggest what maybe wrong here or what could be tried next?

**Comment by matysek** [comment]
Could you try the the development version?

**Comment by akbhat** [comment]
With the dev version, results below. Executable responds to -h (argparse help) but can't really run the executable. Note that the script form runs without issues and there are no connectivity issue with the target IP. 

C:> .\dist\jdata.exe
Cannot connect to device: ConnectError(host: 10.85.17.151, msg: No module named devices.junos)

If I use pyinstaller 2.1, same issue (-h works but nothing else) with slightly different error.

C:> .\dist\jdata.exe
Traceback (most recent call last):
  File "<string>", line 5, in <module>
ImportError: No module named jnpr.junos.device

My imports for jnpr.junos are as listed below:
from jnpr.junos.device import Device
from jnpr.junos.utils.start_shell import StartShell
from jnpr.junos.utils.fs import FS
from jnpr.junos.utils.scp import SCP

I removed the following import:
import jnpr.junos

What can I try next? Let me know if additional information is needed.

**Comment by htgoebel** [comment]
Please follow *all* the instructions in https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly and try to find out, why the module is not packaged. Use a *minimal* example to figure this out.

Please try to solve this on your own. We are currently busy working on Python 3 support, so we can not spend much time into this. If this does not help, please submit a *minimal* example for us to reproduce. Take https://gist.github.com/ronen/024cdae9ff2d50488438 as an example on how we can try reproducing this quickly.

**Comment by akbhat** [comment]
HT
pyi-archive_viewer .\build\d\out00-PYZ.pyz does not include jnpr.junos module.

Provided minimal code example to demonstrate the problem. Help will be much appreciated. 

https://gist.github.com/akbhat/ff7e0a30c7521902b56b

**Comment by htgoebel** [comment]
And where to get this module? How to install it? It's not in PyPI.

**Comment by htgoebel** [comment]
You are *firectly* importing this module, but it's missing anyway. Please search `C:\DLs\Python\Telnet scripts\build\jdata\warnjdata.txt` for the reason.

**Comment by matysek** [comment]
It looks like the module is this: https://pypi.python.org/pypi/junos-eznc/

**Comment by akbhat** [comment]
HT
Matysek pointed to the correct module. You will be able to see the problem with the minimal code example I uploaded. Below is what I see in the warn*.txt log.

W: no module named jnpr (top-level import by __main__)

**Comment by akbhat** [comment]
Hartmut
The same issue exists in a Linux environment as well. Any chance the issue is due to the module egg file being named junos_eznc-1.2.0-py2.7.egg-info?

Were you able to figure the problem based on my code example?

**Comment by akbhat** [comment]
py2exe also could not "find" the jnpr.junos imports! From the py2exe log: 

The following modules appear to be missing
['IronPythonConsole', 'System', 'System.Windows.Forms.Clipboard', '_scproxy', 'clr', 'console', 'jnpr.junos.device', 'jnpr.junos.utils.fs', 'jnpr.junos.utils.scp', 'jnpr.junos.utils.start_shell', 'modes.editingmodes', 'pyreadline.keysyms.make_KeyPress', 'pyreadline.keysyms.make_KeyPress_from_keydescr', 'pyreadline.keysyms.make_keyinfo', 'pyreadline.keysyms.make_keysym', 'startup']

I would really appreciate if you somebody could me figure this out.

**Comment by htgoebel** [comment]
Result of my analysis: This package is using a namespace-package using the `pkg_resources.declare_namespace()` mechanism. This is detected by modulegraph, but not handled by the committed PyInstaller code.

I'm currently working on this issue anyway and already have some working code, but this will need more testing.

**Comment by matysek** [comment]
@htgoebel 
* I just verified that it really is a namespace package - there is no file `__init__.py` in   site-packages/jnpr/.
* But there is available .pth file `site-packages/junos_eznc-1.2.2-py2.7-nspkg.pth` with content:
```python
import sys, types, os;p = os.path.join(sys._getframe(1).f_locals['sitedir'], *('jnpr',));ie = os.path.exists(os.path.join(p,'__init__.py'));m = not ie and sys.modules.setdefault('jnpr', types.ModuleType('jnpr'));mp = (m or []) and m.__dict__.setdefault('__path__',[]);(p not in mp) and mp.append(p)
```
@akbhat could you try using pyinstaller from 'python3' branch and as a workaround create an empty file `site-packages\jnpr\__init__.py`?

**Comment by akbhat** [comment]
HT
I can not use junos_eznc with Python3 as junos_eznc requires ncclient package which does not yet support Python3. :'(. 
Do you have a sense of how long before the fix will be available?

**Comment by htgoebel** [comment]
Next Week latest. I'm currenty short of time for PyInstaller.

**Comment by matysek** [comment]
> I can not use junos_eznc with Python3 as junos_eznc requires ncclient package which does not yet support Python3. :'(.

@akbhat I meant using Python 2.7 with 'python3' branch. NOT using Python 3.

**Comment by matysek** [comment]
BTW, have you tried the workaround I mentioned?

**Comment by akbhat** [comment]
MZ
I added a dummy __init__.py in the jnpr folder and used PyInstaller==3.0.dev0 but see the same import error.

C:> .\dist\jdatap.exe
Traceback (most recent call last):
  File "<string>", line 8, in <module>
ImportError: No module named jnpr.junos.device

You should be able to see the issue with the minimal code example listed at the URL below:
https://gist.github.com/akbhat/ff7e0a30c7521902b56b

**Comment by htgoebel** [comment]
Stay tuned. My code will be published next Werk.

**Comment by htgoebel** [comment]
@akbhat This should be fixed now. I've tested it. Please use the current `python3` branch - with Python 2.7 of course :-)

**Comment by matysek** [comment]
I confirm that python3 branch works for me with the following example when using Python 2.7 on linux:
```python
from jnpr.junos.device import Device
```

**Comment by akbhat** [comment]
HT 
Still see a problem. The minimal code example works but not the actual code. :'). I added node.open() to the code example provided earlier (https://gist.github.com/akbhat/ff7e0a30c7521902b56b) and with that I see the below problem. Let me know what debug information is needed. 
C:> .\dist\d.exe
Traceback (most recent call last):
  File "<string>", line 21, in <module>
  File "<string>", line 16, in main
  File "c:\python27\lib\site-packages\jnpr\junos\device.py", line 481, in open
    raise cnx_err
jnpr.junos.exception.ConnectError: ConnectError(host: 10.85.17.151, msg: No module named devices.junos)

The script works
C:> python.exe .\d.py
Success

To see the problem locally, you will need the ability to actually reach the device that is being connected to. I can provide access to such a device if needed but will need to know your IP subnet.

**Comment by htgoebel** [comment]
Please try to solve this yourself first: https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged

**Comment by akbhat** [comment]
HT
I tried all combinations (onedir, noupx, etc) but run into the same issue. Device is a class inside junos so this particular error is weird since the reference to the module in the error message is devices.junos which seems to be inverted. (This was the same with pyinstaller3 branch before your latest check in - see my previous comment) 

There are multiple warnings in the warnd.txt including the one below. The same warnings exist even with the code example that works so unlikely this is helpful.

From warnd.txt:
no module named select.select - imported by select, ncclient.transport.ssh, paramiko.agent, paramiko.proxy, jnpr.junos.utils.start_shell

Please help!

**Comment by akbhat** [comment]
Did anybody get a chance to look at this? Would really appreciate help in resolving this.

**Comment by akbhat** [comment]
Do I need to open a new ticket or can this be reopened?

**Comment by matysek** [comment]
@akbhat I found out that this is an issue of another package - `ncclient` and not directly `jnpr.junos`.

Try to use option `--hidden-import=ncclient.devices.junos`.

Please add more comments to #1432
