### ISSUE TITLE
pyqtgraph: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by Csega** [pyinstaller/pyinstaller#1365]
Hi Everyone!

I'm new to PyInstaller, so please forgive me if I'm asking something stupid, I just cannot find any solution for this problem.
I wrote a script, which simply imports several tools from pyqtgraph (development version, commit: https://github.com/pyqtgraph/pyqtgraph/commit/f0c9cfa96fb1cf3d149ad3ff22a6525efd6d10ba; I did not install it with pip, easy_install or anything else). It works correctly with python, but when I try to use pyinstaller on it, it gives RuntimeError: maximum recursion depth exceeded.

To reproduce the error:
1. Download pyqtgraph, extract it to a temporary folder and run python setup.py build on it.
2. Copy the folder .\build\lib\pyqtgraph to your working folder.
3. Write a simple program, that imports pyqtgraph tools, like this:

```python
from pyqtgraph.Qt import QtCore, QtGui, QT_LIB, uic
try:
    from pyqtgraph.Qt import QtOpenGL
    from OpenGL.GL import *
    HAVE_OPENGL = True
except ImportError:
    HAVE_OPENGL = False

from pyqtgraph import functions as fn
import pyqtgraph as pg
import pyqtgraph.ptime as ptime

print("Done.")
```

4. Name it to e.g. test.py and create it in your working folder, next to the pyqtgraph directory.

5. Run
```python
python test.py
```

It should print: Done.

6. Run
```python
pyinstaller test.py
```
or
```python
pyinstaller --onedir --name=onedir test.py
```
or
```python
pyinstaller --onefile --name=onefile test.py
```
All throw the following error: RuntimeError: maximum recursion depth exceeded.

I use Windows 8.1 (64 bit), Python 3.3.5 (32-bit), PyInstaller commit: https://github.com/pyinstaller/pyinstaller/commit/586436dd53b96f8f8a58dcdcccbbc8e109b19ff7

What could be the problem? Please, help!

**Comment by htgoebel** [comment]
Could be the same problem as #1289

**Comment by Csega** [comment]
I saw that #1289 has been closed, but the problem stayed the same for me with the newest commit I could get: https://github.com/pyinstaller/pyinstaller/commit/4071aa974d8b83cdc82eece1e97eb66bbdca3a92.
What should I do now?

**Comment by matysek** [comment]
You did not tell anything about installing PyQt/PySide or numpy packages.

I'm not able to reproduce this. Python 3.3.5 32bit. I did:
* installed pyqtgraph-0.9.10.win32.exe
* installed pyside 'pip install pyside'
* installed numpy 'pip install numby
* changed the fist line of your example to: `from pyqtgraph.Qt import QtCore, QtGui`
* `pyinstaller --debug test.py` created the exe
* the exe printed `Done.`

**Comment by Csega** [comment]
I have PyQt5 5.4.2 (built and installed from source) and numpy 1.9.2 (installed via pip). That is why I need the newest (git) pyqtgraph, because it has PyQt5 support. Sorry, I forgot to mention it. I tried the same for the newest pyqtgraph development version (https://github.com/pyqtgraph/pyqtgraph/commit/cc655197d1c8e535f3ec77c342dd4226921c6591), but still got the same error.

**Comment by matysek** [comment]
I'm sorry but it is hard to help you since you use too many moving targets (PyQt compiled from source, dev pyqtgraph version, ...).

Your effort looks like creating import hooks for pyqtgraph module.

**Comment by Csega** [comment]
I see. Could you give me a link as a starter to learn how to create import hooks for a module? I'd like to give it a try.

**Comment by htgoebel** [comment]
The manual https://pythonhosted.org/PyInstaller/ and the wiki https://github.com/pyinstaller/pyinstaller/wiki

**Comment by Csega** [comment]
Thanks!

**Comment by matysek** [comment]
The recursion depth is probably a modulegraph issue that was fixed recently: https://bitbucket.org/ronaldoussoren/modulegraph/commits/d1ab16fbcc152811e29df3b7b645beda67062f2b

**Comment by Csega** [comment]
Thanks for the info. I installed modulegraph using pip (in principle, the fix you mentioned is in the 0.12.1 release), but still have the same issue. Do I have to set somehow Pyinstaller to use modulegraph? Because until now I didn't have this package.

**Comment by Csega** [comment]
In the meantime, I found this: https://bitbucket.org/ronaldoussoren/modulegraph/issues/27/maximum-recursion-depth-exceeded-when

Maybe the problem is still present there...

**Comment by matysek** [comment]
PyInstaller bundles own copy of modulegraph (slightly modified) and does not use modulegraph that you install with `pip install`.

**Comment by Csega** [comment]
Is this mean, that this newer version of modulegraph is not included in Pyinstaller yet? Because otherwise it should work now, right?

**Comment by htgoebel** [comment]
> Does this mean, that this newer version of modulegraph is not included in Pyinstaller yet

Exactly. Weill update these days.

Am 5. August 2015 21:50:48 MESZ, schrieb Martin Zibricky <notifications@github.com>:

**Comment by Csega** [comment]
Thanks, I stay tuned! :)

**Comment by htgoebel** [comment]
This should now be fixed. Please test the current python3-branch and give us a note on your success.

**Comment by Csega** [comment]
Unfortunately, the problem still exists with the same error message. :(

**Comment by Csega** [comment]
Guys! It works now! :) I'm really happy, thanks! :) With the latest commit (this one: https://github.com/pyinstaller/pyinstaller/commit/76c5c2f58a3dceaf95cc50153d27fbe49f734e1a) it works! However, I found a new issue with scipy.linalg, I'll open a ticket for it in a minute. ;)
