### ISSUE TITLE
ImportError: DLL load failed   (Windows x64) issue with GDAL (Possible duplicate manifest entries for MSVCRT)

### ISSUE THREAD

**Issue by mmolero** [pyinstaller/pyinstaller#1376]
First it all, Excellent project!!!!!! thanks for sharing

I have problems when I want to include the GDAL module in my project using the develop version (It works when I'm using the stable 2.1 version)

The environment I'm using is as follows:

Windows 7/8 64 Bits
Python 2.7.9 (WinPython)

and the log that appears is :

```
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "D:\pcloudpy\bin\windows\build\main\out00-PYZ.pyz\pcloudpy.gui.app", line 22, in run
  File "D:\WinPython-64bit-2.7.9.3\python-2.7.9.amd64\Lib\site-packages\PyInstaller\loader\pyi_importers.py", line 271,
in load_module
    exec(bytecode, module.__dict__)
  File "D:\pcloudpy\bin\windows\build\main\out00-PYZ.pyz\pcloudpy.gui.MainWindow", line 18, in <module>
  File "D:\WinPython-64bit-2.7.9.3\python-2.7.9.amd64\Lib\site-packages\PyInstaller\loader\pyi_importers.py", line 271,
in load_module
    exec(bytecode, module.__dict__)
  File "D:\pcloudpy\bin\windows\build\main\out00-PYZ.pyz\pcloudpy.core.io", line 3, in <module>
  File "D:\WinPython-64bit-2.7.9.3\python-2.7.9.amd64\Lib\site-packages\PyInstaller\loader\pyi_importers.py", line 271,
in load_module
    exec(bytecode, module.__dict__)
  File "D:\pcloudpy\bin\windows\build\main\out00-PYZ.pyz\pcloudpy.core.io.ReaderTIFF", line 4, in <module>
  File "D:\WinPython-64bit-2.7.9.3\python-2.7.9.amd64\Lib\site-packages\PyInstaller\loader\pyi_importers.py", line 271,
in load_module
    exec(bytecode, module.__dict__)
  File "D:\pcloudpy\bin\windows\build\main\out00-PYZ.pyz\gdal", line 2, in <module>
  File "D:\WinPython-64bit-2.7.9.3\python-2.7.9.amd64\Lib\site-packages\PyInstaller\loader\pyi_importers.py", line 271,
in load_module
    exec(bytecode, module.__dict__)
  File "D:\pcloudpy\bin\windows\build\main\out00-PYZ.pyz\osgeo", line 32, in <module>
  File "D:\pcloudpy\bin\windows\build\main\out00-PYZ.pyz\osgeo", line 24, in swig_import_helper
  File "D:\WinPython-64bit-2.7.9.3\python-2.7.9.amd64\Lib\site-packages\PyInstaller\loader\pyi_importers.py", line 416,
in load_module
    module = imp.load_module(fullname, fp, filename, self._c_ext_tuple)
ImportError: DLL load failed: The application has failed to start because its side-by-side configuration is incorrect. P
lease see the application event log or use the command-line sxstrace.exe tool for more detail.
```

Any suggestions? 
thanks!!!!

**Comment by codewarrior0** [comment]
Could you run these commands to use the sxstrace.exe and find out what the side-by-side configuration problem is?

```
> sxstrace trace -logfile:trace.log
> (run your program here)
> (press ENTER to stop tracing)
> sxstrace parse -logfile:trace.log -outfile:trace.txt
> start trace.txt
```

Post the contents of trace.txt here or on [gist](http://gist.github.com/) for me to look at.

**Comment by mmolero** [comment]
I've tried running the commands you suggested but without success

I did the following steps:

- Open a cmd console and running 
```
sxstrace trace -logfile:trace.log
```
- Open a second cmd console and running my program (of course it stopped due to the errors I commented above)

- In the first cmd console stopping the tracing 
- Running the command
```
sxstrace parse -logfile:trace.log -outfile:trace.txt
```
But It appears a system window with the message : *Sxs Tracing Tool has stopped working*, (I had to close this window) so it was not able to generate the trace.txt

Any suggestion? thanks!!!

**Comment by codewarrior0** [comment]
I, uh, wow. If sxstrace.exe is crashing, there's really nothing I can think of to find out what the problem is.

**Comment by mmolero** [comment]
Indeed the strange thing is that the same program  works if I'm using the pyinstaller stable 2.1 version. however I need the develop version because it handles very well the IPython package,

**Comment by codewarrior0** [comment]
Actually, I take that back. Here's an idea:

Open the Event Viewer (called "View Event Logs" on Windows 8), open Windows Logs in the left column and select Application. In the center column, scroll to the most recent logs and find the one labeled "Error" and "SideBySide". Copy the text from the top text box in the General tab and paste it here, and also copy the entire text from the Details tab and paste it here.

**Comment by matysek** [comment]
@mmolero Could you debug your app to the few lines that cause it? For examples does just this code work?
```python
import gdal
```

**Comment by matysek** [comment]
@codewarrior0 Could you mention sxstrace in 'If Things Go Wrong' and 'How to Report Bugs' wiki pages?

**Comment by mmolero** [comment]
Ok I've just added it in the wiki pages

**Comment by codewarrior0** [comment]
@mmolero I wrote a bit more about it than you did, so I had to trample over your changes. Sorry.

**Comment by mmolero** [comment]
On contrary thanks to you

This is the log using the Event Logs

```
Log Name:      Application
Source:        SideBySide
Date:          03/08/2015 11:00:08
Event ID:      80
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:     
Description:
Activation context generation failed for "D:\pcloudpy\bin\windows\dist\PCLOUD~1\gdal111.dll".Error in manifest or policy file "" on line . A component version required by the application conflicts with another component version already active. Conflicting components are:. Component 1: D:\pcloudpy\bin\windows\dist\PCLOUD~1\Microsoft.VC90.CRT.MANIFEST. Component 2: D:\pcloudpy\bin\windows\dist\PCLOUD~1\Microsoft.VC90.CRT.MANIFEST.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="SideBySide" />
    <EventID Qualifiers="49409">80</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-08-03T09:00:08.000000000Z" />
    <EventRecordID>724589</EventRecordID>
    <Channel>Application</Channel>
    <Computer>     </Computer>
    <Security />
  </System>
  <EventData>
    <Data>D:\pcloudpy\bin\windows\dist\PCLOUD~1\Microsoft.VC90.CRT.MANIFEST</Data>
    <Data>D:\pcloudpy\bin\windows\dist\PCLOUD~1\Microsoft.VC90.CRT.MANIFEST</Data>
   
    <Data>D:\pcloudpy\bin\windows\dist\PCLOUD~1\gdal111.dll</Data>
  
  </EventData>
</Event>
```

**Comment by codewarrior0** [comment]
Thanks a bunch, that's just what I needed.

I think I know what's going on here. When I did that last patch to the manifest handling code, I noticed something dodgy in the existing code: it was adding the dependencies of python27.dll to the manifests of every .dll it found. What I think is going on here is that python27.dll specifies one version of the MSVCRT assembly, the existing manifest in gdal111.dll specifies another version, and when pyinstaller merges them, the resulting manifest looks something like this:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <dependency>
    <dependentAssembly>
      <assemblyIdentity type="win32" name="Microsoft.VC80.CRT" version="8.0.50727.762" processorArchitecture="x86" publicKeyToken="1fc8b3b9a1e18e3b"></assemblyIdentity>
    </dependentAssembly>
  </dependency>
  <dependency>
    <dependentAssembly>
      <assemblyIdentity type="win32" name="Microsoft.VC80.CRT" version="8.0.50608.0" processorArchitecture="x86" publicKeyToken="1fc8b3b9a1e18e3b"></assemblyIdentity>
    </dependentAssembly>
  </dependency>
</assembly>
```

So, the same assembly is referenced twice, with two different versions, which makes the SxS loader throw a fit (the only sensible response to seeing something like this).

I'm going to look at that dodgy code again and see if I can figure out why it's needed. As far as I know, it shouldn't be necessary to insert python27.dll's dependencies into any other .dll, since the default behavior for a .dll without its own manifest is to use whatever activation context is already active (e.g. the one we set up on app startup).

**Comment by mmolero** [comment]
it would be great if it can be fixed in an easy way, thanks,

**Comment by matysek** [comment]
@mmolero One experimental  way could be trying python3 branch.

We are working on supporting there again Python 2.

**Comment by mmolero** [comment]
@matysek I've tried to use the python3 branch with my code but without success (I'm using my python 2.7 environment I suppose this is the reason) I hope you can fix the python2 branch, thanks a lot!!!

**Comment by codewarrior0** [comment]
All right, I did some digging through the history and found out *why* that dodgy code for injecting manifests into every `.pyd` was put in place to begin with.

In March 2010 (9e1bbe9171dddde5032465d5f3aaa7e29aecd757 and following), the initial support for program manifests was added to aid with porting to Python 2.6 (presumably the first release to link MSVCRT as an assembly). The `manifest` option was added to the `EXE` target to allow user-created manifests to be embedded, and the embedded manifests of all binaries found by `Analyze` were scanned, and all files that make up those assemblies included as plain files outside of any assembly. This was not enough, as there's nothing that links to those assemblies anywhere except for `python26.dll`.

By April 2010 (b40bc16f4c498371fb3ad90b1580d1b08064a042), it was found that even though the assemblies were being included (though the files were ripped out of the assembly folder, they still seemed to work...), extension modules that linked to the DLLs in those assemblies would fail with a DLL Not Found error. Looking back, the reason was obvious: `python.exe` itself has an embedded manifest that has CRT80 as a dependency, so this manifest is active for the entire execution; but the PyInstaller bootloader had no such manifest. The only time CRT80 was linked properly was for `python26.dll` which also had its own embedded manifest. The authors decided the solution was to embed a similar manifest into *each and every extension module*, which is clearly wrong because they work in Python without modification.

Much later, in October 2010 (9e1bbe9171dddde5032465d5f3aaa7e29aecd757), a manifest is finally embedded into the bootloader. This has the same effect as the manifest embedded into `python.exe`; that is to specify CRT80 as a dependency for the entire execution, and allow those extension modules that have no embedded manifest (i.e. *all of them*) to load CRT80 correctly, as it is already specified at the program level.

So by October 2010 this dodgy code was already completely unneeded.

--

I've also noticed we do a few other things of questionable value: 

- Embed the dependency info from every `.pyd`, `.dll`, and assembly found into the bootloader's manifest.

This is almost certainly not needed. If dependency info is found in the manifest embedded into (or sitting alongside as a separate .manifest file) of a `.pyd` or `.dll`, the Windows DLL loader will automatically apply that info while loading that DLL and the DLLs it links to.

- Convert public assemblies into private assemblies

This is my bad. I wrote a big research paper about this, only to go back to it months later and find out that one of my key findings was simply wrong - the DLL loader *will* search the executable's folder for public assemblies, and there is no need to convert them to private ones unless you really, really need that specific version of the assembly, and not a later version installed at the system level and redirected via a policy file. It's probably better to use the system-level one to take advantage of security updates and the like.

--

And one final note. Analysis does not take policy files into account when bundling assemblies. If a binary (e.g. `python27.dll`) depends on the assembly `CRT90.21022`, but a policy file is in place that redirects the assembly's version to `CRT90.30729`, and version 21022 is not installed, then Analysis will not include that assembly at all. Later, when the built exe is run on a system that has neither version of CRT90 (Mostly Windows XP), it will fail to launch because it doesn't have any version of CRT90.

--

At some point, I'm going to go through all of the Windows manifest-related code and remove as much of this questionable code as I can.

**Comment by codewarrior0** [comment]
I'm confident this is fixed now. Extra dependency entries are no longer added to manifest files so the SxS error caused by having two different versions of a dependency in one manifest will not happen anymore.

@mmolero, you may try again with the newest `python3` branch when you get a chance. (It works with Python 2.7 also). If you still get the same problem, I'll reopen the issue.

**Comment by mmolero** [comment]
@codewarrior0 I've tried with the branch you said but the error is the same as in the beginning:

```
E:\miguel\Projects\pcloudpy\bin\windows\dist\pcloudpy-64Bits>pcloudpy-64Bits.exe
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "E:\miguel\Projects\pcloudpy\pcloudpy\gui\app.py", line 22, in run
    from MainWindow import MainWindow
  File "C:\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 311, in load_module
    exec(bytecode, module.__dict__)
  File "E:\miguel\Projects\pcloudpy\pcloudpy\gui\MainWindow.py", line 18, in <module>
    from ..core import io as IO
  File "C:\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 311, in load_module
    exec(bytecode, module.__dict__)
  File "E:\miguel\Projects\pcloudpy\pcloudpy\core\io\__init__.py", line 3, in <module>
    from ReaderTIFF import ReaderTIFF
  File "C:\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 311, in load_module
    exec(bytecode, module.__dict__)
  File "E:\miguel\Projects\pcloudpy\pcloudpy\core\io\ReaderTIFF.py", line 5, in <module>
    import gdal
  File "C:\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 311, in load_module
    exec(bytecode, module.__dict__)
  File "C:\WinPython-64bit-2.7.9.3\python-2.7.9.amd64\lib\site-packages\gdal.py", line 2, in <module>
    from osgeo.gdal import deprecation_warn
  File "C:\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 311, in load_module
    exec(bytecode, module.__dict__)
  File "C:\WinPython-64bit-2.7.9.3\python-2.7.9.amd64\lib\site-packages\osgeo\__init__.py", line 32, in <module>
    _gdal = swig_import_helper()
  File "C:\WinPython-64bit-2.7.9.3\python-2.7.9.amd64\lib\site-packages\osgeo\__init__.py", line 24, in swig_import_help
er
    import _gdal
  File "C:\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 465, in load_module
    module = imp.load_module(fullname, fp, filename, ext_tuple)
ImportError: DLL load failed: No se pudo iniciar la aplicaci¾n; la configuraci¾n en paralelo no es correcta. Consulte el
 registro de eventos de la aplicaci¾n o use la herramienta sxstrace.exe de la lÝnea de comandos para obtener mßs detalle
s.
main returned -1
```
 And using the **Event Logs** I got the following:

```
Nombre de registro:Application
Origen:        SideBySide
Fecha:         13/09/2015 20:25:58
Id. del evento:78
Categoría de la tarea:Ninguno
Nivel:         Error
Palabras clave:Clásico
Usuario:       No disponible
Equipo:        eva
Descripción:
Error al generar el contexto de activación para "E:\miguel\Projects\pcloudpy\bin\windows\dist\pcloudpy-64Bits\gdal111.dll". Error en el archivo de manifiesto o directiva "" en la línea . Una versión de componente requerida por la aplicación está en conflicto con la versión de otro componente activo. Los componentes en conflicto son:. Componente 1: E:\miguel\Projects\pcloudpy\bin\windows\dist\pcloudpy-64Bits\Microsoft.VC90.CRT.MANIFEST. Componente 2: E:\miguel\Projects\pcloudpy\bin\windows\dist\pcloudpy-64Bits\Microsoft.VC90.CRT.MANIFEST.
XML de evento:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="SideBySide" />
    <EventID Qualifiers="49409">78</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-09-13T18:25:58.000000000Z" />
    <EventRecordID>2632</EventRecordID>
    <Channel>Application</Channel>
    <Computer>eva</Computer>
    <Security />
  </System>
  <EventData>
    <Data>E:\miguel\Projects\pcloudpy\bin\windows\dist\pcloudpy-64Bits\Microsoft.VC90.CRT.MANIFEST</Data>
    <Data>E:\miguel\Projects\pcloudpy\bin\windows\dist\pcloudpy-64Bits\Microsoft.VC90.CRT.MANIFEST</Data>
    <Data>
    <Data>E:\miguel\Projects\pcloudpy\bin\windows\dist\pcloudpy-64Bits\gdal111.dll</Data>
    
  </EventData>
</Event>
```

So I can say  I still get the same problem, thanks in advance for your time!!!!

**Comment by codewarrior0** [comment]
Could you try again, but this time run `pyinstaller` with the `--clean` option?

**Comment by mmolero** [comment]
@codewarrior0 Now It works!!!!! thanks
