### ISSUE TITLE
hook-sqlite3 should not add tests modules

### ISSUE THREAD

**Issue by cournape** [pyinstaller/pyinstaller#1415]
The `hook-sqlite3.py` hook pull out `sqlite3.tests.*` files. Besides adding unneeded files, this causes pulling out tkinter on at least Linux, because `sqlite3` tests import `test.test_support` from the stdlib.

You can easily check it with the following simple script:

``` python 
import sqlite3
print("foo")
```

this will pull out tkinter in the binary.

As an aside, it should be possible this behaviour: currently, defining a custom `hook-sqlite3.py` does not override pyinstaller own hook, so the only solution is to fork and modify pyinstaller.

**Comment by matysek** [comment]
@cournape It is not clear what you complain about:
* Do you complain that tkinter is not bundled with sqlite by default?
* Do you think tkinter should be bundled by default?
* Could you describe your use case?
* Do you use module `sqlite3.test.test_support` for anything in your app?

**Comment by cournape** [comment]
Pretty much the opposite :) 

* pyinstaller causes tkinter to be bundled by default with sqlite3, which is not what I want. I suspect most people do not expect this either
* I don't think tkinter should be bundled by default
* I do not use `sqlite3.test.test_support`, but the "official" pyinstaller sqlite3 hook causes pyinstaller to always include it as soon as `sqlite3` is imported. The exact value of `hiddenimports` inside `hook-sqlite3.py` on my machine is 

``` python
['sqlite3.test.transactions', 'sqlite3.test.factory', 'sqlite3.test.types', 'sqlite3.test', 'sqlite3.test.userfunctions', 'sqlite3.test.dbapi', 'sqlite3.test.hooks', 'sqlite3.test.dump', 'sqlite3.test.py25tests', 'sqlite3', 'sqlite3.dbapi2', 'sqlite3.dump', 'sqlite3.test.regression']
```

So there are 2 issues:

* sqlite3 hook should be fixed not to include the test modules
* it would be nice if one could override an existing hook to workaround those issues

Does that make more sense ?

**Comment by matysek** [comment]
@cournape What version of pyinstaller do you use? Could you try the `python3` branch? I think the hook-sqlite3 was recently fixed to not bundle 'sqlite3.test' modules.

**Comment by htgoebel** [comment]
@matysek: The hook was even fixed by yourself :-) 4257b4563

**Comment by matysek** [comment]
Yes, it was :-)

**Comment by cournape** [comment]
So actually, this is still broken in `python3`. Looks like there is a typo, at least for python 2 https://github.com/pyinstaller/pyinstaller/blob/python3/PyInstaller/hooks/hook-sqlite3.py#L18, as tests there are in the package `sqlite3.test`, not `sqlite3.tests`.

**Comment by matysek** [comment]
@cournape The typo should be now fixed. Thanks for reporting.
