### ISSUE TITLE
No module named hookutils

### ISSUE THREAD

**Issue by micmica** [pyinstaller/pyinstaller#1585]
I have installed new version pyinstaller 3.0 and I get this error:
 from PyInstaller.hooks.hookutils import collect_submodules
ImportError: No module named hookutils

Pyinstaller 2.1 worked fine :(

Any idea why this happened?

**Comment by matysek** [comment]
Please provide more info.
* it looks like you have some customized hooks or .spec and files
* in 3.0 this module was renamed: `PyInstaller.hooks.hookutils -> PyInstaller.utils.hooks`

**Comment by micmica** [comment]
Thank you I did not know that. However now I get :
  File "C:\Python27\lib\site-packages\flask\exthook.py", line 87, in load_module

    raise ImportError('No module named %s' % fullname)
ImportError: No module named flask.ext.sqlalchemy.sys
manage returned -1

As I said I did not have these problems with 2.1 version... Any advice will help.

My hooks for flask_sqlalchemy:
 from PyInstaller.utils.hooks import collect_submodules
hiddenimports = collect_submodules('flask_sqlalchemy')
   
Thank you once again.

**Comment by matysek** [comment]
@micmica try the option `--hidden-import=flask.ext.sqlalchemy.sys`

When you get flask hooks working please create a pull request.

**Comment by micmica** [comment]
I have tried that but it's still the same.I will, if I get them work.

**Comment by htgoebel** [comment]
Closing this issue. It's about "No module named hookutils", which is solved.

**Comment by micmica** [comment]
Are you sure it's about that? I have changed in hook-flask_sqlalchemy and hook-flask, 
PyInstaller.hooks.hookutils  to  PyInstaller.utils.hooks, and still won't work.

**Comment by micmica** [comment]
I was wandering if this could be a bug? It seems like pyinstaller isn't detecting an import of the standard library's sys? I'm really trying to make this work, and I don't think it's about hookutils.

**Comment by htgoebel** [comment]
See the title of the ticket. Matysek gave you the solution. You are now talking about a totally different issue. Please open a new ticket for this.

Am 9. Oktober 2015 10:29:14 MESZ, schrieb micmica <notifications@github.com>:
>Are you sure it's about that? I have changed in hook-flask_sqlalchemy
>and hook-flask, 
>PyInstaller.hooks.hookutils  to  PyInstaller.utils.hooks, and still
>won't work.
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/pyinstaller/pyinstaller/issues/1585#issuecomment-146796034

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
