### ISSUE TITLE
Something Wicked This Way Came to "modulegraph"

### ISSUE THREAD

**Issue by leycec** [pyinstaller/pyinstaller#1919]
Bleary-eyed midnight salutations, fellow code spelunkers. All may not be well in the cavernous depths of the PyInstaller codebase. I am possibly the sad-faced pallbearer of ultrabad news.

**PyInstaller might be a little b0rked.** I know, right? leycec crazy talk. But hear this angsty diatribe out.

## How Bad Could It Possibly Be?

Ultrabad. Here's a minimal-length example (MLE):

```
import scipy.special
```

That's it. A one-liner noop only importing a single package. For:

- SciPy < 0.15.0, PyInstaller should already freeze this example without modification.
- SciPy >= 0.15.0, PyInstaller should theoretically freeze this example after merging #1909.

**It doesn't do either.** To demonstrate this, #1909 adds a new [`test_scipy_special()`](https://github.com/pyinstaller/pyinstaller/pull/1909/commits/ef680f6c97b7c74b5c809bb30429b4cfce3284cc) test trivially exercising the above example as:

```
def test_scipy_special(pyi_builder):
    pyi_builder.test_source("""import scipy.special""")
```

For SciPy < 0.15.0, this test should succeed. For SciPy >= 0.15.0, this test should succeed after merging #1909 and otherwise fail with the traceback given at #1908 – a long-standing issue of an undetectable import in a SciPy C extension trivially fixed with a [new one-liner hook](https://github.com/pyinstaller/pyinstaller/pull/1909/commits/65a4873f0883d6b6f674b7131cc1443434e367d8). _Annnyway._

This test currently does none of those things. If you're still with me, you might be thinking: _"Ah-ha! He's gonna complain about hooks, C extensions, shared libraries, or Windows. Those always break."_

**Nope.** Disturbingly, this test does _not_ fail with a trivially fixable low-level platform- or package-specific error. It fails with a [high-level import error](https://travis-ci.org/pyinstaller/pyinstaller/jobs/119444786) causally implicating `ModuleGraph`. That's _never_ trivially fixable:

```
LOADER: Running pyiboot01_bootstrap.py
LOADER: Running pyi_rth_pkgres.py
LOADER: Running test_scipy_special.py
Failed to execute script test_scipy_special
LOADER: OK.
LOADER: Cleaning up Python interpreter.
Traceback (most recent call last):
  File "/tmp/pytest-of-travis/pytest-0/popen-gw2/test_scipy_special_onedir_0/test_scipy_special.py", line 2, in <module>
    import scipy.special
  File "/home/travis/build/pyinstaller/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "scipy/special/__init__.py", line 629, in <module>
  File "/home/travis/build/pyinstaller/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "scipy/special/basic.py", line 18, in <module>
  File "/home/travis/build/pyinstaller/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "scipy/special/orthogonal.py", line 101, in <module>
ImportError: cannot import name 'linalg'
LOADER: Back to parent (RC: 255)
LOADER: Doing cleanup
LOADER: Freeing archive status for /tmp/pytest-of-travis/pytest-0/popen-gw2/test_scipy_special_onedir_0/dist/test_scipy_special/test_scipy_special
```

## I Don't See a Problem Here

Okay, everybody. Put on your corpse-handling gloves. The stacktrace above implies the import chain below:

1. The pure-Python `test_scipy_special()` test attempts to `import scipy.special`.
1. The pure-Python `scipy.special.__init__` module attempts to `from .basic import *`.
1. The pure-Python `scipy.special.basic` module attempts to `from . import orthogonal`.
1. The pure-Python `scipy.special.orthogonal` module attempts to `from scipy import linalg`.
1. The pure-Python `scipy.linalg` package was _not_ frozen by PyInstaller, resulting in the destruction of all that is good and pure.

**This import chain should be trivially parsable by `ModuleGraph`.** No dynamic `__import__()` calls or package `__path__` modifications are performed by any of the modules or packages in this chain. No C extensions, shared libraries, Cython modules, or other unparsable shenanigans are imported within this chain. It's all static pure-Python `import` statements. <sup>_I could be wrong. I'm often wrong. I hope I'm wrong._</sup>

To muddy the waters even more, this import chain _is_ parsable by `ModuleGraph` when the `import scipy.special` statement is moved into the existing `test_scipy()` test. It only fails when this import is performed in a stand-alone test. _wat?_

`ModuleGraph` is the stable bedrock on which all PyInstaller behaviour depends. It no longer appears to be capable of parsing a simple import chain under certain edge cases. Maybe it never was.

## Should I Be Concerned Yet?

I'm sweating bullets myself. (_Kinda hurts._)

I'm hoping this test passed without modification under older versions of PyInstaller – at least for Python <= 2.7 and SciPy < 0.15.0. Since we didn't have a test exercising this failure [until now](https://github.com/pyinstaller/pyinstaller/pull/1909/commits/ef680f6c97b7c74b5c809bb30429b4cfce3284cc), it's all conjecture without manually going back in time or investing time in testing older releases. Sadly, I'm out of flux capacitors.

If this used to work, then PyInstaller's capacity to freeze applications has significantly degraded. The above example is trivial. PyInstaller no longer freezes it. What else can PyInstaller no longer freeze?

If this never worked, then PyInstaller's capacity to freeze at least trivial applications is in question. Which is also kind-of bad. Just not quite as bad.

In either case, badness follows.

## How Do You Know It Was Us? Maybe It Was Ron!

Blaming [Ron](https://bitbucket.org/ronaldoussoren/modulegraph) is my modus operandi. For better or worse, Ron probably didn't do this. In fact, Ron appears to have abandoned `modulegraph`. Which makes me feel bad.

I could be wrong. It's feasible that `ModuleGraph` has always been broken in this respect. That would be great. But also not, because I have no idea how to repair that. Which makes me feel bad yet again.

## How Do You Know Anything?

I don't, O.K.? That's the trouble with code tribbles.

To decipher this dessicated dungheap, I first enabled `ModuleGraph` debugging via `MODULEGRAPH_DEBUG=4`. A suspicious line reared up on its creepy hindlegs:

```
                   Global name found: scipy linalg
```

_Heywaitaminute!_ That's the name of the erroneously omitted package: `scipy.linalg`. That's also debug output recently added by us, which I'd never seen before... **until now.** The lugubrious plot thickens.

The logic responsible for this output lives in two related private `ModuleGraph` methods – `_ensure_fromlist()` and `_safe_import_hook()`. Note the suspicious strings `'Global name found:'` in this code snippet:

```
class ModuleGraph(Graph):
    ...

    def _ensure_fromlist(self, m, fromlist):
        ...

        for sub in fromlist:
            submod = m.get(sub)
            if submod is None:
                if sub in m.globalnames:
                    # Name is a global in the module
                    self.msg(4, 'Global name found:', m.identifier, sub)
                    continue
        ...

    def _safe_import_hook(self, name, caller, fromlist, level=DEFAULT_IMPORT_LEVEL, attr=None):
        ...

        for sub in (fromlist or ()):
            # If this name is in the module namespace already,
            # then add the entry to the list of substitutions
            if sub in m:
                ...

            elif sub in m.globalnames:
                # Global variable in the module, ignore
                self.msg(4, 'Global name found:', m.identifier, sub)
                continue
        ...
```

The `Node.globalnames` set appears to be implicated. Plot thickens more. I grepped about for other instances of `globalnames` and discovered this:

```
class ModuleGraph(Graph):
    ...

    def _scan_code(self, m, co, co_ast=None):
        ...

        # Actually import the modules collected while scanning.
        # We need to suspend the globalnames as otherwise
        # `_safe_import_hook()` would take identfiers imported via
        # `from . import abc` as existing global names and not try to
        # import them. Please note: This only effects this form of
        # import where relative_module is "." For all other cases, the
        # imported module is already processed and all global names
        # are in place anyway.
        globalnames = m.globalnames
        m.globalnames = set()
        self._process_imports(m)
        m.globalnames = globalnames
```

_Hey! **Hey!**_ What in the two-headed hydra of Hades is going on here? Bar none, that's the most suspiciously hacky code I've seen in months. And I've personally authored several decades worth of hacky code in the past month alone. <sup>_Don't tell my wife._</sup>

Again, the shameless hackage above has been recently added by us. I've never seen it before.

## Explain It To Me Like I'm Intellectually Five

I'm intellectually five, too. I can't explain anything.

Also, `ModuleGraph` is a classic [wicked problem](https://en.wikipedia.org/wiki/Wicked_problem). Between Ron's undocumented older functionality, the undocumented newer functionality we've added, and the sad passage of Time, I no longer have a firm grip on `ModuleGraph` behaviour. <sup>...or my own, thanks to this issue.</sup>

I do have unsubstantiated suppositions, however. Let's take those one non-Euclidean dimension at a time.

### `ModuleGraph`: The Teenage Years

A ripe cornucopia of new functionality I've never seen before has been added to `ModuleGraph`, including:

* A new `BaseModule._imported_modules` list.
* A new `_Visitor._collect_import()` method.
* A new `ModuleGraph._process_imports()` method.
* A new `ModuleGraph.createNode()` method.

The new `BaseModule._imported_modules` list appears to be the linchpin tying this new functionality together, which appears to be trying to defer imports performed by `ModuleGraph._scan_*()` methods until _after_ those methods return, which may not behave as expected under all edge cases. Like this one.

### `ModuleGraph` Invariants Have Been B0rked (_Maybe_)

**`ModuleGraph` invariants.** Remember those? Neither do I.

The idea is that all recursively called functions in a recursive algorithm have formal, contractual invariants that should _never_ be broken. We might've broken them. Maybe.

> **Caveat emptor:** Everything that follows is pure conjecture based on the seemingly reasonable assumption that `ModuleGraph` used to behave sanely. I did actually try testing the above example under older versions of PyInstaller, but... I failed and decided go to sleep. It was the smart move.

My assumption is that older versions of `ModuleGraph` did _not_ add attributes imported from other modules and packages to the graph. Imported attributes were simply ignored. This makes sense. Imported attributes are module-scope types and variables. Nobody using `ModuleGraph` cares about module-scope types and variables. Everybody only cares about imports between modules and packages.

Ignoring imported attributes is exactly what the `if sub in m.globalnames:` branches in the `_ensure_fromlist()` and `_safe_import_hook()` methods detailed above were attempting to do. Hence, this assumption appears reasonable.

If this assumption used to hold, it doesn't anymore. Most (but _not_ all) imported attributes are now added to the graph as `MissingModule` nodes rather than being ignored. This is unspeakably bad – but I shall speak of it. Since attributes are _not_ modules, adding attributes to the graph:

* **Breaks `ModuleGraph` semantics.** What would an outgoing edge from an attribute node even mean, for example? Attributes aren't namespaces. They can't import anything. Moreover, `MissingModule` nodes are supposed to inform PyInstaller about... missing modules, _not_ ignorable attributes that actually exist.
* **Increases average graph size** with predictable decreases in performance. I haven't profiled anything, because lazy – but it's easy to see how a graph obesity epidemic would be bad for space and time complexity. Most modules import multiple attributes, most of which are now encapsulated as `MissingModule` nodes unidirectionally connected to their parent module nodes.
* **Invites namespace conflicts** between ignorable attributes and non-ignorable submodules and subpackages of the same name. What happens, for example, when a module `foo` imports a submodule `bar` and then reassigns `bar` to be a variable? Python 2 and 3 both permissively permit this. What's `bar`, in this case? Is it a non-ignorable imported submodule _or_ an ignorable attribute? It's both at different times, of course, but what does `ModuleGraph` think it is? For example, suppose module `foo` contains:

        from . import bar
        bar = 3.1415

* **Serves zero purpose.** PyInstaller doesn't care about imported attributes. Neither should `ModuleGraph`, except to explicitly ignore imported attributes. Which it no longer does.

### `ModuleGraph` Attribute Detection Has Been B0rked, Too

More importantly, the `if sub in m.globalnames:` branches in the `_ensure_fromlist()` and `_safe_import_hook()` methods that I assume once conditionally ignored imported attributes now either:

1. Always evaluate to `False` when those methods are called by `_scan_code()` for the currently scanned module. This is usually the case, so ignorable attribute imports are usually no longer ignored.
1. Sometimes evaluate to `True` when those methods are called by `_scan_code()` for modules other than the currently scanned module. This is _not_ usually the case, but it sometimes is. So, non-ignorable module and package imports are occasionally misdetected as ignorable attribute imports now.

The latter case is what's happening in the `test_scipy_special()` test. The non-ignorable import of the `scipy.linalg` package is misdetected as an ignorable import of a non-existent `scipy.linalg` attribute. It's _not_ an attribute. It's a package. But `ModuleGraph` no longer knows the difference – if it ever did.

Why did this happen? Possibly because `_scan_code()` has been hacked to temporarily nullify the set of all attributes imported by the current module (i.e., `Node.globalnames`), preventing `_ensure_fromlist()` and `_safe_import_hook()` from ignoring imported attributes. My assumption is that, previously, those methods could reliably distinguish ignorable imported attributes from non-ignorable imported modules. That no longer happens – if it ever did.

## Why? Oh Nordic Gods Below, _Why?_

A myriad of ugly questions jostle for attention in my ADHD-addled brainpan. The most stunningly obvious is: **"Why?"**

Why are we trying to delay imports in `_scan_code()` and elsewhere? What's going on here? Is all of this really necessary? Because it may not work. Is this preparatory work for future work to be done – say, an attempt to refactor `ModuleGraph` to use an iterative rather than recursive algorithm for parsing imports? If so, I applaud such virtuous forward-thinking entrepeneurship. That whole maybe-non-working thing puts a damper on my enthusiam, however.

Is delaying imports the cause of this issue? This superficially appears to be the cause, but I'm definitely open to being stupid and wrong. Maybe this never worked and `ModuleGraph` was always discouragingly broken.

If delaying imports _is_ the cause and we want to valiantly trek on with this new functionality, that's cool. Let's trek! But only if we get this to work without brute-force hackery attempting (...but failing) to circumvent our having broken `ModuleGraph` invariants. The `ModuleGraph._scan_code()` changes, which appear to only mask rather than solve underlying issues caused by this new functionality, are especially disconcerting.

Two obvious solutions present themselves.

### Temporary Fix for Maximum Worky

As a merely temporary fix just getting this to work right now without any nauseating delay, we _could_:

* Comment out the entire `if sub in m.globalnames:` branch in `_ensure_fromlist()`.
* Comment out the entire `elif sub in m.globalnames:` branch in `_safe_import_hook()`.

After disabling both of these branches, I can confirm that the `test_scipy_special()` test now locally passes. Both must be disabled. It does _not_ suffice to disable merely one.

Since the `_ensure_fromlist()` and `_safe_import_hook()` methods can no longer reliably distinguish ignorable imported attributes from non-ignorable imported modules, the easiest hack-on-a-hack is to stop ignoring attributes altogether. That's what this fix does. It's a poor long-term solution, however. Ignorable imported attributes _should_ be ignored. <sup>_Assuming `ModuleGraph` could ever do that, that is. So many assumptions._</sup>

### Ideal Fix for Maximum Happy

If delaying imports is the cause, my preference would – with a tip of the fedora and a sad apology to the original author – be to revert our new functionality. But maybe it's actually awesome and we should work hard to preserve somebody's hard work? I don't know. Convince me, convincingly!

### No Fix for Maximum Confused

If delaying imports is _not_ the cause, `ModuleGraph` was always broken in this respect. That's hard to fathom. Detecting simple import chains is core functionality... but my bloodshot third eye is open to the possibility that everything we thought worked never _truly_ worked.

I don't know what the optimum solution to this worst-case scenario would be. Maybe just rip out the `Node.globalnames` attribute and all functionality related to that attribute? If detecting attribute imports is actually infeasible (_...as it might be_), we need to stop trying entirely.

I have no working code and I must scream. Help me, Odin. Help me.

![McBain: "MENDOZAAAAAAA!!!!"](https://deadhomersociety.files.wordpress.com/2011/02/saturdaysofthunder6_thumb.png?w=512&h=384)

**Comment by leycec** [comment]
@htgoebel Save us, code Jesus. Are you familiar with the state of modern `modulegraph`? I'm not. Too much recursion, undocumented code, and oddball data structures. I'm out of my depth here.

I have a bit more free time up my sleeve, though, so I'm gonna try... _something something_. Maybe I'll locally revert recent `modulegraph` changes and see where that gets me.

**Comment by bjones1** [comment]
@leycec, it's good to have you back! An idea, which is a plug for my own software: given your love of writing, have you considered using literate programming to capture your thoughts in the code you write? For plumbing the depths of modulegraph, this would be helpful commentary to the uninitiated (such as me). Specifically, [CodeChat](https://pythonhosted.org/CodeChat/README.html) interprets comments as reST, using Sphinx to produce nicely-formatted webpages from source code.

**Comment by leycec** [comment]
**O.K.** I'd actually never heard of CodeChat before, but... _(wo)man_. Prettifying comments is a pretty sweet ideal. You've documented and evangelized it well. This is one for the bookmarks.

<sup>**Rant follows.** Literate programming is an idea whose time should have come thirty years ago, but didn't – presumably because most engineers treat code as merely the means to an end rather than an end in and of itself. Since code doesn't actually have intrinsic value apart from its end product to most engineers, code comments have even _less_ intrinsic value. Both are sadly disposal. I'd love for that to change, but... well, I harbour doubts. A throw-away culture predicate on conspicuous consumption, planned obsolescence, and utilitarian short-term nonrenewable efficiency gains seems incompatible with literate programming. Or maybe that's just my pessimism talkin'. **Rant ends.**<sup>

**Back on topic.** As I delve through the bowels of `modulegraph`, I'm collecting my commentary into a new documentation-only pull request. It's _all_ docstrings, comments, and `FIXME`'s. Too much logic in `modulegraph` is locked behind inscrutable, unintelligible code. That's unacceptable.

Time to roll up the code sleeves and get greasy.

**Comment by codewarrior0** [comment]
> Why are we trying to delay imports in _scan_code() and elsewhere? What's going on here?

In #1289 there is a `maximum recursion depth exceeded` error when building on Anaconda, which has a lot of modules installed by default. A look at the full stack trace showed that it descended through the ASTs of the source files it is analyzing *and* the graph of imports that it is building at the same time - in other words, the stack trace had alternating layers of AST traversal and import-graph traversal. @htgoebel's solution was to complete the AST traversal for a single source file and collect all of the import statements at once, before building the import graph outward from that file. 

I'm not sure exactly why `globalnames` is being suspended. I should have looked at that more closely.

**Comment by leycec** [comment]
**Oh, Christ-on-a-drumstick.** :poultry_leg:

It _is_ a partial attempt to transition `modulegraph` from a recursive to imperative approach. I intuitively feared this might be the case. This is jump-scare territory. Nonetheless, I support all contributions toward that utopian goal-state, including @htgoebel's gruelling work here.

As a temporary non-solution for alleviating recursion limits under Linux and (..._to a much lesser extent_) Windows, we might consider increasing the default limit via `sys.getrecursionlimit()`. Tragically, the default limit does _not_ appear to be increasable under OS X. Courtesy the [divine oracle](https://stackoverflow.com/a/3194553/2809027):

* The default recursion limit for all platforms is `1000`.
* The maximum recursion limit for:
   * Linux is `2147483647` (i.e., 2<sup>31</sup> - 1).
   * OS X is `1000`. That's right; it's _not_ increasable under OS X. (Only my chittering chihuahua knows why.)
   * Windows is `2000`. Unfortunately, this isn't the _real_ recursion limit under Windows. The _real_ recursion limit is the [stack size](https://stackoverflow.com/a/2918118/2809027) for the current thread – which appears to default to only 1MB! <sup>Take all of this with a grain of salt. I hate Windows.</sup>

In any case, calling `sys.getrecursionlimit(2147483647)` on PyInstaller startup _should_ buy us a bit of leeway on two out of three platforms. Two out of three ain't bad, baby. On Windows, this call should be internally capped at `2000`. On OS X, this call should simply be ignored.

Ultimately, this highlights the necessity of transitioning to a fully imperative approach as fast as volunteer overtime pay **[**read: _zilch_**]** makes feasible. Meanwhile, I'll do my utmost to remove _only_ the **DANGER, DANGER!** zone of `_scan_code()`'s kludgy hack. The remainder of @htgoebel's herculean efforts must be preserved!

Let's do this.

**Comment by leycec** [comment]
**O.K.** I've been doing quite a bit of delving, documenting, and cursing softly in a creepy manner. This issue appears to partially be Ron's fault and partially be our fault. So, everyone's to blame? We're definitely to blame for the `_scan_code()` kludge. But another culprit erupts from this suspicious comment in `ModuleGraph._ensure_fromlist()`:

```
    def _ensure_fromlist(self, m, fromlist):
        fromlist = set(fromlist)
        self.msg(4, "ensure_fromlist", m, fromlist)
        if '*' in fromlist:
            fromlist.update(self._find_all_submodules(m))
            fromlist.remove('*')
        for sub in fromlist:
            submod = m.get(sub)
            if submod is None:
                if sub in m.globalnames:
                    # Name is a global in the module
                    self.msg(4, 'Global name found:', m.identifier, sub)
                    continue
                # XXX: ^^^ need something simular for names imported
                #      by 'm'.
        ...
```

First, I should note that the `if '*' in fromlist:` test in this low-level method is superfluous and hence safely removable. The higher-level `_scan_bytecode()` and `_collect_import()` methods already guarantee `*` characters to be removed from fromlists. _Annnnyway._

Second, note the suspicious comment `# XXX: ^^^ need something simular for names imported by 'm'.` **Gods be cursed.** I noted this before and then summarily ignored it, because... information overload. But this might be the crux of our issue. Perhaps we want to refactor this `if` statement into an `elif` statement preceded by an `if` statement implementing this comment (e.g., by differentiating imported submodules from attributes).

**Comment by leycec** [comment]
**OHGODSOHGODSOHGODS.** I just uncovered the core issue – and it truly is ultra-lame-o. Anyone recall where I [suggested above](https://github.com/pyinstaller/pyinstaller/issues/1919#issue-145315380) that our `ModuleGraph._scan_code()` kludge:

> **Invites namespace conflicts** between ignorable attributes and non-ignorable submodules and subpackages of the same name. What happens, for example, when a module `foo` imports a submodule `bar` and then reassigns `bar` to be a variable? Python 2 and 3 both permissively permit this. What's `bar`, in this case? Is it a non-ignorable imported submodule or an ignorable attribute? It's both at different times, of course, but what does ModuleGraph think it is? For example, suppose module `foo` contains:

```
from . import bar
bar = 3.1415
```

The answer to my query "...but what does ModuleGraph think it is?" is worst-case horrible, of course: **ModuleGraph thinks `bar` is an ignorable attribute.** I never actually envisioned any module _actually_ doing this, but that's exactly what `scipy.__init__` is doing. <sup>I think, anyway.</sup>

Line 68 of  `scipy.__init__` defines a global `linalg = None`. Catastrophically, `linalg` is _also_ a subpackage of `scipy` (i.e., `scipy.linalg`). ModuleGraph resolves this namespace conflict in the stupidest possible way, treating `linalg` as a global variable rather than a subpackage.

To resolve this, we absolutely _do_ need to:

1. Patch the `ModuleGraph._ensure_fromlist()` method as [suggested above](https://github.com/pyinstaller/pyinstaller/issues/1919#issuecomment-216020047) to differentiate non-ignorable submodules from ignorable attributes.
1. Patch the `ModuleGraph._safe_import_hook()` method in a similar way.
1. Remove the `ModuleGraph._scan_code()` kludge.

Tune in next time as leycec possibly does something.

**Comment by leycec** [comment]
Work proceeds at a snail-like pace. "Slow, but steady!" is the motto. :snail: 

I'm zealously documenting everything in sight. It is good. A working solution may spontaneously emerge in a day... **or twenty.**

**Comment by leycec** [comment]
**[Done](https://github.com/leycec/pyinstaller/tree/scipyattr),** in theory. If Travis [passes](https://travis-ci.org/leycec/pyinstaller), then pull request imminent; else, more [blood for the Blood God](https://www.youtube.com/watch?v=3uSM-ihNGHs).

**Comment by htgoebel** [comment]
> t is a partial attempt to transition modulegraph from a recursive to imperative approach

Not really: I just changed it to delay the recursion until after scanning all the code of a module has been completed. This is not much of a difference, since in both cases the identifiers found are processed in the same order. And the code of the module is constant.

**Comment by htgoebel** [comment]
@leycec Thanks a lot for you details an elaborated analysis :-) I'm still not finished reading it, but am looking forward to see your fix.

BTW: Since this is an important case: Could you implement a test-case implementing what you described in "I Don't See a Problem Here", but *without* scipy. Thus we'd had a test-case even if scipy is changing.

**Comment by leycec** [comment]
> ...but am looking forward to see your fix.

Me too! [Tests pass](https://travis-ci.org/leycec/pyinstaller), including the currently failing `test_scipy_special`.

I still need to clean up a few docstrings and commit messages. Otherwise, we're good to go. The pull request should drop sometime this weekend. _Awesome change is incoming._ :innocent: 

> Could you implement a test-case implementing what you described in "I Don't See a Problem Here", but _without_ scipy. Thus we'd had a test-case even if scipy is changing.

That's... **a really good idea.** I'm concerned about this regressing, too. I'll definitely add:

* A mockup package to `tests/functional/modules` containing both a mockup submodule and an `__init__` submodule defining a global variable of the same name as that mockup submodule. This exercises the exact issue.
* A test in `tests/functional/test_basic.py` attempting to import that mockup submodule.

**Comment by leycec** [comment]
**Urgh.** I've documented everything up, only to realize that the ideal solution requires parsing global variable _deletions_ in `ModuleGraph._scan_code()`. Currently, we only parse global variable _additions_. We really need to parse both.

So – despite the fact that my current solution technically works and passes tests, I hate it. The perfectionism strikes back. I am disgust incarnate! <sup>This'll be a few more days.</sup>
