### ISSUE TITLE
Needed modules are not collected on windows becasue of names with different case are treated the same

### ISSUE THREAD

**Issue by concussiongfx** [pyinstaller/pyinstaller#1935]
On windows, my executable is failing to load because there is a missing module. The missing module is called "Logging" and lives in my source tree. The python "logging" has already been collected and causes the append method on the TOC class to fail with:

`Attempted to add Python module twice with different upper/lowercases:`

If the name is matched in FilenameSet, shouldn't there be a second check to see if the module paths are the same?

```
"Logging" - 'C:\Jenkins\workspace\buildstage\Initial\Source\Logging\__init__.py
"logging" - C:\tools\python2\lib\logging\__init__.pyc
```

This is not failing on OSX or Linux since normcase returns the original path..

**Comment by concussiongfx** [comment]
I am seeing the issue with core python modules as well. So far, I have seen this with `Queue` and `Configparser`

In the bundled exe, twisted fails to load with:
```
# Queue not found in PYZ
Traceback (most recent call last):
  File "PyInstaller\loader\rthooks\pyi_rth_twisted.py", line 23, in <module>
```

`Queue` is not included because pyInstaller has already found `queue` in site-packages, so the proper Queue from lib gets dropped.

skipped Modules:
```
`C:\\tools\\python2\\lib\\ConfigParser.py'
'C:\\tools\\python2\\lib\\Queue.py'
```

because these exist
```
[('configparser', 'C:\\tools\\python2\\lib\\site-packages\\configparser\\__init__.py', 'PYMODULE')]
[('queue', 'C:\\tools\\python2\\lib\\site-packages\\queue\\__init__.py', 'PYMODULE')]
```

**Comment by concussiongfx** [comment]
also noticed this from when this change was introduced. The original code stated that this can not be done for python modules, only binaries.

```
# Normalize the case for binary files and data files only (to avoid duplicates
-            # for different cases under Windows). We can't do that for
-            # Python files because the import semantic (even at runtime)
-            # depends on the case. We also cannot do that for GObject Introspection typelibs
-            # which depend on the case when being loaded through PyGObject.
```

**Comment by htgoebel** [comment]
@codewarrior0 Assigning to you, since the change causing this problem (f285f6184b) was yours and thus I assume you know why this has been introduces. (The reason for doing this is neither in the source nor in the commit message.)

**Comment by codewarrior0** [comment]
This check could probably be skipped altogether for pure-Python modules, since they are stored inside our PYZ archive and not on the filesystem. The reason this check is done is because if, for instance, the `Logging` and `logging` modules are extension modules instead of pure-Python modules (or if they are any other kind of data file), then they will be stored as ordinary files. On Windows, the two files are considered to have the same name, so they can't both be stored.

**Comment by stephenrauch** [comment]
@htgoebel, For issue #1939, there is a very minimal example in the test case in PR #1959.

```python
import queue
queue.Queue()
```

**Comment by codewarrior0** [comment]
> I assume you know why this has been introduces

The original reason was because data-files added to the TOC were having their filenames changed to lower-case, which led to the special case for `gi_typelibs`. The special case was later removed when the TOC was changed to never change filenames to lower case, and instead use a case-insensitive compare when adding new entries to the TOC, leaving the original filename unchanged.

The warning (and skipping) for pure-Python modules was a mistake on my part. There's no need to do a case-insensitive compare for pure-Python modules because they aren't stored on the filesystem, but rather inside our archive file. 

It's still a bit reckless to have two Python modules whose name only differs by the character case. It usually doesn't work on Windows using the Python interpreter, except when the two modules are in different `sys.path` folders as seen in this very issue!

Give me a minute, I'll update the unit tests and whip up a fix.

**Comment by htgoebel** [comment]
@codewarrior0 Is this issue fixed now?

**Comment by htgoebel** [comment]
@codewarrior0 If this is fixes, I assume #1959 can be closed, too.

**Comment by codewarrior0** [comment]
Yep, it's fixed now. I went the extra inch and added a test case or two for `future` since that's where we found out about the issue.

**Comment by coyotlinden** [comment]
This problem with Queue still exists as of pyinstaller 3.2 and is causing us to do major refactoring work to work around it.  Error occurs at runtime when a module imports a module that imports Queue:

LOADER: Running download_update.py
Traceback (most recent call last):
 File "download_update.py", line 33, in <module>
   import os
 File "c:\cygwin64\tmp\pip-build-xzzmth\pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
 File "InstallerUserMessage.py", line 33, in <module>
   import Queue
ImportError: No module named Queue
Failed to execute script download_update

**Comment by stephenrauch** [comment]
The problem is in 3.2, but is fixed on dev tip.

**Comment by coyotlinden** [comment]
Thanks, Stephen.  For some reason, I did not get a notification of your comment, I'll try pulling the dev version and seeing if that helps.

Do you know when the next release is planned?

**Comment by Guts** [comment]
I just reproduced the #2327 working with develop branch updated this morning:


```
C:\Users\USER\Documents\GitHub\Perso\DicoGIS\dist\DicoGIS>DicoGIS.exe
[6388] PyInstaller Bootloader 3.x
[6388] LOADER: executable is C:\Users\USER\Documents\GitHub\Perso\DicoGI
S\dist\DicoGIS\DicoGIS.exe
[6388] LOADER: homepath is C:\Users\USER\Documents\GitHub\Perso\DicoGIS\
dist\DicoGIS
[6388] LOADER: _MEIPASS2 is NULL
[6388] LOADER: archivename is C:\Users\USER\Documents\GitHub\Perso\DicoG
IS\dist\DicoGIS\DicoGIS.exe
[6388] LOADER: No need to extract files to run; setting extractionpath to homepa
th
[6388] LOADER: SetDllDirectory(C:\Users\USER\Documents\GitHub\Perso\Dico
GIS\dist\DicoGIS)
[6388] LOADER: Already in the child - running user's code.
[6388] LOADER: Python library: C:\Users\USER\Documents\GitHub\Perso\Dico
GIS\dist\DicoGIS\python27.dll
[6388] LOADER: Loaded functions from Python library.
[6388] LOADER: Manipulating environment (sys.path, sys.prefix)
[6388] LOADER: sys.prefix is C:\Users\USER\DOCUME~1\GitHub\Perso\DicoGIS
\dist\DicoGIS
[6388] LOADER: Setting runtime options
[6388] LOADER: Initializing python
[6388] LOADER: Overriding Python's sys.path
[6388] LOADER: Post-init sys.path is C:\Users\USER\Documents\GitHub\Pers
o\DicoGIS\dist\DicoGIS
[6388] LOADER: Setting sys.argv
[6388] LOADER: setting sys._MEIPASS
[6388] LOADER: importing modules from CArchive
[6388] LOADER: extracted struct
[6388] LOADER: callfunction returned...
[6388] LOADER: extracted pyimod01_os_path
[6388] LOADER: callfunction returned...
[6388] LOADER: extracted pyimod02_archive
[6388] LOADER: callfunction returned...
[6388] LOADER: extracted pyimod03_importers
[6388] LOADER: callfunction returned...
[6388] LOADER: Installing PYZ archive with Python modules.
[6388] LOADER: PYZ archive: out00-PYZ.pyz
[6388] LOADER: Running pyiboot01_bootstrap.py
[6388] LOADER: Running pyi_rth_pkgres.py
[6388] LOADER: Running pyi_rth_win32comgenpy.py
[6388] LOADER: Running pyi_rth_multiprocessing.py
[6388] LOADER: Running pyi_rth_osgeo.py
[6388] LOADER: Running pyi_rth__tkinter.py
[6388] LOADER: Running DicoGIS.py
Traceback (most recent call last):
  File "DicoGIS.py", line 51, in <module>
  File "c:\users\USER\documents\github\perso\dicogis\virtenv2\Lib\site-p
ackages\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "modules\__init__.py", line 2, in <module>
  File "c:\users\USER\documents\github\perso\dicogis\virtenv2\Lib\site-p
ackages\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "modules\georeaders\__init__.py", line 3, in <module>
  File "c:\users\USER\documents\github\perso\dicogis\virtenv2\Lib\site-p
ackages\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "modules\georeaders\Infos_GDB.py", line 38, in <module>
  File "c:\users\USER\documents\github\perso\dicogis\virtenv2\Lib\site-p
ackages\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "modules\georeaders\gdal_exceptions_handler.py", line 23, in <module>
  File "site-packages\future\standard_library\__init__.py", line 457, in install
_aliases
ImportError: No module named UserList
[6388] Failed to execute script DicoGIS
[6388] LOADER: OK.
[6388] LOADER: Cleaning up Python interpreter.
```

It seems to be related to future packages, but I'm not able to solve it by myself.
[spec file is located here](https://github.com/Guts/DicoGIS/blob/master/bundle_dicogis.spec).

**Comment by nchammas** [comment]
I think I'm hitting this issue with PyInstaller 3.3.

`botocore` has a dependency on `configparser` via `six` which PyInstaller is not picking up, so I have to add `configparser` as a hidden import.

**Comment by pimplesushant-perennial** [comment]
@nchammas can you provide steps to add `configparser` as a hidden import.

**Comment by nchammas** [comment]
Just call `pyinstaller --hidden-import configparser`. Please refer to [the docs](https://pyinstaller.readthedocs.io/en/latest/usage.html) for basic questions like this.

**Comment by abdulzeedo** [comment]
my `configparser` started requiring `pkgutil` from a certain point which I needed to hidden-import. Why is that? It did work without it before and I did not update anything in between.
