### ISSUE TITLE
waf file missing from bootloader folder

### ISSUE THREAD

**Issue by Repiklis** [pyinstaller/pyinstaller#2146]
I was trying to follow the instructions for [building the bootloader](http://pyinstaller.readthedocs.io/en/latest/bootloader-building.html#building-the-bootloader), but I seem to be missing the waf file in the bootloader directory. I am using the latest development version, but it's the same on another PC with version 3.2. If this is intentional, I think that the manual should mention it.

**Comment by htgoebel** [comment]
The bootloader source is *not* installed if you are using `pip install …`. You need to use a source package of PyInstaller (either a git clone or download an archive from github).

**Comment by htgoebel** [comment]
No further comment since 5 month. Assume this is solved.

**Comment by Davido17** [comment]
> The bootloader source is _not_ installed if you are using `pip install …`. You need to use a source package of PyInstaller (either a git clone or download an archive from github).

how? Me I still face problem. it gives an error. also I don't know how to upgrade my pyinstaller to 4.6 so it can support the 3.10 version

**Comment by Davido17** [comment]
> No further comment since 5 month. Assume this is solved.

not yet

**Comment by eric15342335** [comment]
> not yet

Just download the source package from [here](https://github.com/pyinstaller/pyinstaller/archive/refs/heads/develop.zip).

>  I don't know how to upgrade my pyinstaller to 4.6 so it can support the 3.10 version

You can upgrade pyinstaller using `pip install -U pyinstaller` so it can support the 3.10 version
