### ISSUE TITLE
TypeError everytime PyInstaller cant find dependencies to some windows api dlls that does not have any imports.

### ISSUE THREAD

**Issue by AraHaan** [pyinstaller/pyinstaller#2184]
Every time I run Pyinstaller I get these Tracebacks it would be nice if PyInstaller was to suppress or fix this issue.
here is the entire console output:

```
2976 INFO: PyInstaller: 3.2
2977 INFO: Python: 3.5.1
2978 INFO: Platform: Windows-7-6.1.7601-SP1
2985 INFO: wrote E:\Users\Elsword\Desktop\DecoraterBot\Async\exe\DecoraterBot.sp
ec
3279 INFO: UPX is available.
3284 INFO: Extending PYTHONPATH with paths
['E:\\Users\\Elsword\\Desktop\\DecoraterBot\\Async\\exe',
 'E:\\Users\\Elsword\\Desktop\\DecoraterBot\\Async\\exe']
3285 INFO: checking Analysis
3327 INFO: Building because E:\Users\Elsword\Desktop\DecoraterBot\Async\exe\Deco
raterBot.py changed
3328 INFO: Initializing module dependency graph...
3360 INFO: Initializing module graph hooks...
3456 INFO: Analyzing base_library.zip ...
21948 INFO: running Analysis out00-Analysis.toc
22503 WARNING: Can not get binary dependencies for file: E:\Windows\system32\api
-ms-win-crt-runtime-l1-1-0.dll
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695
, in getImports
    return _getImports_pe(pth)
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122
, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
26453 WARNING: Can not get binary dependencies for file: E:\Windows\system32\api
-ms-win-crt-heap-l1-1-0.dll
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695
, in getImports
    return _getImports_pe(pth)
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122
, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
26486 WARNING: Can not get binary dependencies for file: E:\Windows\system32\api
-ms-win-crt-locale-l1-1-0.dll
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695
, in getImports
    return _getImports_pe(pth)
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122
, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
26631 WARNING: Can not get binary dependencies for file: E:\Windows\system32\api
-ms-win-crt-stdio-l1-1-0.dll
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695
, in getImports
    return _getImports_pe(pth)
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122
, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
26867 WARNING: Can not get binary dependencies for file: E:\Windows\system32\api
-ms-win-crt-math-l1-1-0.dll
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695
, in getImports
    return _getImports_pe(pth)
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122
, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
26909 WARNING: Can not get binary dependencies for file: E:\Windows\system32\api
-ms-win-crt-environment-l1-1-0.dll
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695
, in getImports
    return _getImports_pe(pth)
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122
, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
27021 WARNING: Can not get binary dependencies for file: E:\Windows\system32\api
-ms-win-crt-convert-l1-1-0.dll
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695
, in getImports
    return _getImports_pe(pth)
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122
, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
27234 WARNING: Can not get binary dependencies for file: E:\Windows\system32\api
-ms-win-crt-string-l1-1-0.dll
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695
, in getImports
    return _getImports_pe(pth)
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122
, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
27324 WARNING: Can not get binary dependencies for file: E:\Windows\system32\api
-ms-win-crt-process-l1-1-0.dll
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695
, in getImports
    return _getImports_pe(pth)
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122
, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
27375 WARNING: Can not get binary dependencies for file: E:\Windows\system32\api
-ms-win-crt-conio-l1-1-0.dll
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695
, in getImports
    return _getImports_pe(pth)
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122
, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
27466 WARNING: Can not get binary dependencies for file: E:\Windows\system32\api
-ms-win-crt-filesystem-l1-1-0.dll
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695
, in getImports
    return _getImports_pe(pth)
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122
, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
27542 WARNING: Can not get binary dependencies for file: E:\Windows\system32\api
-ms-win-crt-time-l1-1-0.dll
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695
, in getImports
    return _getImports_pe(pth)
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122
, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
27558 INFO: Caching module hooks...
27611 INFO: Analyzing E:\Users\Elsword\Desktop\DecoraterBot\Async\exe\DecoraterB
ot.py
36447 INFO: Loading module hooks...
36463 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
36593 INFO: Loading module hook "hook-pydoc.py"...
36621 INFO: Loading module hook "hook-encodings.py"...
36981 INFO: Loading module hook "hook-xml.py"...
40905 INFO: Looking for ctypes DLLs
40972 INFO: Analyzing run-time hooks ...
41044 INFO: Looking for dynamic libraries
45751 WARNING: Can not get binary dependencies for file: E:\Windows\system32\api
-ms-win-crt-utility-l1-1-0.dll
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695
, in getImports
    return _getImports_pe(pth)
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122
, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
51380 INFO: Looking for eggs
51381 INFO: Using Python library E:\Python35\python35.dll
51382 INFO: Found binding redirects:
[]
51431 INFO: Warnings written to E:\Users\Elsword\Desktop\DecoraterBot\Async\exe\
build\DecoraterBot\warnDecoraterBot.txt
51542 INFO: checking PYZ
51571 INFO: Building because toc changed
51572 INFO: Building PYZ (ZlibArchive) E:\Users\Elsword\Desktop\DecoraterBot\Asy
nc\exe\build\DecoraterBot\out00-PYZ.pyz
55131 INFO: checking PKG
55143 INFO: Building because toc changed
55144 INFO: Building PKG (CArchive) out00-PKG.pkg
59118 INFO: Bootloader E:\Python35\lib\site-packages\PyInstaller\bootloader\Wind
ows-32bit\run.exe
59120 INFO: checking EXE
59139 INFO: Rebuilding out00-EXE.toc because DecoraterBot.exe missing
59140 INFO: Building EXE from out00-EXE.toc
59208 INFO: SRCPATH [('E:\\Users\\Elsword\\Desktop\\DecoraterBot\\Async\\exe\\VP
.ico', None)]
59208 INFO: Updating icons from ['E:\\Users\\Elsword\\Desktop\\DecoraterBot\\Asy
nc\\exe\\VP.ico'] to E:\Users\Elsword\AppData\Local\Temp\tmp0nmixpi5
59239 INFO: Writing RT_GROUP_ICON 0 resource with 76 bytes
59240 INFO: Writing RT_ICON 1 resource with 3752 bytes
59242 INFO: Writing RT_ICON 2 resource with 2216 bytes
59243 INFO: Writing RT_ICON 3 resource with 1384 bytes
59245 INFO: Writing RT_ICON 4 resource with 204840 bytes
59248 INFO: Writing RT_ICON 5 resource with 270376 bytes
59255 INFO: Appending archive to EXE E:\Users\Elsword\Desktop\DecoraterBot\Async
\exe\\Build\DecoraterBot.exe
```

**Comment by stephenrauch** [comment]
The wiki has a [nice page on how to report bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs) so that the devs have the best chance of helping you. Having said that, this appears to be a duplicate of #1970 and #2014.  A fix has been merged and is on the development tip. From the wiki:

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;_Please try latest development version and let us know if the bug is already fixed there. Simply use_

```
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   _to install the latest git version._

That may get you going.  Please report back...

**Comment by AraHaan** [comment]
Ok, seems good also Can you have the latest Dev reference the latest ``setuptools`` as it works fine with that as well?

**Comment by stephenrauch** [comment]
Fixed by #1981

**Comment by AraHaan** [comment]
oh I noticed it did not fully fix the issue just now on the other as well after importing (hackingly) ``html`` you should add change where if it is python 3 do not try to add ``HTMLParser`` as that was changed to ``html.parser``.
Anyway the new output from the dev:

```
572 INFO: PyInstaller: 3.2
572 INFO: Python: 3.5.1
573 INFO: Platform: Windows-7-6.1.7601-SP1
577 INFO: wrote E:\Users\Elsword\Desktop\DecoraterBot\Async\exe\DecoraterBot.spe
c
725 INFO: UPX is available.
731 INFO: Extending PYTHONPATH with paths
['E:\\Users\\Elsword\\Desktop\\DecoraterBot\\Async\\exe',
 'E:\\Users\\Elsword\\Desktop\\DecoraterBot\\Async\\exe']
733 INFO: checking Analysis
755 INFO: Building because E:\Users\Elsword\Desktop\DecoraterBot\Async\exe\Decor
aterBot.py changed
756 INFO: Initializing module dependency graph...
765 INFO: Initializing module graph hooks...
776 INFO: Analyzing base_library.zip ...
12823 INFO: running Analysis out00-Analysis.toc
13180 WARNING: Can not get binary dependencies for file: E:\Windows\system32\api
-ms-win-crt-heap-l1-1-0.dll
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695
, in getImports
    return _getImports_pe(pth)
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122
, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
15234 WARNING: Can not get binary dependencies for file: E:\Windows\system32\api
-ms-win-crt-locale-l1-1-0.dll
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695
, in getImports
    return _getImports_pe(pth)
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122
, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
15689 WARNING: Can not get binary dependencies for file: E:\Windows\system32\api
-ms-win-crt-math-l1-1-0.dll
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695
, in getImports
    return _getImports_pe(pth)
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122
, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
15780 WARNING: Can not get binary dependencies for file: E:\Windows\system32\api
-ms-win-crt-runtime-l1-1-0.dll
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695
, in getImports
    return _getImports_pe(pth)
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122
, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
15886 WARNING: Can not get binary dependencies for file: E:\Windows\system32\api
-ms-win-crt-stdio-l1-1-0.dll
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695
, in getImports
    return _getImports_pe(pth)
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122
, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
15926 WARNING: Can not get binary dependencies for file: E:\Windows\system32\api
-ms-win-crt-process-l1-1-0.dll
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695
, in getImports
    return _getImports_pe(pth)
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122
, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
15950 WARNING: Can not get binary dependencies for file: E:\Windows\system32\api
-ms-win-crt-environment-l1-1-0.dll
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695
, in getImports
    return _getImports_pe(pth)
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122
, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
16009 WARNING: Can not get binary dependencies for file: E:\Windows\system32\api
-ms-win-crt-filesystem-l1-1-0.dll
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695
, in getImports
    return _getImports_pe(pth)
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122
, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
16097 WARNING: Can not get binary dependencies for file: E:\Windows\system32\api
-ms-win-crt-convert-l1-1-0.dll
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695
, in getImports
    return _getImports_pe(pth)
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122
, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
16149 WARNING: Can not get binary dependencies for file: E:\Windows\system32\api
-ms-win-crt-time-l1-1-0.dll
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695
, in getImports
    return _getImports_pe(pth)
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122
, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
16270 WARNING: Can not get binary dependencies for file: E:\Windows\system32\api
-ms-win-crt-string-l1-1-0.dll
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695
, in getImports
    return _getImports_pe(pth)
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122
, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
16299 WARNING: Can not get binary dependencies for file: E:\Windows\system32\api
-ms-win-crt-conio-l1-1-0.dll
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695
, in getImports
    return _getImports_pe(pth)
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122
, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
16307 INFO: Caching module hooks...
16333 INFO: Analyzing E:\Users\Elsword\Desktop\DecoraterBot\Async\exe\DecoraterB
ot.py
19957 INFO: Loading module hooks...
19959 INFO: Loading module hook "hook-encodings.py"...
20053 INFO: Loading module hook "hook-xml.py"...
20989 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
20993 INFO: Loading module hook "hook-pydoc.py"...
21090 INFO: Looking for ctypes DLLs
21149 INFO: Analyzing run-time hooks ...
21215 INFO: Looking for dynamic libraries
24613 WARNING: Can not get binary dependencies for file: E:\Windows\system32\api
-ms-win-crt-utility-l1-1-0.dll
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 695
, in getImports
    return _getImports_pe(pth)
  File "E:\Python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 122
, in _getImports_pe
    dll, _ = sym.forwarder.split('.')
TypeError: a bytes-like object is required, not 'str'
29862 INFO: Looking for eggs
29866 INFO: Using Python library E:\Python35\python35.dll
29870 INFO: Found binding redirects:
[]
29922 INFO: Warnings written to E:\Users\Elsword\Desktop\DecoraterBot\Async\exe\
build\DecoraterBot\warnDecoraterBot.txt
29967 INFO: checking PYZ
29977 INFO: Building because toc changed
29978 INFO: Building PYZ (ZlibArchive) E:\Users\Elsword\Desktop\DecoraterBot\Asy
nc\exe\build\DecoraterBot\out00-PYZ.pyz
33661 INFO: checking PKG
33664 INFO: Building because toc changed
33665 INFO: Building PKG (CArchive) out00-PKG.pkg
34995 INFO: Bootloader E:\Python35\lib\site-packages\PyInstaller\bootloader\Wind
ows-32bit\run.exe
34996 INFO: checking EXE
35000 INFO: Rebuilding out00-EXE.toc because DecoraterBot.exe missing
35002 INFO: Building EXE from out00-EXE.toc
35010 INFO: SRCPATH [('E:\\Users\\Elsword\\Desktop\\DecoraterBot\\Async\\exe\\VP
.ico', None)]
35011 INFO: Updating icons from ['E:\\Users\\Elsword\\Desktop\\DecoraterBot\\Asy
nc\\exe\\VP.ico'] to E:\Users\Elsword\AppData\Local\Temp\tmph5x1c4j5
35017 INFO: Writing RT_GROUP_ICON 0 resource with 76 bytes
35018 INFO: Writing RT_ICON 1 resource with 3752 bytes
35019 INFO: Writing RT_ICON 2 resource with 2216 bytes
35019 INFO: Writing RT_ICON 3 resource with 1384 bytes
35020 INFO: Writing RT_ICON 4 resource with 204840 bytes
35021 INFO: Writing RT_ICON 5 resource with 270376 bytes
35032 INFO: Appending archive to EXE E:\Users\Elsword\Desktop\DecoraterBot\Async
\exe\\Build\DecoraterBot.exe
Press any key to continue . . .```

**Comment by AraHaan** [comment]
Fixed by adding this to this:

```diff
    # We must also read the exports table to find forwarded symbols:
    # http://blogs.msdn.com/b/oldnewthing/archive/2006/07/19/671238.aspx
    exportSymbols = getattr(pe, 'DIRECTORY_ENTRY_EXPORT', None)
    if exportSymbols:
        for sym in exportSymbols.symbols:
            if sym.forwarder is not None:
                # sym.forwarder is for example 'KERNEL32.EnterCriticalSection'
+                if type(sym.forwarder) == string:
+                    bytes(sym.forwarder, 'utf-8')
                dll, _ = sym.forwarder.split('.')
                dlls.add(winutils.convert_dll_name_to_str(dll) + ".dll")
```

**Comment by codewarrior0** [comment]
>Anyway the new output from the dev:
>572 INFO: PyInstaller: 3.2

This is not the `develop` version. This issue is already fixed in the latest `develop`
