### ISSUE TITLE
Mac: "Launching" app when it's already open doesn't put it in foreground

### ISSUE THREAD

**Issue by mherrmann** [pyinstaller/pyinstaller#2616]
On macOS, launching applications when they are already open puts them in the foreground. For instance:

```
open -a TextEdit
# TextEdit opened. Leave it open. Switch back to the terminal and type again:
open -a TextEdit
# TextEdit is again in the foreground, Terminal in the background.
```

This also works with apps built with py2app:

```
git clone https://github.com/adamw523/simple_pyobjc_cocoa_xib
cd simple_pyobjc_cocoa_xib
virtualenv --system-site-packages venv
source venv/bin/activate
python setup.py py2app -A
ln -s "`pwd`/dist/SimpleXibDemo.app" /Applications/SimpleXibDemo.app

open -a SimpleXibDemo
open -a SimpleXibDemo
```

But it doesn't work with apps built with PyInstaller. Proceeding from the above command line:

```
# Preserve the .nib file compiled by py2app:
cp dist/SimpleXibDemo.app/Contents/Resources/SimpleXibDemo.nib .

rm -rf build/ dist/

# Build with PyInstaller
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
pyinstaller --name SimpleXibDemo --windowed SimpleXibDemo.py
cp SimpleXibDemo.nib dist/SimpleXibDemo.app/Contents/Resources/

# Run:
open -a SimpleXibDemo
# SimpleXibDemo is in the foreground. Go back to terminal and type:
open -a SimpleXibDemo
# SimpleXibDemo should be in foreground but isn't.
```

I am encountering exactly the same problem with a [PyQt5 app](https://fman.io) I'm working on. So the problem is not specific to PyObjC.

**Comment by mherrmann** [comment]
Without knowing PyInstaller well enough, I suspect it is because of the way it launches. When starting an app built with PyInstaller, it spawns a new process:

![image](https://cloud.githubusercontent.com/assets/1076393/26237671/69dc8ee4-3c76-11e7-98a6-377f9771f008.png)

I am guessing the parent process sets up the environment, and the child process does the actual GUI display. I suspect that macOS only "sees" the parent process, thinks it doesn't have a GUI and is thus unable to "switch to it".

Or, it could be caused by the parent process "Not Responding" in the screenshot.

**Comment by xoviat** [comment]
PyInstaller [already uses](https://github.com/pyinstaller/pyinstaller/blob/develop/bootloader/src/pyi_main.c#L105) a single process for windows. I'm not sure what py2app does, but if you're familiar with C, then you could look at changing this for mac. This additional complexity comes from --onefile, but it shouldn't affect --onedir.

**Comment by tallforasmurf** [comment]
Possibly relevant: [pyi_parent_to_background](https://github.com/pyinstaller/pyinstaller/blob/a70b20e4de6a6817987d28ca9f3201c8105fd858/bootloader/src/pyi_launch.c#L578) called by bootloader in the child process.

**Comment by mherrmann** [comment]
So @xoviat do you think the problem could be solved by simply moving the `#ifdef _WIN32` you linked to 7 lines down?

**Comment by xoviat** [comment]
You could try changing it to `#ifdef _WIN32 || __APPLE__`, but I strongly suspect that's not the only change required. This really needs to be changed, but I think that as soon as you change that, some other problems will appear, which will need to be fixed as well. If you're familiar with C and osx, then it might take a few hours to fix these problems, but if you're not, then it could take significantly longer. I cannot do anything more on this problem than make some recommendations because I don't have access to osx, which means that it's not going to be possible for me to resolve these issues.

**Comment by mherrmann** [comment]
Amazing. That works!

```
#if defined(_WIN32) || defined(__APPLE__)
```

My app runs perfectly fine with this change - and the "not coming to foreground" issue is fixed. I'll create a PR to get this merged (or at least reviewed) by PyInstaller. Thanks @xoviat!

**Comment by xoviat** [comment]
Wow! I did not expect it to be that easy!

**Comment by cbenhagen** [comment]
Unfortunately this issue is only partially fixed as reopening still does not work in `--onefile` mode. I opened a new issue for this: https://github.com/pyinstaller/pyinstaller/issues/4234
