### ISSUE TITLE
Running errors when either matplotlib or scipy imported

### ISSUE THREAD

**Issue by barryghall** [pyinstaller/pyinstaller#3134]
Under OS X 10.13 (High Sierra) if either matplotlib or scipy is imported I get the same run time error when the stand-alone executable compiled by pyinstaller 3.3 is run.  The problem began when I updated from OS X 10.12 to 10.13. I updated pyinstaller to 3.3, matplotlib to 2.1.1 and scipy to 1.0.0.  I am running Anaconda python 2.7.14.

For example, LinePlot1.py imports matplotlib.

When compiled to the stand-alone executable and the executable is run I get the following:

	Scorpion Testing barry$ ./LinePlot1
	Traceback (most recent call last):
	  File "site-packages/PyInstaller/loader/rthooks/pyi_rth_pkgres.py", line 11, in <module>
	  File "lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
	  File "site-packages/pkg_resources/__init__.py", line 1040, in <module>
	  File "site-packages/pkg_resources/__init__.py", line 1043, in Environment
	  File "site-packages/pkg_resources/__init__.py", line 272, in get_supported_platform
	  File "site-packages/pkg_resources/__init__.py", line 478, in get_build_platform
	  File "sysconfig.py", line 617, in get_platform
	  File "sysconfig.py", line 481, in get_config_vars
	  File "sysconfig.py", line 364, in _init_posix
	ImportError: No module named _sysconfigdata
	[23611] Failed to execute script pyi_rth_pkgres
	
The _sysconfigdata module does exist

	/Users/barry/anaconda2/lib/python2.7/_sysconfigdata.py
	
but pyinstaller seems unable to find it.
The pyinstaller manual says:

	Some Python scripts import modules in ways that PyInstaller cannot detect: for example, by using the __import__() function with variable data, or manipulating the sys.path value at run time. If your script requires files that PyInstaller does not know about, you must help it:

		You can give additional files on the pyinstaller command line.
		You can give additional import paths on the command line.

How can I give an additional import path on the command line?
When I tried

	pyinstaller -F --hidden-import='/Users/barry/anaconda2/lib/python2.7/_sysconfigdata.py' LinePlot1.py
the log file included an error saying that the file does not exist.

I get exactly the same run time error when running a stand-alone executable that includes an import scipy statement.
Thanks for any help

**Comment by htgoebel** [comment]
This is solved in PyInstaller 3.3.1

**Comment by barryghall** [comment]
Sorry, but it is not solved.  Using Anaconda python 2.7.14 under osx 10.13.1 updated pyinstaller from 3.3 to 3.3.1 using pip (because conda does not know about v 3.3.1).

The problem remains.

Barry G. Hall
