### ISSUE TITLE
not found python library in msys2

### ISSUE THREAD

**Issue by welitonfreitas** [pyinstaller/pyinstaller#3167]
on msys2 with python 3.6.4 returned this error:

```python
158153 INFO: Python library not in binary dependencies. Doing additional searching...
Traceback (most recent call last):
  File "C:\msys32_2\mingw32\bin\pyinstaller-script.py", line 11, in <module>
    load_entry_point('PyInstaller==3.3.1', 'console_scripts', 'pyinstaller')()
  File "C:/msys32_2/mingw32/lib/python3.6/site-packages\PyInstaller\__main__.py", line 94, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:/msys32_2/mingw32/lib/python3.6/site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:/msys32_2/mingw32/lib/python3.6/site-packages\PyInstaller\building\build_main.py", line 791, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:/msys32_2/mingw32/lib/python3.6/site-packages\PyInstaller\building\build_main.py", line 737, in build
    exec(text, spec_namespace)
  File "<string>", line 15, in <module>
  File "C:/msys32_2/mingw32/lib/python3.6/site-packages\PyInstaller\building\build_main.py", line 213, in __init__
    self.__postinit__()
  File "C:/msys32_2/mingw32/lib/python3.6/site-packages\PyInstaller\building\datastruct.py", line 161, in __postinit__
    self.assemble()
  File "C:/msys32_2/mingw32/lib/python3.6/site-packages\PyInstaller\building\build_main.py", line 545, in assemble
    self._check_python_library(self.binaries)
  File "C:/msys32_2/mingw32/lib/python3.6/site-packages\PyInstaller\building\build_main.py", line 629, in _check_python_library
    raise IOError(msg)
OSError: Python library not found: python36.dll, libpython3.6.dll
This would mean your Python installation doesn't come with proper library files.
This usually happens by missing development package, or unsuitable build parameters of Python installation.

* On Debian/Ubuntu, you would need to install Python development packages
  * apt-get install python3-dev
  * apt-get install python-dev
* If you're building Python by yourself, please rebuild your Python with `--enable-shared` (or, `--enable-framework` on Darwin)

```
in the msys enviroment exist only libpythonX.Xm.dll like cygwin

**Comment by OzymandiasTheGreat** [comment]
Having this issue. Tried installing development version from github but the issue persists.

**Comment by htgoebel** [comment]
The pull-request solving this has jsut been merged. Please try the current development version.

Closing since I assume this is fixed.

**Comment by avery-laird** [comment]
I'm still having this problem with python 3.6.5:

```
46 INFO: PyInstaller: 3.3.1
46 INFO: Python: 3.6.5
46 INFO: Platform: Windows-10-10.0.16299-SP0
62 INFO: wrote C:/msys64/home/avery/mips/gui.spec
62 INFO: UPX is not available.
62 INFO: Extending PYTHONPATH with paths
['C:/msys64/home/avery/mips', 'C:/msys64/home/avery/mips']
62 INFO: checking Analysis
62 INFO: Building Analysis because out00-Analysis.toc is non existent
62 INFO: Initializing module dependency graph...
62 INFO: Initializing module graph hooks...
62 INFO: Analyzing base_library.zip ...
3333 INFO: running Analysis out00-Analysis.toc
3365 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of f                                                                                                                                  inal executable
  required by C:/msys64/mingw32/bin/python3.exe
3506 INFO: Caching module hooks...
3506 INFO: Analyzing C:/msys64/home/avery/mips/gui.py
3599 INFO: Processing pre-safe import module hook   gi.repository.Gtk
3741 INFO: Loading module hooks...
3741 INFO: Loading module hook "hook-encodings.py"...
3819 INFO: Loading module hook "hook-gi.py"...
3819 INFO: Loading module hook "hook-gi.repository.Gtk.py"...
6427 INFO: Processing pre-safe import module hook   gi.repository.GObject
6474 INFO: Processing pre-safe import module hook   gi.repository.GLib
6474 INFO: Processing pre-safe import module hook   gi.repository.Gdk
6474 INFO: Processing pre-safe import module hook   gi.repository.Atk
6474 INFO: Loading module hook "hook-pydoc.py"...
6474 INFO: Loading module hook "hook-xml.py"...
6678 INFO: Loading module hook "hook-gi.repository.Atk.py"...
6867 INFO: Loading module hook "hook-gi.repository.Gdk.py"...
7054 INFO: Processing pre-safe import module hook   gi.repository.cairo
7054 INFO: Processing pre-safe import module hook   gi.repository.Pango
7054 INFO: Processing pre-safe import module hook   gi.repository.Gio
7054 INFO: Processing pre-safe import module hook   gi.repository.GdkPixbuf
7054 WARNING: Hidden import "gi._gi_cairo" not found!
7054 INFO: Loading module hook "hook-gi.repository.GdkPixbuf.py"...
7554 INFO: Processing pre-safe import module hook   gi.repository.GModule
7554 INFO: Loading module hook "hook-gi.repository.Gio.py"...
7821 INFO: Loading module hook "hook-gi.repository.GLib.py"...
8134 INFO: Loading module hook "hook-gi.repository.GModule.py"...
8305 INFO: Loading module hook "hook-gi.repository.GObject.py"...
8493 WARNING: Hidden import "gi._gobject" not found!
8493 INFO: Loading module hook "hook-gi.repository.Pango.py"...
8666 INFO: Loading module hook "hook-gi.repository.cairo.py"...
8869 INFO: Looking for ctypes DLLs
8869 WARNING: library python dll required via ctypes not found
8869 WARNING: library libpython%d.%d.dll required via ctypes not found
8869 WARNING: library PyOS_getsig.dll required via ctypes not found
8869 INFO: Analyzing run-time hooks ...
8869 INFO: Including run-time hook 'pyi_rth_gtk.py'
8885 INFO: Including run-time hook 'pyi_rth_glib.py'
8885 INFO: Including run-time hook 'pyi_rth_gdkpixbuf.py'
8885 INFO: Including run-time hook 'pyi_rth_gio.py'
8885 INFO: Including run-time hook 'pyi_rth_gi.py'
8885 INFO: Looking for dynamic libraries
10983 INFO: Looking for eggs
10983 INFO: Python library not in binary dependencies. Doing additional searchin                                                                                                                                  g...
Traceback (most recent call last):
  File "C:\msys64\mingw32\bin\pyinstaller-script.py", line 11, in <module>
    load_entry_point('PyInstaller==3.3.1', 'console_scripts', 'pyinstaller')()
  File "C:/msys64/mingw32/lib/python3.6/site-packages\PyInstaller\__main__.py",                                                                                                                                   line 94, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:/msys64/mingw32/lib/python3.6/site-packages\PyInstaller\__main__.py",                                                                                                                                   line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:/msys64/mingw32/lib/python3.6/site-packages\PyInstaller\building\build                                                                                                                                  _main.py", line 791, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'                                                                                                                                  ))
  File "C:/msys64/mingw32/lib/python3.6/site-packages\PyInstaller\building\build                                                                                                                                  _main.py", line 737, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "C:/msys64/mingw32/lib/python3.6/site-packages\PyInstaller\building\build                                                                                                                                  _main.py", line 213, in __init__
    self.__postinit__()
  File "C:/msys64/mingw32/lib/python3.6/site-packages\PyInstaller\building\datas                                                                                                                                  truct.py", line 161, in __postinit__
    self.assemble()
  File "C:/msys64/mingw32/lib/python3.6/site-packages\PyInstaller\building\build                                                                                                                                  _main.py", line 545, in assemble
    self._check_python_library(self.binaries)
  File "C:/msys64/mingw32/lib/python3.6/site-packages\PyInstaller\building\build                                                                                                                                  _main.py", line 629, in _check_python_library
    raise IOError(msg)
OSError: Python library not found: libpython3.6.dll, python36.dll
This would mean your Python installation doesn't come with proper library files.
This usually happens by missing development package, or unsuitable build paramet                                                                                                                                  ers of Python installation.

* On Debian/Ubuntu, you would need to install Python development packages
  * apt-get install python3-dev
  * apt-get install python-dev
* If you're building Python by yourself, please rebuild your Python with `--enab                                                                                                                                  le-shared` (or, `--enable-framework` on Darwin)
```

Not sure which package is meant exactly by "current development version," but the python package was installed just a few hours ago. I've never used msys2 before, but I couldn't find any devel packages in the github repo.

Any ideas for a fix?
