### ISSUE TITLE
Pyinstaller 3.4 can't find PyQt5.sip and insists on Qt5.9.2 msvc plugin

### ISSUE THREAD

**Issue by TongZhai** [pyinstaller/pyinstaller#3750]
I am developing pyqt5.9.6 application with python 3.6 using the development stack that comes with the OSGeo4W64 installer for QGIS software. Below is my testing script:

```
import os, sys
from PyQt5 import QtCore, QtGui
from PyQt5.QtGui import *
from PyQt5.QtWidgets import QApplication
from PyQt5 import sip
app = QApplication(sys.argv)
sys.exit(app.exec_())
```

I am using PyCharm 2018.2 community version as my IDE, pyinstaller is version 3.4. 

The spec file for this testing script is as below:
```
# -*- mode: python -*-

block_cipher = None

a = Analysis(['pyinstaller_test.py'],
             pathex=['C:\\dev\\src'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='pyinstaller_test',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='pyinstaller_test')
```
It failed when I tried to package it via ```pyinstaller --clean pyinstaller_test.spec```, below is the output/failure message:
```
79 INFO: PyInstaller: 3.4
79 INFO: Python: 3.6.0
79 INFO: Platform: Windows-7-6.1.7601-SP1
90 INFO: UPX is not available.
90 INFO: Removing temporary files and cleaning cache in C:\Users\XXX\AppData\Roaming\pyinstaller
90 INFO: Extending PYTHONPATH with paths
['C:\\dev\\src',
 'C:\\dev\\src']
90 INFO: checking Analysis
90 INFO: Building Analysis because Analysis-00.toc is non existent
90 INFO: Initializing module dependency graph...
90 INFO: Initializing module graph hooks...
90 INFO: Analyzing base_library.zip ...
3840 INFO: running Analysis Analysis-00.toc
4590 INFO: Caching module hooks...
4600 INFO: Analyzing pyinstaller_test.py
4640 INFO: Loading module hooks...
4640 INFO: Loading module hook "hook-encodings.py"...
4730 INFO: Loading module hook "hook-pydoc.py"...
4730 INFO: Loading module hook "hook-PyQt5.py"...
4820 INFO: Loading module hook "hook-PyQt5.QtCore.py"...
4920 WARNING: Unable to find Qt5 translations C:/src/Qt/Qt5.9.2-2/5.9.2/msvc2015_64/translations\qtbase_*.qm. These translations were not packaged.
4920 INFO: Loading module hook "hook-PyQt5.QtGui.py"...
Traceback (most recent call last):
  File "c:\OSGeo4W64\apps\Python36\Scripts\pyinstaller-script.py", line 11, in <module>
    load_entry_point('PyInstaller==3.4', 'console_scripts', 'pyinstaller')()
  File "C:\OSGeo4W64\apps\Python36\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\OSGeo4W64\apps\Python36\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\OSGeo4W64\apps\Python36\lib\site-packages\PyInstaller\building\build_main.py", line 838, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\OSGeo4W64\apps\Python36\lib\site-packages\PyInstaller\building\build_main.py", line 784, in build
    exec(text, spec_namespace)
  File "<string>", line 17, in <module>
  File "C:\OSGeo4W64\apps\Python36\lib\site-packages\PyInstaller\building\build_main.py", line 241, in __init__
    self.__postinit__()
  File "C:\OSGeo4W64\apps\Python36\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
    self.assemble()
  File "C:\OSGeo4W64\apps\Python36\lib\site-packages\PyInstaller\building\build_main.py", line 500, in assemble
    module_hook.post_graph()
  File "C:\OSGeo4W64\apps\Python36\lib\site-packages\PyInstaller\building\imphook.py", line 410, in post_graph
    self._load_hook_module()
  File "C:\OSGeo4W64\apps\Python36\lib\site-packages\PyInstaller\building\imphook.py", line 377, in _load_hook_module
    self.hook_module_name, self.hook_filename)
  File "C:\OSGeo4W64\apps\Python36\lib\site-packages\PyInstaller\compat.py", line 736, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 251, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "C:\OSGeo4W64\apps\Python36\lib\site-packages\PyInstaller\hooks\hook-PyQt5.QtGui.py", line 11, in <module>
    hiddenimports, binaries, datas = add_qt5_dependencies(__file__)
  File "C:\OSGeo4W64\apps\Python36\lib\site-packages\PyInstaller\utils\hooks\qt.py", line 514, in add_qt5_dependencies
    more_binaries = qt_plugins_binaries(plugin, namespace=namespace)
  File "C:\OSGeo4W64\apps\Python36\lib\site-packages\PyInstaller\utils\hooks\qt.py", line 132, in qt_plugins_binaries
    pdir = qt_plugins_dir(namespace=namespace)
  File "C:\OSGeo4W64\apps\Python36\lib\site-packages\PyInstaller\utils\hooks\qt.py", line 117, in qt_plugins_dir
    """.format(namespace, ", ".join(paths)))
Exception:
            Cannot find existing PyQt5 plugin directories
            Paths checked: C:/src/Qt/Qt5.9.2-2/5.9.2/msvc2015_64/plugins
```
What's puzzling is that why is it looking for Qt5.9.2? is it hard coded in pyinstaller 3.4?
I've tried adding --hidden-import=PyQt5.sip and from PyQt5 import sip, none worked. 

This is essentially the same issue as #3630, but it was closed and it wouldn't allow additional comments from users.

**Comment by bjones1** [comment]
Try the current development head. A recent commit might fix this.

**Comment by TongZhai** [comment]
@bjones1 I am a little out of practice on pyinstaller, you mean run it from source code? or is there a nightly build of something?

**Comment by TongZhai** [comment]
Actually, I got pass the loading of Qt5 stuff using the version 3.3.1, so whatever that is changed after that actually made it worse for OSGeo4W stack

**Comment by bjones1** [comment]
Per https://pyinstaller.readthedocs.io/en/stable/when-things-go-wrong.html#getting-the-latest-version:

```
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

PyInstaller 3.4 uses an improved approach to detecting Qt libraries; hopefully, this is already fixed in master.

**Comment by TongZhai** [comment]
@bjones1 Just tried this develop version after pip install, still failed, below is the complete log while packaging:
```
218 INFO: PyInstaller: 3.5.dev0+268f57a06
218 INFO: Python: 3.6.0
219 INFO: Platform: Windows-7-6.1.7601-SP1
221 INFO: UPX is not available.
221 INFO: Removing temporary files and cleaning cache in C:\Users\XXX\AppData\Roaming\pyinstaller
237 INFO: Extending PYTHONPATH with paths
['C:\\dev\\src',
 'C:\\OSGeo4W64\\apps\\Python36\\lib\\site-packages\\PyQt5',
 'C:\\dev\\src']
238 INFO: checking Analysis
239 INFO: Building Analysis because Analysis-00.toc is non existent
239 INFO: Initializing module dependency graph...
243 INFO: Initializing module graph hooks...
245 INFO: Analyzing base_library.zip ...
4606 INFO: running Analysis Analysis-00.toc
4654 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\OSGeo4W64\bin\python3.exe
5598 INFO: Caching module hooks...
5606 INFO: Analyzing qgis_test.py
6073 INFO: Loading module hooks...
6074 INFO: Loading module hook "hook-encodings.py"...
6178 INFO: Loading module hook "hook-pydoc.py"...
6179 INFO: Loading module hook "hook-PyQt5.py"...
6610 WARNING: Hidden import "PyQt5.sip" not found!
6611 INFO: Loading module hook "hook-PyQt5.QtCore.py"...
6769 WARNING: Unable to find Qt5 translations qtbase_*.qm. These translations were not packaged.
6769 INFO: Loading module hook "hook-PyQt5.QtGui.py"...
Traceback (most recent call last):
  File "c:\OSGeo4W64\apps\Python36\Scripts\pyinstaller-script.py", line 11, in <module>
    load_entry_point('PyInstaller==3.5.dev0+268f57a06', 'console_scripts', 'pyinstaller')()
  File "C:\OSGeo4W64\apps\Python36\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\OSGeo4W64\apps\Python36\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\OSGeo4W64\apps\Python36\lib\site-packages\PyInstaller\building\build_main.py", line 838, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\OSGeo4W64\apps\Python36\lib\site-packages\PyInstaller\building\build_main.py", line 784, in build
    exec(text, spec_namespace)
  File "<string>", line 18, in <module>
  File "C:\OSGeo4W64\apps\Python36\lib\site-packages\PyInstaller\building\build_main.py", line 241, in __init__
    self.__postinit__()
  File "C:\OSGeo4W64\apps\Python36\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
    self.assemble()
  File "C:\OSGeo4W64\apps\Python36\lib\site-packages\PyInstaller\building\build_main.py", line 500, in assemble
    module_hook.post_graph()
  File "C:\OSGeo4W64\apps\Python36\lib\site-packages\PyInstaller\building\imphook.py", line 410, in post_graph
    self._load_hook_module()
  File "C:\OSGeo4W64\apps\Python36\lib\site-packages\PyInstaller\building\imphook.py", line 377, in _load_hook_module
    self.hook_module_name, self.hook_filename)
  File "C:\OSGeo4W64\apps\Python36\lib\site-packages\PyInstaller\compat.py", line 736, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 251, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "C:\OSGeo4W64\apps\Python36\lib\site-packages\PyInstaller\hooks\hook-PyQt5.QtGui.py", line 11, in <module>
    hiddenimports, binaries, datas = add_qt5_dependencies(__file__)
  File "C:\OSGeo4W64\apps\Python36\lib\site-packages\PyInstaller\utils\hooks\qt.py", line 517, in add_qt5_dependencies
    more_binaries = qt_plugins_binaries(plugin, namespace=namespace)
  File "C:\OSGeo4W64\apps\Python36\lib\site-packages\PyInstaller\utils\hooks\qt.py", line 135, in qt_plugins_binaries
    pdir = qt_plugins_dir(namespace=namespace)
  File "C:\OSGeo4W64\apps\Python36\lib\site-packages\PyInstaller\utils\hooks\qt.py", line 120, in qt_plugins_dir
    """.format(namespace, ", ".join(paths)))
Exception:
            Cannot find existing PyQt5 plugin directories
            Paths checked:
```

**Comment by bjones1** [comment]
Would you run this program and post the output?

``` Python
from PyQt5.QtCore import QLibraryInfo, QCoreApplication
from pprint import pprint

# QLibraryInfo isn't always valid until a QCoreApplication is
# instantiated.
app = QCoreApplication([])
paths = [x for x in dir(QLibraryInfo) if x.endswith('Path')]
location = {x: QLibraryInfo.location(getattr(QLibraryInfo, x))
            for x in paths}
try:
    version = QLibraryInfo.version().segments()
except AttributeError:
    version = None
pprint({
    'isDebugBuild': QLibraryInfo.isDebugBuild(),
    'version': version,
    'location': location,
})
```

**Comment by TongZhai** [comment]
@bjones1 Below is the output printout:
```
{'isDebugBuild': False,
 'location': {'ArchDataPath': '/',
              'BinariesPath': '',
              'DataPath': '/',
              'DocumentationPath': '/doc',
              'ExamplesPath': '/examples',
              'HeadersPath': '',
              'ImportsPath': '/imports',
              'LibrariesPath': '',
              'LibraryExecutablesPath': '/bin',
              'PluginsPath': '',
              'PrefixPath': '',
              'Qml2ImportsPath': '/qml',
              'SettingsPath': '',
              'TestsPath': '/tests',
              'TranslationsPath': ''},
 'version': [5, 9, 2]}
```

**Comment by bjones1** [comment]
Hmm, looks like this install of Qt is broken -- there's no valid `PluginsPath`. Most of the other paths also look broken. I'd suggest taking this problem up with your vendor.

**Comment by TongZhai** [comment]
@bjones1 This is the open source OSGeo4W's QGIS install that bundles PyQt5 libraries, these run in PyCharm environment without problem, also we have the same application in python 2.7 (also in OSGeo4W environment) and we used pyinstaller to package up this app without problem. We just recently migrated it to Python 3.6 version of the OSGeo4W QGIS install, now we are trying to get pyinstaller to work with this new stack. As I mentioned, pyinstaller 3.3.1 can actually package up the pyqt5 libs in this environment (but it fails with the pyqgis libs). I hope the capability of 3.3.1 version can at least be retained in new versions of pyinstaller. We developed everything for US EPA using open source libraries, nothing is proprietary and we are not selling the software, it is all open source on github, so I don't really have a vendor to turn to, hope we all help each other. Thanks.

**Comment by CarlosAlberto18** [comment]
{'isDebugBuild': False,
 'location': {'ArchDataPath': 'D:/Anaconda/Library',
              'BinariesPath': 'D:/Anaconda/Library/bin',
              'DataPath': 'D:/Anaconda/Library',
              'DocumentationPath': 'D:/Anaconda/Library/doc',
              'ExamplesPath': 'D:/Anaconda/Library/examples',
              'HeadersPath': 'D:/Anaconda/Library/include/qt',
              'ImportsPath': 'D:/Anaconda/Library/imports',
              'LibrariesPath': 'D:/Anaconda/Library/lib',
              'LibraryExecutablesPath': 'D:/Anaconda/Library/bin',
              'PluginsPath': 'D:/Anaconda/Library/plugins',
              'PrefixPath': 'D:/Anaconda/Library',
              'Qml2ImportsPath': 'D:/Anaconda/Library/qml',
              'SettingsPath': '',
              'TestsPath': 'D:/Anaconda/Library/tests',
              'TranslationsPath': 'D:/Anaconda/Library/translations'},
 'version': [5, 9, 7]}

**Comment by bjones1** [comment]
Use the development versions. It's fixed there.
