### ISSUE TITLE
sys.flags.utf8_mode is -1

### ISSUE THREAD

**Issue by petsuter** [pyinstaller/pyinstaller#3866]
Since Python 3.7 there is a [UTF-8 mode](https://www.python.org/dev/peps/pep-0540/).
`PYTHONUTF8=1` or `python -X utf8`  can be used to enable it.
`sys.flags.utf8_mode` can be used to check it. It should be `0` or `1`. But with PyInstaller, it is `-1` instead. I don't understand why. `-1` is treated as truthy, enabling the mode. Is it intended? I would like to leave the mode disabled.

**Comment by petsuter** [comment]
> `PYTHONUTF8=1` or `python -X utf8` can be used to enable it.

But neither of these can be used with PyInstaller to disable it.

**Comment by petsuter** [comment]
Apparently it's a bug in Python 3.7, already fixed in Python 3.7.1.

**Comment by htgoebel** [comment]
Thanks for finding out this is already fixed.

**Comment by petsuter** [comment]
Enabling the UTF8 mode via environment variable still doesn't work though:
```
C:\>mkdir test-pyinstaller && cd  test-pyinstaller 

C:\test-pyinstaller>py -3.7 --version
Python 3.7.1

C:\test-pyinstaller>py -3.7 -m pip install pyinstaller
Collecting pyinstaller
...
Successfully installed pyinstaller-3.4 ...

C:\test-pyinstaller>echo import sys; print("UTF8 mode is ", sys.flags.utf8_mode) >main.py

C:\test-pyinstaller>py -3.7 main.py
UTF8 mode is  0

C:\test-pyinstaller>py -3.7 -m PyInstaller main.py
45 INFO: PyInstaller: 3.4
46 INFO: Python: 3.7.1
... completed successfully.

C:\test-pyinstaller>dist\main\main.exe
UTF8 mode is  0

C:\test-pyinstaller>set PYTHONUTF8=1

C:\test-pyinstaller>py -3.7 main.py
UTF8 mode is  1

C:\test-pyinstaller>dist\main\main.exe
UTF8 mode is  0
```

[Discussing](https://discuss.python.org/t/sys-flags-utf8-mode-is-1/431/7) with CPython core developer Victor Stinner:
>I checked PyInstaller: it explicitly disable PYTHON environment variables. src/pyi_pythonlib.c:
> ```
> /* This flag ensures PYTHONPATH and PYTHONHOME are ignored by Python. */
> *PI_Py_IgnoreEnvironmentFlag = 1;
>```
>I suggest you to open an issue in PyInstaller, there is nothing Python can do for you

**Comment by BoboTiG** [comment]
:+1: for that issue. This is seems the root cause of #2032.
