### ISSUE TITLE
matplotlib import leading to hook-PyQt5.py call

### ISSUE THREAD

**Issue by james0807** [pyinstaller/pyinstaller#3997]
Hi,

I'm having some trouble with matplotlib and PyQt5.

Due to licencing issues, I cannot have PyQt installed, and i've got PySide2 instead.

I've written the following minimal working example that demonstrates the issue I'm facing which is essentially that pyinstaller calls hook-PyQt5.py even though PyQt5 isn't installed and in fact Qt5 isn't actually required.

```
import matplotlib
import matplotlib.pyplot as plt

plt.plot([1,2,3],[4,5,6])
plt.show()
```

Matplotlib version 3.0.2
Pyinstaller and python versions detailed in pyinstaller output below.

I can rectify this problem by manually excluding the PyQt5 module, however, it's not clear why this is necessary given the following logger output below : `55642 INFO: Excluding import 'PyQt5'`.

Below is the output from the command `pyinstaller mpltest.py`

I have tried looking in the hook-matplotlib.py and hook-matplotlib.backends.py but I can't see how PyQt5 gets forwarded as a requirement when it isn't installed and clearly isn't required given the compiled .exe runs fine when PyQt5 is manually excluded.

Any help would be greatly appreciated.

Thanks.

```
96 INFO: PyInstaller: 3.5.dev0+0d289e49b
96 INFO: Python: 3.6.1
96 INFO: Platform: Windows-10-10.0.15063-SP0
100 INFO: wrote C:\Users\james.richardson\GUI\mpltest.spec
104 INFO: UPX is not available.
107 INFO: Extending PYTHONPATH with paths
['C:\\Users\\james.richardson',
 'C:\\Users\\james.richardson\\GUI']
107 INFO: checking Analysis
107 INFO: Building Analysis because Analysis-00.toc is non existent
107 INFO: Initializing module dependency graph...
111 INFO: Initializing module graph hooks...
115 INFO: Analyzing base_library.zip ...
6972 INFO: running Analysis Analysis-00.toc
6996 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\Users\james.richardson\AppData\Local\Continuum\Anaconda3\envs\huffle_test\python.exe
7841 INFO: Caching module hooks...
7849 INFO: Analyzing C:\Users\james.richardson\huffle\GUI\mpltest.py
8329 INFO: Processing pre-find module path hook   distutils
16081 INFO: Processing pre-safe import module hook   setuptools.extern.six.moves
17097 INFO: Processing pre-find module path hook   site
17101 INFO: site: retargeting to fake-dir 'C:\\Users\\james.richardson\\AppData\\Local\\Continuum\\Anaconda3\\envs\\huffle_test\\lib\\site-packages\\PyInstaller\\fake-modules'
22382 INFO: Processing pre-safe import module hook   six.moves
54982 INFO: Loading module hooks...
54982 INFO: Loading module hook "hook-certifi.py"...
54982 INFO: Loading module hook "hook-cryptography.py"...
55461 INFO: Loading module hook "hook-distutils.py"...
55465 INFO: Loading module hook "hook-encodings.py"...
55604 INFO: Loading module hook "hook-IPython.py"...
55620 INFO: Excluding import 'matplotlib'
55620 INFO:   Removing import of matplotlib from module IPython.core.pylabtools
55620 INFO:   Removing import of matplotlib.pyplot from module IPython.core.pylabtools
55620 INFO:   Removing import of matplotlib._pylab_helpers from module IPython.core.pylabtools
55620 INFO:   Removing import of matplotlib.figure from module IPython.core.pylabtools
55620 INFO: Excluding import 'PySide'
55620 INFO:   Removing import of PySide from module IPython.external.qt_loaders
55636 INFO: Excluding import 'gtk'
55642 INFO: Excluding import 'PyQt5'
55650 INFO:   Removing import of PyQt5.QtGui from module IPython.external.qt_loaders
55650 INFO:   Removing import of PyQt5.QtCore from module IPython.external.qt_loaders
55650 INFO:   Removing import of PyQt5.QtWidgets from module IPython.external.qt_loaders
55650 INFO:   Removing import of PyQt5.QtSvg from module IPython.external.qt_loaders
55650 INFO:   Removing import of PyQt5 from module IPython.external.qt_loaders
55654 INFO: Excluding import 'tkinter'
55662 INFO:   Removing import of tkinter from module IPython.lib.clipboard
55666 INFO: Excluding import 'PyQt4'
55674 INFO:   Removing import of PyQt4 from module IPython.external.qt_loaders
55674 INFO: Loading module hook "hook-jinja2.py"...
55698 INFO: Loading module hook "hook-jsonschema.py"...
55702 INFO: Loading module hook "hook-lib2to3.py"...
55706 INFO: Loading module hook "hook-matplotlib.backends.py"...
56669 INFO:   Matplotlib backend "GTK3Agg": ignored
    cairo backend requires that cairocffi or pycairo is installed
57151 INFO:   Matplotlib backend "GTK3Cairo": ignored
    cairo backend requires that cairocffi or pycairo is installed
57745 INFO:   Matplotlib backend "MacOSX": ignored
    cannot import name '_macosx'
59097 INFO:   Matplotlib backend "nbAgg": added
59750 INFO:   Matplotlib backend "Qt4Agg": added
60217 INFO:   Matplotlib backend "Qt4Cairo": ignored
    cairo backend requires that cairocffi or pycairo is installed
60905 INFO:   Matplotlib backend "Qt5Agg": added
61352 INFO:   Matplotlib backend "Qt5Cairo": ignored
    cairo backend requires that cairocffi or pycairo is installed
61953 INFO:   Matplotlib backend "TkAgg": added
62568 INFO:   Matplotlib backend "TkCairo": ignored
    cairo backend requires that cairocffi or pycairo is installed
63706 INFO:   Matplotlib backend "WebAgg": added
64278 INFO:   Matplotlib backend "WX": ignored
    No module named 'wx'
64719 INFO:   Matplotlib backend "WXAgg": ignored
    No module named 'wx'
65185 INFO:   Matplotlib backend "WXCairo": ignored
    No module named 'wx'
65707 INFO:   Matplotlib backend "agg": added
66231 INFO:   Matplotlib backend "cairo": ignored
    cairo backend requires that cairocffi or pycairo is installed
66883 INFO:   Matplotlib backend "pdf": added
67431 INFO:   Matplotlib backend "pgf": added
67895 INFO:   Matplotlib backend "ps": added
68396 INFO:   Matplotlib backend "svg": added
68953 INFO:   Matplotlib backend "template": added
69570 INFO: Loading module hook "hook-matplotlib.py"...
69973 INFO: Loading module hook "hook-numpy.core.py"...
70079 INFO: MKL libraries found when importing numpy. Adding MKL to binaries
70083 INFO: Loading module hook "hook-numpy.py"...
70087 INFO: Loading module hook "hook-PIL.Image.py"...
70678 INFO: Loading module hook "hook-PIL.py"...
70682 INFO: Excluding import 'PySide'
70686 INFO:   Removing import of PySide from module PIL.ImageQt
70686 INFO: Excluding import 'PyQt5'
70690 INFO: Excluding import 'tkinter'
70694 INFO:   Removing import of tkinter from module PIL.ImageTk
70694 INFO: Excluding import 'PyQt4'
70698 INFO:   Removing import of PyQt4 from module PIL.ImageQt
70698 INFO: Import to be excluded not found: 'FixTk'
70698 INFO: Loading module hook "hook-PIL.SpiderImagePlugin.py"...
70702 INFO: Excluding import 'tkinter'
70706 INFO: Import to be excluded not found: 'FixTk'
70706 INFO: Loading module hook "hook-pkg_resources.py"...
71823 INFO: Processing pre-safe import module hook   win32com
72131 INFO: Loading module hook "hook-pycparser.py"...
72409 INFO: Loading module hook "hook-pydoc.py"...
72409 INFO: Loading module hook "hook-pygments.py"...
74685 INFO: Loading module hook "hook-PyQt5.py"...
74795 WARNING: Cannot read QLibraryInfo output: raised Expecting value: line 1 column 1 (char 0) when decoding:
Traceback (most recent call last):
  File "<string>", line 11, in <module>
ModuleNotFoundError: No module named 'PyQt5.QtCore'
Traceback (most recent call last):
  File "C:\Users\james.richardson\AppData\Local\Continuum\Anaconda3\envs\huffle_test\Scripts\pyinstaller-script.py", line 11, in <module>
    load_entry_point('PyInstaller==3.5.dev0+0d289e49b', 'console_scripts', 'pyinstaller')()
  File "C:\Users\james.richardson\AppData\Local\Continuum\Anaconda3\envs\huffle_test\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Users\james.richardson\AppData\Local\Continuum\Anaconda3\envs\huffle_test\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Users\james.richardson\AppData\Local\Continuum\Anaconda3\envs\huffle_test\lib\site-packages\PyInstaller\building\build_main.py", line 844, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\Users\james.richardson\AppData\Local\Continuum\Anaconda3\envs\huffle_test\lib\site-packages\PyInstaller\building\build_main.py", line 791, in build
    exec(code, spec_namespace)
  File "C:\Users\james.richardson\huffle\GUI\mpltest.spec", line 17, in <module>
    noarchive=False)
  File "C:\Users\james.richardson\AppData\Local\Continuum\Anaconda3\envs\huffle_test\lib\site-packages\PyInstaller\building\build_main.py", line 243, in __init__
    self.__postinit__()
  File "C:\Users\james.richardson\AppData\Local\Continuum\Anaconda3\envs\huffle_test\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
    self.assemble()
  File "C:\Users\james.richardson\AppData\Local\Continuum\Anaconda3\envs\huffle_test\lib\site-packages\PyInstaller\building\build_main.py", line 502, in assemble
    module_hook.post_graph()
  File "C:\Users\james.richardson\AppData\Local\Continuum\Anaconda3\envs\huffle_test\lib\site-packages\PyInstaller\building\imphook.py", line 410, in post_graph
    self._load_hook_module()
  File "C:\Users\james.richardson\AppData\Local\Continuum\Anaconda3\envs\huffle_test\lib\site-packages\PyInstaller\building\imphook.py", line 377, in _load_hook_module
    self.hook_module_name, self.hook_filename)
  File "C:\Users\james.richardson\AppData\Local\Continuum\Anaconda3\envs\huffle_test\lib\site-packages\PyInstaller\compat.py", line 785, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 251, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "C:\Users\james.richardson\AppData\Local\Continuum\Anaconda3\envs\huffle_test\lib\site-packages\PyInstaller\hooks\hook-PyQt5.py", line 23, in <module>
    collect_system_data_files(pyqt5_library_info.location['PrefixPath'],
  File "C:\Users\james.richardson\AppData\Local\Continuum\Anaconda3\envs\huffle_test\lib\site-packages\PyInstaller\utils\hooks\qt.py", line 70, in __getattr__
    qli = json.loads(json_str)
  File "C:\Users\james.richardson\AppData\Local\Continuum\Anaconda3\envs\huffle_test\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\james.richardson\AppData\Local\Continuum\Anaconda3\envs\huffle_test\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\james.richardson\AppData\Local\Continuum\Anaconda3\envs\huffle_test\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by giumas** [comment]
> I can rectify this problem by manually excluding the PyQt5 module

Do you mean by manually editing the `.spec` file to add `PyQt5` to the `exclude` list like in the following snippet?

```
# mpltest.spec
[...]
a = Analysis(['mpl_test.py'],
             pathex=['C:\\code\\test'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=['PyQt5', ],   # <<--- edited
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
[...]
```

**Comment by james0807** [comment]
> > I can rectify this problem by manually excluding the PyQt5 module
> 
> Do you mean by manually editing the `.spec` file to add `PyQt5` to the `exclude` list like in the following snippet?
> 
> ```
> # mpltest.spec
> [...]
> a = Analysis(['mpl_test.py'],
>              pathex=['C:\\code\\test'],
>              binaries=[],
>              datas=[],
>              hiddenimports=[],
>              hookspath=[],
>              runtime_hooks=[],
>              excludes=['PyQt5', ],   # <<--- edited
>              win_no_prefer_redirects=False,
>              win_private_assemblies=False,
>              cipher=block_cipher,
>              noarchive=False)
> [...]
> ```

Yes

**Comment by james0807** [comment]
So do all hooks get called every time you build an app?

I'm unsure why the PyQt5 hook is even detected as necessary for the build?

**Comment by bjones1** [comment]
From what I've heard, the Matplotlib backend is selected at run-time, meaning a compile-time tool like PyInstaller has to include all backends, since it doesn't know which one will be selected.

**Comment by james0807** [comment]
That would explain the issue I suppose, but Qt4Agg is added, despite:

`59750 INFO:   Matplotlib backend "Qt4Agg": added`

and yet PyQt4 hook is not called.

**Comment by bjones1** [comment]
This should be fixed in 9e1f05ba22ee797b6914d85ac11fe9dc425ad649 to avoid throwing an error if PyQt5 can't be imported. Let me know if it doesn't work.

**Comment by expertdicer** [comment]
I'm still getting these errors.

`87757 INFO: Excluding import 'PyQt4'
87764 INFO:   Removing import of PyQt4 from module IPython.external.qt_loaders
87765 INFO: Excluding import 'PySide'
87771 INFO:   Removing import of PySide from module IPython.external.qt_loaders
87772 INFO: Excluding import 'gtk'
87779 INFO: Excluding import 'PyQt5'
87786 INFO:   Removing import of PyQt5 from module IPython.external.qt_loaders
87787 INFO: Excluding import 'tkinter'
87794 INFO:   Removing import of tkinter from module IPython.lib.clipboard
87796 INFO: Excluding import 'matplotlib'
87803 INFO:   Removing import of matplotlib._pylab_helpers from module IPython.core.pylabtools
87803 INFO:   Removing import of matplotlib.backend_bases from module IPython.core.pylabtools
87804 INFO:   Removing import of matplotlib.figure from module IPython.core.pylabtools
87804 INFO:   Removing import of matplotlib.pyplot from module IPython.core.pylabtools
87805 INFO:   Removing import of matplotlib from module IPython.core.pylabtools`

Here is the details https://stackoverflow.com/questions/65146493/pyinstaller-made-an-exe-but-not-working-how-to-fix-these-errors

**Comment by rokm** [comment]
> I'm still getting these errors.
> 
> ```
> 87764 INFO:   Removing import of PyQt4 from module IPython.external.qt_loaders
> 87765 INFO: Excluding import 'PySide'
> 87771 INFO:   Removing import of PySide from module IPython.external.qt_loaders
> 87772 INFO: Excluding import 'gtk'
> 87779 INFO: Excluding import 'PyQt5'
> 87786 INFO:   Removing import of PyQt5 from module IPython.external.qt_loaders
> 87787 INFO: Excluding import 'tkinter'
> 87794 INFO:   Removing import of tkinter from module IPython.lib.clipboard
> 87796 INFO: Excluding import 'matplotlib'
> 87803 INFO:   Removing import of matplotlib._pylab_helpers from module IPython.core.pylabtools
> 87803 INFO:   Removing import of matplotlib.backend_bases from module IPython.core.pylabtools
> 87804 INFO:   Removing import of matplotlib.figure from module IPython.core.pylabtools
> 87804 INFO:   Removing import of matplotlib.pyplot from module IPython.core.pylabtools
> 87805 INFO:   Removing import of matplotlib from module IPython.core.pylabtools```
> ```

None of the above messages are errors.
