### ISSUE TITLE
PyInstaller does not work with PySide2/QtQuick

### ISSUE THREAD

**Issue by Vyeadiai** [pyinstaller/pyinstaller#4177]
I am using PySide2 for QML to Python communication.  All was well until I tried to create an installer using fbs which uses PyInstaller. I am not sure if the problem lies with PySide2 or PyInstaller, hopefully someone here can provide some direction as how I can fix this.

Before anything else I am using 
Python 3.6.x
PyInstaller 3.4
PySide2 5.12

> Ed-MacBook-Air:client ed$ python -V
Python 3.6.8
Ed-MacBook-Air:client ed$ pip freeze
altgraph==0.16.1
boto3==1.9.130
botocore==1.12.130
docutils==0.14
fbs==0.7.4
future==0.17.1
jmespath==0.9.4
macholib==1.11
pefile==2018.8.8
PyInstaller==3.4
Pyro4==4.75
PySide2==5.12.2
python-dateutil==2.8.0
s3transfer==0.2.0
serpent==1.28
shiboken2==5.12.2
sip==4.19.8
six==1.12.0
urllib3==1.24.1
>

I removed my code and created a minimal example with 2 files to prove my point:

main.py

```
from fbs_runtime.application_context import ApplicationContext
from PySide2.QtQml import QQmlApplicationEngine
from PySide2.QtWidgets import QApplication
from PySide2.QtCore import QObject, Signal, Slot
import sys
import os

class AppContext(ApplicationContext):
    def run(self):
        engine = QQmlApplicationEngine()
        chartGenerator = ChartGenerator()
        engine.rootContext().setContextProperty("chartGenerator", chartGenerator)
        engine.load("main.qml")
        root = engine.rootObjects()[0]
        engine.quit.connect(self.app.quit)
        return self.app.exec_()

class ChartGenerator(QObject):
    def __init__(self):
        QObject.__init__(self)

    @Slot(float)
    def do_something(self, my_number):
        print(my_number)

if __name__ == '__main__':
    app = AppContext()
    exit_code = app.run()
    sys.exit(exit_code)
```

and,
main.qml

```
import QtQuick 2.12
import QtQuick.Window 2.12
import QtQuick.Controls 2.12
import QtCharts 2.3

Window {
    id: window
    width: 1000
    height: 1000
    visible: true


    ChartView {
        id: chart
        anchors.fill: parent
        axes: [
            ValueAxis{
                id: xAxis
                min: 0.0
                max: 0.1
                visible: true
                tickCount: 17
            },
            ValueAxis{
                id: yAxis
                min: 0.0
                max: 0.1
                visible: true
                tickCount: 17
            }
        ]
    }
}
```

The output from pyinstaller:

```
Thrive-MacBook-Air:client thrive$ pyinstaller --onefile main.py
256 INFO: PyInstaller: 3.4
256 INFO: Python: 3.6.8
276 INFO: Platform: Darwin-18.5.0-x86_64-i386-64bit
280 INFO: wrote /Users/thrive/python_sandbox/client/main.spec
287 INFO: UPX is not available.
293 INFO: Extending PYTHONPATH with paths
['/Users/thrive/python_sandbox/client', '/Users/thrive/python_sandbox/client']
293 INFO: checking Analysis
375 INFO: Building because /Users/thrive/.pyenv/versions/3.6.8/Python.framework/Versions/3.6/lib/python3.6/site-packages/fbs_runtime/application_context.py changed
375 INFO: Initializing module dependency graph...
379 INFO: Initializing module graph hooks...
386 INFO: Analyzing base_library.zip ...
6389 INFO: running Analysis Analysis-00.toc
6402 INFO: Caching module hooks...
6408 INFO: Analyzing /Users/thrive/python_sandbox/client/main.py
6758 INFO: Loading module hooks...
6758 INFO: Loading module hook "hook-PySide2.QtWidgets.py"...
6760 INFO: Loading module hook "hook-PySide2.QtQml.py"...
6763 INFO: Loading module hook "hook-PySide2.QtGui.py"...
8025 INFO: Loading module hook "hook-PySide2.QtNetwork.py"...
8183 INFO: Loading module hook "hook-encodings.py"...
8258 INFO: Loading module hook "hook-PySide2.QtCore.py"...
8414 INFO: Loading module hook "hook-PySide2.py"...
8417 WARNING: Hidden import "numpy.core.multiarray" not found!
8417 INFO: Loading module hook "hook-xml.py"...
8792 INFO: Loading module hook "hook-pydoc.py"...
8794 INFO: Loading module hook "hook-PySide2.QtQuick.py"...
9121 INFO: Looking for ctypes DLLs
9121 INFO: Analyzing run-time hooks ...
9124 INFO: Including run-time hook 'pyi_rth_qt5plugins.py'
9128 INFO: Including run-time hook 'pyi_rth_qml.py'
9136 INFO: Looking for dynamic libraries
10402 ERROR: Can not find path ./libshiboken2.abi3.5.12.dylib (needed by /Users/thrive/.pyenv/versions/3.6.8/Python.framework/Versions/3.6/lib/python3.6/site-packages/PySide2/QtCore.abi3.so)
10409 ERROR: Can not find path ./libshiboken2.abi3.5.12.dylib (needed by /Users/thrive/.pyenv/versions/3.6.8/Python.framework/Versions/3.6/lib/python3.6/site-packages/PySide2/QtNetwork.abi3.so)
10432 ERROR: Can not find path ./libshiboken2.abi3.5.12.dylib (needed by /Users/thrive/.pyenv/versions/3.6.8/Python.framework/Versions/3.6/lib/python3.6/site-packages/PySide2/QtWidgets.abi3.so)
10454 ERROR: Can not find path ./libshiboken2.abi3.5.12.dylib (needed by /Users/thrive/.pyenv/versions/3.6.8/Python.framework/Versions/3.6/lib/python3.6/site-packages/PySide2/QtGui.abi3.so)
10465 ERROR: Can not find path ./libshiboken2.abi3.5.12.dylib (needed by /Users/thrive/.pyenv/versions/3.6.8/Python.framework/Versions/3.6/lib/python3.6/site-packages/PySide2/QtQml.abi3.so)
10481 ERROR: Can not find path ./libshiboken2.abi3.5.12.dylib (needed by /Users/thrive/.pyenv/versions/3.6.8/Python.framework/Versions/3.6/lib/python3.6/site-packages/PySide2/QtQuick.abi3.so)
11020 ERROR: Can not find path ./libshiboken2.abi3.5.12.dylib (needed by /Users/thrive/.pyenv/versions/3.6.8/Python.framework/Versions/3.6/lib/python3.6/site-packages/PySide2/libpyside2.abi3.5.12.dylib)
...
```

and the exe fails to run:

```
Thrive-MacBook-Air:client thrive$ dist/main
Problem importing shibokensupport:
No module named 'typing'
Traceback (most recent call last):
  File "site-packages/PyInstaller/loader/rthooks/pyi_rth_qt5plugins.py", line 47, in <module>
ModuleNotFoundError: No module named 'PyQt5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "(builtin)", line 93, in ensure_shibokensupport
  File "(builtin)", line 133, in bootstrap
  File "/var/folders/83/1f9vq04x4236n32js121b3yh0000gp/T/embedded.m0fc4yls.zip/shibokensupport/signature/loader.py", line 156, in <module>
    import typing
ModuleNotFoundError: No module named 'typing'
sys.path:
  /var/folders/83/1f9vq04x4236n32js121b3yh0000gp/T/embedded.m0fc4yls.zip
  /var/folders/83/1f9vq04x4236n32js121b3yh0000gp/T/_MEInejJd8/base_library.zip
  /var/folders/83/1f9vq04x4236n32js121b3yh0000gp/T/_MEInejJd8
Traceback (most recent call last):
  File "site-packages/PyInstaller/loader/rthooks/pyi_rth_qt5plugins.py", line 47, in <module>
ModuleNotFoundError: No module named 'PyQt5'

During handling of the above exception, another exception occurred:
...
...
```
Can anyone help? I believe PySide2 is not fully supported how do I make a hook for this I am new to PyInstaller and have no idea what a hook is in the first place. Thank you

**Comment by Vyeadiai** [comment]
Could someone point me in the right direction as to how to fix this? @patrickelectric @bjones1 ?

This issue is somehow related to these issues
[https://github.com/pyinstaller/pyinstaller/issues/3689](https://github.com/pyinstaller/pyinstaller/issues/3689)

and this issue that was resolved with PyQt5 but not PySide2
[https://github.com/pyinstaller/pyinstaller/issues/3711](https://github.com/pyinstaller/pyinstaller/issues/3711)
and
[https://github.com/pyinstaller/pyinstaller/pull/3693](https://github.com/pyinstaller/pyinstaller/pull/3693)


Thank you

**Comment by bjones1** [comment]
Update the PySide2 hooks to follow the structure of the PyQt5 hooks. You can probably eliminate most of the real-time hooks (same as PyQt5).

**Comment by Vyeadiai** [comment]
@bjones1  I have tried for days trying to fix this issue. I tried following the PyQt5 structure as you suggested to no avail. 

Our company is in desperate need of creating an installer for our PySide2/QML app. Can we please pay you for you to help us fix this for us and the PyInstaller project? We will pay in advance of your help, as stated we REALLY need this installer to deploy on our customers machines and we have no one in house for this. 

Please let me know as soon as possible, you can contact me at edwin.fernandez@thrivebio.com or I will be watching this thread. Thank you.

**Comment by giumas** [comment]
@Vyeadiai Why don't you just add `"typing"` in the `hiddenimports` list of the generated `main.spec`? 
Then you just re-run the freezing process with `pyinstaller --clean -y main.spec`.

It worked for me.

**Comment by giumas** [comment]
@Vyeadiai I have never used `QtCharts`, but I would try to add it as `hiddenimports`. 

If this does not work, you can try the solution that I have adopted here as the last resource (i.e., copy the full `PySide2` folder!): https://github.com/hydroffice/hyo2_soundspeed/blob/master/freeze/SoundSpeedManager.1folder.spec#L101

**Comment by bjones1** [comment]
This was fixed in 5b5791285332003940f4bc70c32bb0cf10a32917. Please reopen if there are still problems.

**Comment by sebolio** [comment]
It still doesn't work for me. I keep getting:
```
Traceback (most recent call last):
  File "main.py", line 6, in <module>
ModuleNotFoundError: No module named 'PySide2'
[4921] Failed to execute script main
```
Using macOS 10.15.4 with Python 3.7.7 installed via `brew`

**Comment by Merkwurdichliebe** [comment]
I am getting this error as well. Downgraded to Python 3.7.6 in my virtual environment as suggested [here](http://pyinstaller.47505.x6.nabble.com/Help-needed-Error-loading-Python-lib-td2872.html) after getting a dlopen error. Now I don't get the error but after freezing I get the same traceback as @tr4g above (no module named 'PySide2'). Any news on that?

macOS 10.15.6 with Python 3.7.6 installed with the python.org Mac installer.

Thanks.
