### ISSUE TITLE
Program fails at `pyiboot01_bootstrap` when using `--noconsole`

### ISSUE THREAD

**Issue by cdgriffith** [pyinstaller/pyinstaller#4213]
Python 3.6.8
Windows 10 Build 17763
Pyinstaller 3.4 /  3.5.dev0+06f7da789

I am having an odd issue where my executable is working just fine as long as there is a console enabled, but fails at `pyiboot01_bootstrap` when there is not a console (which also really limits the amount of debug output I can gather.) 

![why](https://user-images.githubusercontent.com/3275435/57187713-d2221e80-6eb8-11e9-8de9-bba976c99289.PNG)

I have tried running the `sxstrace` as well, but it leaves an empty `trace.txt` file. 
Works the same in `--onedir` and `--onefile`. 

As I am unsure of the root cause I am sorry I do not know how to limit the scope for a better example. 

The code I am using is located https://github.com/cdgriffith/FastFlix/tree/44636c97036a5cd2d2ec05ce64b8a11f99e388c3

One time prep: 
```
git clone -b fast-flix --single-branch https://github.com/cdgriffith/binary-files.git
C:\Python36-x64\python -m pip install --upgrade pip setuptools --ignore-installed
C:\Python36-x64\python -m pip install -r requirements.txt
pushd flix && ..\binary-files\executables\windows\7-zip\1900\x64\7za.exe a "..\plugins.7z" "plugins" && popd
```

Build command for noconsole (broken version)
```
C:\Python36-x64\Scripts\pyinstaller --add-data "bundled;." --add-data "plugins.7z;extra" --add-data "data\rotations\*;data\rotations" --add-data "data\icon.ico;data" --add-data "binary-files\executables\windows\svt-av1\svt-1.0.549.7z;extra" --add-data "docs\build-licenses.txt;docs" --add-data "binary-files\executables\windows\7-zip\1900\x64\*;extra" --add-data "binary-files\executables\windows\ffmpeg\lgpl\N-93214-g7e4d3dbe18\x86_64\ffmpeg_lgpl.7z;extra" --paths "C:\Python36-x64\Lib\site-packages\shiboken2" flix\gui.py  --icon "data\icon.ico" --name FastFlix --clean --onedir --noconsole --debug all
```

Working command with console
```
C:\Python36-x64\Scripts\pyinstaller --add-data "bundled;." --add-data "plugins.7z;extra" --add-data "data\rotations\*;data\rotations" --add-data "data\icon.ico;data" --add-data "binary-files\executables\windows\svt-av1\svt-1.0.549.7z;extra" --add-data "docs\build-licenses.txt;docs" --add-data "binary-files\executables\windows\7-zip\1900\x64\*;extra" --add-data "binary-files\executables\windows\ffmpeg\lgpl\N-93214-g7e4d3dbe18\x86_64\ffmpeg_lgpl.7z;extra" --paths "C:\Python36-x64\Lib\site-packages\shiboken2" flix\gui.py  --icon "data\icon.ico" --name FastFlix --clean --onedir --debug all
```

(Please note that even though it is not a venv this python version is specifically for building this project and keeping it the same as used on Appveyor, where the problem also occurs.) 

<details>
<summary>Build output:</summary>

```
C:\Python36-x64\Scripts\pyinstaller --add-data "bundled;." --add-data "plugins.7z;extra" --add-data "data\rotations\*;data\rotations" --add-data "data\icon.ico;data" --add-data "binary-files\executables\windows\svt-av1\svt-1.0.549.7z;extra" --add-data "docs\build-licenses.txt;docs" --add-data "binary-files\executables\windows\7-zip\1900\x64\*;extra" --add-data "binary-files\executables\windows\ffmpeg\lgpl\N-93214-g7e4d3dbe18\x86_64\ffmpeg_lgpl.7z;extra" --paths "C:\Python36-x64\Lib\site-packages\shiboken2" flix\gui.py  --icon "data\icon.ico" --name FastFlix --clean --onedir --noconsole --debug all --log-level DEBUG
157 INFO: PyInstaller: 3.5.dev0+06f7da789
158 INFO: Python: 3.6.8
159 INFO: Platform: Windows-10-10.0.17763-SP0
161 INFO: wrote C:\Users\teckc\PycharmProjects\FastFlix\FastFlix.spec
162 DEBUG: Testing for UPX ...
168 INFO: UPX is not available.
169 INFO: Removing temporary files and cleaning cache in C:\Users\teckc\AppData\Roaming\pyinstaller
284 DEBUG: script: C:\Users\teckc\PycharmProjects\FastFlix\flix\gui.py
285 INFO: Extending PYTHONPATH with paths
['C:\\Users\\teckc\\PycharmProjects\\FastFlix',
 'C:\\Python36-x64\\Lib\\site-packages\\shiboken2',
 'C:\\Users\\teckc\\PycharmProjects\\FastFlix']
286 INFO: checking Analysis
286 INFO: Building Analysis because Analysis-00.toc is non existent
288 INFO: Initializing module dependency graph...
291 INFO: Initializing module graph hooks...
293 INFO: Analyzing base_library.zip ...
293 DEBUG: Collecting submodules for encodings
415 DEBUG: collect_submodules - Found submodules: {'encodings.cp500', 'encodings.iso2022_kr', 'encodings.cp858', 'encodings.utf_16_be', 'encodings.cp1252', 'encodings.base64_codec', 'en
codings.koi8_u', 'encodings.shift_jis', 'encodings.cp65001', 'encodings.koi8_t', 'encodings.iso2022_jp_1', 'encodings.utf_32_be', 'encodings.utf_7', 'encodings.iso8859_5', 'encodings.un
icode_internal', 'encodings.utf_16_le', 'encodings.mac_turkish', 'encodings.utf_32_le', 'encodings.cp865', 'encodings.iso8859_16', 'encodings.mac_cyrillic', 'encodings.cp856', 'encoding
s.cp1257', 'encodings.iso8859_9', 'encodings.cp855', 'encodings.cp1026', 'encodings.iso8859_13', 'encodings.aliases', 'encodings.cp869', 'encodings.iso8859_1', 'encodings.iso8859_14', '
encodings.cp037', 'encodings.cp1258', 'encodings.mac_farsi', 'encodings.mac_romanian', 'encodings.euc_jisx0213', 'encodings.gb18030', 'encodings.big5hkscs', 'encodings.iso8859_2', 'enco
dings.mac_roman', 'encodings.oem', 'encodings.iso8859_11', 'encodings.quopri_codec', 'encodings.utf_16', 'encodings.big5', 'encodings.cp852', 'encodings.utf_8_sig', 'encodings.cp874', '
encodings.mac_arabic', 'encodings.cp775', 'encodings.iso8859_4', 'encodings.mac_centeuro', 'encodings.uu_codec', 'encodings.cp1251', 'encodings.cp857', 'encodings.cp875', 'encodings.cp9
32', 'encodings.punycode', 'encodings.utf_32', 'encodings.shift_jis_2004', 'encodings.ascii', 'encodings.johab', 'encodings.cp424', 'encodings.iso2022_jp_ext', 'encodings.cp1006', 'enco
dings.iso8859_3', 'encodings.iso2022_jp_3', 'encodings.cp1140', 'encodings.palmos', 'encodings.cp1254', 'encodings.cp862', 'encodings.cp1125', 'encodings.cp437', 'encodings.hz', 'encodi
ngs.hex_codec', 'encodings', 'encodings.iso8859_8', 'encodings.cp850', 'encodings.mac_iceland', 'encodings.tis_620', 'encodings.iso2022_jp_2004', 'encodings.cp1253', 'encodings.mbcs', '
encodings.mac_croatian', 'encodings.gbk', 'encodings.iso8859_10', 'encodings.kz1048', 'encodings.ptcp154', 'encodings.euc_kr', 'encodings.shift_jisx0213', 'encodings.undefined', 'encodi
ngs.iso2022_jp_2', 'encodings.cp1255', 'encodings.idna', 'encodings.raw_unicode_escape', 'encodings.latin_1', 'encodings.iso8859_15', 'encodings.unicode_escape', 'encodings.mac_greek',
'encodings.rot_13', 'encodings.cp949', 'encodings.cp860', 'encodings.koi8_r', 'encodings.cp866', 'encodings.hp_roman8', 'encodings.gb2312', 'encodings.cp737', 'encodings.charmap', 'enco
dings.mac_latin2', 'encodings.utf_8', 'encodings.cp720', 'encodings.cp861', 'encodings.iso8859_7', 'encodings.cp863', 'encodings.euc_jis_2004', 'encodings.cp864', 'encodings.euc_jp', 'e
ncodings.cp950', 'encodings.cp1250', 'encodings.cp273', 'encodings.cp1256', 'encodings.zlib_codec', 'encodings.bz2_codec', 'encodings.iso2022_jp', 'encodings.iso8859_6'}
420 DEBUG: Collecting submodules for collections
518 DEBUG: collect_submodules - Found submodules: {'collections', 'collections.abc'}
4307 DEBUG: Adding python files to base_library.zip
4346 DEBUG: Hidden import: codecs
4347 DEBUG: Hidden import 'codecs' already found
4347 INFO: running Analysis Analysis-00.toc
4347 DEBUG: Analyzing c:\python36-x64\python.exe
4354 DEBUG: Dependent assemblies of c:\python36-x64\python.exe:
4354 DEBUG: *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
4355 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\python36-x64\python.exe
4356 DEBUG: Skipping assembly *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
4368 DEBUG: Adding api-ms-win-crt-runtime-l1-1-0.dll dependency of python.exe from C:\ProgramData\Anaconda3\api-ms-win-crt-runtime-l1-1-0.dll
4370 DEBUG: Adding api-ms-win-crt-locale-l1-1-0.dll dependency of python.exe from C:\ProgramData\Anaconda3\api-ms-win-crt-locale-l1-1-0.dll
4377 DEBUG: Adding python36.dll dependency of python.exe from c:\python36-x64\python36.dll
4380 DEBUG: Adding VCRUNTIME140.dll dependency of python.exe from c:\python36-x64\VCRUNTIME140.dll
4384 DEBUG: Skipping KERNEL32.dll dependency of python.exe
4396 DEBUG: Adding api-ms-win-crt-math-l1-1-0.dll dependency of python.exe from C:\ProgramData\Anaconda3\api-ms-win-crt-math-l1-1-0.dll
4401 DEBUG: Adding api-ms-win-crt-stdio-l1-1-0.dll dependency of python.exe from C:\ProgramData\Anaconda3\api-ms-win-crt-stdio-l1-1-0.dll
4405 DEBUG: Adding api-ms-win-crt-heap-l1-1-0.dll dependency of python.exe from C:\ProgramData\Anaconda3\api-ms-win-crt-heap-l1-1-0.dll
4406 DEBUG: Analyzing C:\ProgramData\Anaconda3\api-ms-win-crt-runtime-l1-1-0.dll
4420 DEBUG: Adding ucrtbase.dll dependency of api-ms-win-crt-runtime-l1-1-0.dll from C:\ProgramData\Anaconda3\ucrtbase.dll
4421 DEBUG: Analyzing C:\ProgramData\Anaconda3\api-ms-win-crt-locale-l1-1-0.dll
4432 DEBUG: Analyzing c:\python36-x64\python36.dll
4433 DEBUG: Dependent assemblies of c:\python36-x64\python36.dll:
4434 DEBUG: *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
4435 DEBUG: Skipping assembly *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
4466 DEBUG: Adding api-ms-win-crt-environment-l1-1-0.dll dependency of python36.dll from C:\ProgramData\Anaconda3\api-ms-win-crt-environment-l1-1-0.dll
4470 DEBUG: Skipping KERNEL32.dll dependency of python36.dll
4473 DEBUG: Skipping SHLWAPI.dll dependency of python36.dll
4483 DEBUG: Adding api-ms-win-crt-time-l1-1-0.dll dependency of python36.dll from C:\ProgramData\Anaconda3\api-ms-win-crt-time-l1-1-0.dll
4489 DEBUG: Adding api-ms-win-crt-convert-l1-1-0.dll dependency of python36.dll from C:\ProgramData\Anaconda3\api-ms-win-crt-convert-l1-1-0.dll
4495 DEBUG: Adding api-ms-win-crt-process-l1-1-0.dll dependency of python36.dll from C:\ProgramData\Anaconda3\api-ms-win-crt-process-l1-1-0.dll
4498 DEBUG: Adding api-ms-win-crt-filesystem-l1-1-0.dll dependency of python36.dll from C:\ProgramData\Anaconda3\api-ms-win-crt-filesystem-l1-1-0.dll
4502 DEBUG: Adding api-ms-win-crt-conio-l1-1-0.dll dependency of python36.dll from C:\ProgramData\Anaconda3\api-ms-win-crt-conio-l1-1-0.dll
4507 DEBUG: Skipping WS2_32.dll dependency of python36.dll
4513 DEBUG: Adding api-ms-win-crt-string-l1-1-0.dll dependency of python36.dll from C:\ProgramData\Anaconda3\api-ms-win-crt-string-l1-1-0.dll
4518 DEBUG: Skipping ADVAPI32.dll dependency of python36.dll
4523 DEBUG: Skipping VERSION.dll dependency of python36.dll
4524 DEBUG: Analyzing c:\python36-x64\VCRUNTIME140.dll
4535 DEBUG: Skipping KERNEL32.dll dependency of VCRUNTIME140.dll
4547 DEBUG: Analyzing C:\ProgramData\Anaconda3\api-ms-win-crt-math-l1-1-0.dll
4564 DEBUG: Analyzing C:\ProgramData\Anaconda3\api-ms-win-crt-stdio-l1-1-0.dll
4580 DEBUG: Analyzing C:\ProgramData\Anaconda3\api-ms-win-crt-heap-l1-1-0.dll
4585 DEBUG: Analyzing C:\ProgramData\Anaconda3\ucrtbase.dll
4641 DEBUG: Adding api-ms-win-core-processthreads-l1-1-0.dll dependency of ucrtbase.dll from C:\ProgramData\Anaconda3\api-ms-win-core-processthreads-l1-1-0.dll
4646 DEBUG: Adding api-ms-win-core-localization-l1-2-0.dll dependency of ucrtbase.dll from C:\ProgramData\Anaconda3\api-ms-win-core-localization-l1-2-0.dll
4649 DEBUG: Adding api-ms-win-core-sysinfo-l1-1-0.dll dependency of ucrtbase.dll from C:\ProgramData\Anaconda3\api-ms-win-core-sysinfo-l1-1-0.dll
4652 DEBUG: Adding api-ms-win-core-memory-l1-1-0.dll dependency of ucrtbase.dll from C:\ProgramData\Anaconda3\api-ms-win-core-memory-l1-1-0.dll
4656 DEBUG: Adding api-ms-win-core-synch-l1-1-0.dll dependency of ucrtbase.dll from C:\ProgramData\Anaconda3\api-ms-win-core-synch-l1-1-0.dll
4659 DEBUG: Adding api-ms-win-core-util-l1-1-0.dll dependency of ucrtbase.dll from C:\ProgramData\Anaconda3\api-ms-win-core-util-l1-1-0.dll
4662 DEBUG: Adding api-ms-win-core-console-l1-1-0.dll dependency of ucrtbase.dll from C:\ProgramData\Anaconda3\api-ms-win-core-console-l1-1-0.dll
4666 DEBUG: Adding api-ms-win-core-timezone-l1-1-0.dll dependency of ucrtbase.dll from C:\ProgramData\Anaconda3\api-ms-win-core-timezone-l1-1-0.dll
4669 DEBUG: Adding api-ms-win-core-processenvironment-l1-1-0.dll dependency of ucrtbase.dll from C:\ProgramData\Anaconda3\api-ms-win-core-processenvironment-l1-1-0.dll
4680 DEBUG: Adding api-ms-win-core-processthreads-l1-1-1.dll dependency of ucrtbase.dll from C:\ProgramData\Anaconda3\api-ms-win-core-processthreads-l1-1-1.dll
4684 DEBUG: Adding api-ms-win-core-datetime-l1-1-0.dll dependency of ucrtbase.dll from C:\ProgramData\Anaconda3\api-ms-win-core-datetime-l1-1-0.dll
4688 DEBUG: Adding api-ms-win-core-handle-l1-1-0.dll dependency of ucrtbase.dll from C:\ProgramData\Anaconda3\api-ms-win-core-handle-l1-1-0.dll
4695 DEBUG: Adding api-ms-win-core-rtlsupport-l1-1-0.dll dependency of ucrtbase.dll from C:\ProgramData\Anaconda3\api-ms-win-core-rtlsupport-l1-1-0.dll
4697 DEBUG: Adding api-ms-win-core-namedpipe-l1-1-0.dll dependency of ucrtbase.dll from C:\ProgramData\Anaconda3\api-ms-win-core-namedpipe-l1-1-0.dll
4700 DEBUG: Adding api-ms-win-core-libraryloader-l1-1-0.dll dependency of ucrtbase.dll from C:\ProgramData\Anaconda3\api-ms-win-core-libraryloader-l1-1-0.dll
4703 DEBUG: Adding api-ms-win-core-heap-l1-1-0.dll dependency of ucrtbase.dll from C:\ProgramData\Anaconda3\api-ms-win-core-heap-l1-1-0.dll
4711 DEBUG: Adding api-ms-win-core-errorhandling-l1-1-0.dll dependency of ucrtbase.dll from C:\ProgramData\Anaconda3\api-ms-win-core-errorhandling-l1-1-0.dll
4714 DEBUG: Adding api-ms-win-core-interlocked-l1-1-0.dll dependency of ucrtbase.dll from C:\ProgramData\Anaconda3\api-ms-win-core-interlocked-l1-1-0.dll
4718 DEBUG: Adding api-ms-win-core-profile-l1-1-0.dll dependency of ucrtbase.dll from C:\ProgramData\Anaconda3\api-ms-win-core-profile-l1-1-0.dll
4727 DEBUG: Adding api-ms-win-core-string-l1-1-0.dll dependency of ucrtbase.dll from C:\ProgramData\Anaconda3\api-ms-win-core-string-l1-1-0.dll
4730 DEBUG: Adding api-ms-win-core-debug-l1-1-0.dll dependency of ucrtbase.dll from C:\ProgramData\Anaconda3\api-ms-win-core-debug-l1-1-0.dll
4732 DEBUG: Adding api-ms-win-core-file-l1-2-0.dll dependency of ucrtbase.dll from C:\ProgramData\Anaconda3\api-ms-win-core-file-l1-2-0.dll
4735 DEBUG: Adding api-ms-win-core-synch-l1-2-0.dll dependency of ucrtbase.dll from C:\ProgramData\Anaconda3\api-ms-win-core-synch-l1-2-0.dll
4741 DEBUG: Adding api-ms-win-core-file-l1-1-0.dll dependency of ucrtbase.dll from C:\ProgramData\Anaconda3\api-ms-win-core-file-l1-1-0.dll
4745 DEBUG: Adding api-ms-win-core-file-l2-1-0.dll dependency of ucrtbase.dll from C:\ProgramData\Anaconda3\api-ms-win-core-file-l2-1-0.dll
4745 DEBUG: Analyzing C:\ProgramData\Anaconda3\api-ms-win-crt-environment-l1-1-0.dll
4748 DEBUG: Analyzing C:\ProgramData\Anaconda3\api-ms-win-crt-time-l1-1-0.dll
4752 DEBUG: Analyzing C:\ProgramData\Anaconda3\api-ms-win-crt-convert-l1-1-0.dll
4762 DEBUG: Analyzing C:\ProgramData\Anaconda3\api-ms-win-crt-process-l1-1-0.dll
4768 DEBUG: Analyzing C:\ProgramData\Anaconda3\api-ms-win-crt-filesystem-l1-1-0.dll
4778 DEBUG: Analyzing C:\ProgramData\Anaconda3\api-ms-win-crt-conio-l1-1-0.dll
4784 DEBUG: Analyzing C:\ProgramData\Anaconda3\api-ms-win-crt-string-l1-1-0.dll
4799 DEBUG: Analyzing C:\ProgramData\Anaconda3\api-ms-win-core-processthreads-l1-1-0.dll
4813 DEBUG: Skipping kernel32.dll dependency of api-ms-win-core-processthreads-l1-1-0.dll
4821 DEBUG: Skipping advapi32.dll dependency of api-ms-win-core-processthreads-l1-1-0.dll
4821 DEBUG: Analyzing C:\ProgramData\Anaconda3\api-ms-win-core-localization-l1-2-0.dll
4833 DEBUG: Skipping kernel32.dll dependency of api-ms-win-core-localization-l1-2-0.dll
4833 DEBUG: Analyzing C:\ProgramData\Anaconda3\api-ms-win-core-sysinfo-l1-1-0.dll
4839 DEBUG: Skipping kernel32.dll dependency of api-ms-win-core-sysinfo-l1-1-0.dll
4839 DEBUG: Analyzing C:\ProgramData\Anaconda3\api-ms-win-core-memory-l1-1-0.dll
4846 DEBUG: Skipping kernel32.dll dependency of api-ms-win-core-memory-l1-1-0.dll
4847 DEBUG: Analyzing C:\ProgramData\Anaconda3\api-ms-win-core-synch-l1-1-0.dll
4858 DEBUG: Skipping kernel32.dll dependency of api-ms-win-core-synch-l1-1-0.dll
4859 DEBUG: Analyzing C:\ProgramData\Anaconda3\api-ms-win-core-util-l1-1-0.dll
4864 DEBUG: Skipping kernel32.dll dependency of api-ms-win-core-util-l1-1-0.dll
4865 DEBUG: Analyzing C:\ProgramData\Anaconda3\api-ms-win-core-console-l1-1-0.dll
4873 DEBUG: Skipping kernel32.dll dependency of api-ms-win-core-console-l1-1-0.dll
4873 DEBUG: Analyzing C:\ProgramData\Anaconda3\api-ms-win-core-timezone-l1-1-0.dll
4881 DEBUG: Skipping kernel32.dll dependency of api-ms-win-core-timezone-l1-1-0.dll
4881 DEBUG: Analyzing C:\ProgramData\Anaconda3\api-ms-win-core-processenvironment-l1-1-0.dll
4887 DEBUG: Skipping kernel32.dll dependency of api-ms-win-core-processenvironment-l1-1-0.dll
4888 DEBUG: Analyzing C:\ProgramData\Anaconda3\api-ms-win-core-processthreads-l1-1-1.dll
4897 DEBUG: Skipping kernel32.dll dependency of api-ms-win-core-processthreads-l1-1-1.dll
4897 DEBUG: Analyzing C:\ProgramData\Anaconda3\api-ms-win-core-datetime-l1-1-0.dll
4904 DEBUG: Skipping kernel32.dll dependency of api-ms-win-core-datetime-l1-1-0.dll
4904 DEBUG: Analyzing C:\ProgramData\Anaconda3\api-ms-win-core-handle-l1-1-0.dll
4912 DEBUG: Skipping kernel32.dll dependency of api-ms-win-core-handle-l1-1-0.dll
4912 DEBUG: Analyzing C:\ProgramData\Anaconda3\api-ms-win-core-rtlsupport-l1-1-0.dll
4932 DEBUG: Skipping ntdll.dll dependency of api-ms-win-core-rtlsupport-l1-1-0.dll
4932 DEBUG: Analyzing C:\ProgramData\Anaconda3\api-ms-win-core-namedpipe-l1-1-0.dll
4940 DEBUG: Skipping kernel32.dll dependency of api-ms-win-core-namedpipe-l1-1-0.dll
4945 DEBUG: Skipping advapi32.dll dependency of api-ms-win-core-namedpipe-l1-1-0.dll
4945 DEBUG: Analyzing C:\ProgramData\Anaconda3\api-ms-win-core-libraryloader-l1-1-0.dll
4950 DEBUG: Skipping kernel32.dll dependency of api-ms-win-core-libraryloader-l1-1-0.dll
4951 DEBUG: Analyzing C:\ProgramData\Anaconda3\api-ms-win-core-heap-l1-1-0.dll
4961 DEBUG: Skipping kernel32.dll dependency of api-ms-win-core-heap-l1-1-0.dll
4962 DEBUG: Analyzing C:\ProgramData\Anaconda3\api-ms-win-core-errorhandling-l1-1-0.dll
4970 DEBUG: Skipping kernel32.dll dependency of api-ms-win-core-errorhandling-l1-1-0.dll
4970 DEBUG: Analyzing C:\ProgramData\Anaconda3\api-ms-win-core-interlocked-l1-1-0.dll
4978 DEBUG: Skipping kernel32.dll dependency of api-ms-win-core-interlocked-l1-1-0.dll
4978 DEBUG: Analyzing C:\ProgramData\Anaconda3\api-ms-win-core-profile-l1-1-0.dll
4983 DEBUG: Skipping kernel32.dll dependency of api-ms-win-core-profile-l1-1-0.dll
4983 DEBUG: Analyzing C:\ProgramData\Anaconda3\api-ms-win-core-string-l1-1-0.dll
4989 DEBUG: Skipping kernel32.dll dependency of api-ms-win-core-string-l1-1-0.dll
4989 DEBUG: Analyzing C:\ProgramData\Anaconda3\api-ms-win-core-debug-l1-1-0.dll
4997 DEBUG: Skipping kernel32.dll dependency of api-ms-win-core-debug-l1-1-0.dll
4997 DEBUG: Analyzing C:\ProgramData\Anaconda3\api-ms-win-core-file-l1-2-0.dll
5005 DEBUG: Skipping kernel32.dll dependency of api-ms-win-core-file-l1-2-0.dll
5005 DEBUG: Analyzing C:\ProgramData\Anaconda3\api-ms-win-core-synch-l1-2-0.dll
5013 DEBUG: Skipping kernel32.dll dependency of api-ms-win-core-synch-l1-2-0.dll
5013 DEBUG: Analyzing C:\ProgramData\Anaconda3\api-ms-win-core-file-l1-1-0.dll
5022 DEBUG: Skipping kernel32.dll dependency of api-ms-win-core-file-l1-1-0.dll
5023 DEBUG: Analyzing C:\ProgramData\Anaconda3\api-ms-win-core-file-l2-1-0.dll
5032 DEBUG: Skipping kernel32.dll dependency of api-ms-win-core-file-l2-1-0.dll
5034 INFO: Caching module hooks...
5083 INFO: Analyzing C:\Users\teckc\PycharmProjects\FastFlix\flix\gui.py
5488 INFO: Processing pre-safe import module hook   win32com
5490 DEBUG: win32com: extending __path__ with dir 'c:\\python36-x64\\lib\\site-packages\\win32comext'
5527 INFO: Processing pre-find module path hook   distutils
7375 INFO: Loading module hooks...
7376 INFO: Loading module hook "hook-appdirs.py"...
7378 INFO: Excluding import 'win32com'
7379 INFO:   Removing import of win32com.shell.shellcon from module appdirs
7379 INFO:   Removing import of win32com.shell from module appdirs
7379 INFO:   Removing import of win32com.shell.shell from module appdirs
7380 INFO: Loading module hook "hook-distutils.py"...
7383 INFO: Loading module hook "hook-encodings.py"...
7384 DEBUG: Collecting submodules for encodings
7491 DEBUG: collect_submodules - Found submodules: {'encodings.cp500', 'encodings.iso2022_kr', 'encodings.cp858', 'encodings.utf_16_be', 'encodings.cp1252', 'encodings.base64_codec', 'e
ncodings.koi8_u', 'encodings.shift_jis', 'encodings.cp65001', 'encodings.koi8_t', 'encodings.iso2022_jp_1', 'encodings.utf_32_be', 'encodings.utf_7', 'encodings.iso8859_5', 'encodings.u
nicode_internal', 'encodings.utf_16_le', 'encodings.mac_turkish', 'encodings.utf_32_le', 'encodings.cp865', 'encodings.iso8859_16', 'encodings.mac_cyrillic', 'encodings.cp856', 'encodin
gs.cp1257', 'encodings.iso8859_9', 'encodings.cp855', 'encodings.cp1026', 'encodings.iso8859_13', 'encodings.aliases', 'encodings.cp869', 'encodings.iso8859_1', 'encodings.iso8859_14',
'encodings.cp037', 'encodings.cp1258', 'encodings.mac_farsi', 'encodings.mac_romanian', 'encodings.euc_jisx0213', 'encodings.gb18030', 'encodings.big5hkscs', 'encodings.iso8859_2', 'enc
odings.mac_roman', 'encodings.oem', 'encodings.iso8859_11', 'encodings.quopri_codec', 'encodings.utf_16', 'encodings.big5', 'encodings.cp852', 'encodings.utf_8_sig', 'encodings.cp874',
'encodings.mac_arabic', 'encodings.cp775', 'encodings.iso8859_4', 'encodings.mac_centeuro', 'encodings.uu_codec', 'encodings.cp1251', 'encodings.cp857', 'encodings.cp875', 'encodings.cp
932', 'encodings.punycode', 'encodings.utf_32', 'encodings.shift_jis_2004', 'encodings.ascii', 'encodings.johab', 'encodings.cp424', 'encodings.iso2022_jp_ext', 'encodings.cp1006', 'enc
odings.iso8859_3', 'encodings.iso2022_jp_3', 'encodings.cp1140', 'encodings.palmos', 'encodings.cp1254', 'encodings.cp862', 'encodings.cp1125', 'encodings.cp437', 'encodings.hz', 'encod
ings.hex_codec', 'encodings', 'encodings.iso8859_8', 'encodings.cp850', 'encodings.mac_iceland', 'encodings.tis_620', 'encodings.iso2022_jp_2004', 'encodings.cp1253', 'encodings.mbcs',
'encodings.mac_croatian', 'encodings.gbk', 'encodings.iso8859_10', 'encodings.kz1048', 'encodings.ptcp154', 'encodings.euc_kr', 'encodings.shift_jisx0213', 'encodings.undefined', 'encod
ings.iso2022_jp_2', 'encodings.cp1255', 'encodings.idna', 'encodings.raw_unicode_escape', 'encodings.latin_1', 'encodings.iso8859_15', 'encodings.unicode_escape', 'encodings.mac_greek',
 'encodings.rot_13', 'encodings.cp949', 'encodings.cp860', 'encodings.koi8_r', 'encodings.cp866', 'encodings.hp_roman8', 'encodings.gb2312', 'encodings.cp737', 'encodings.charmap', 'enc
odings.mac_latin2', 'encodings.utf_8', 'encodings.cp720', 'encodings.cp861', 'encodings.iso8859_7', 'encodings.cp863', 'encodings.euc_jis_2004', 'encodings.cp864', 'encodings.euc_jp', '
encodings.cp950', 'encodings.cp1250', 'encodings.cp273', 'encodings.cp1256', 'encodings.zlib_codec', 'encodings.bz2_codec', 'encodings.iso2022_jp', 'encodings.iso8859_6'}
7503 INFO: Loading module hook "hook-pydoc.py"...
7504 INFO: Loading module hook "hook-PySide2.py"...
7519 DEBUG: Collecting data files for PySide2
7521 DEBUG: collect_data_files - Found files: []
7522 WARNING: Hidden import "numpy.core.multiarray" not found!
7523 INFO: Loading module hook "hook-PySide2.QtCore.py"...
7819 DEBUG: Found plugin files [] for plugin 'codecs
7819 INFO: Loading module hook "hook-PySide2.QtGui.py"...
7949 DEBUG: Found plugin files [] for plugin 'accessible
8071 DEBUG: Found plugin files ['C:/python36-x64/lib/site-packages/PySide2/plugins\\iconengines\\qsvgicon.dll'] for plugin 'iconengines
8226 DEBUG: Found plugin files ['C:/python36-x64/lib/site-packages/PySide2/plugins\\imageformats\\qgif.dll', 'C:/python36-x64/lib/site-packages/PySide2/plugins\\imageformats\\qicns.dll'
, 'C:/python36-x64/lib/site-packages/PySide2/plugins\\imageformats\\qico.dll', 'C:/python36-x64/lib/site-packages/PySide2/plugins\\imageformats\\qjpeg.dll', 'C:/python36-x64/lib/site-pa
ckages/PySide2/plugins\\imageformats\\qsvg.dll', 'C:/python36-x64/lib/site-packages/PySide2/plugins\\imageformats\\qtga.dll', 'C:/python36-x64/lib/site-packages/PySide2/plugins\\imagefo
rmats\\qtiff.dll', 'C:/python36-x64/lib/site-packages/PySide2/plugins\\imageformats\\qwbmp.dll', 'C:/python36-x64/lib/site-packages/PySide2/plugins\\imageformats\\qwebp.dll'] for plugin
 'imageformats
8358 DEBUG: Found plugin files [] for plugin 'inputmethods
8496 DEBUG: Found plugin files [] for plugin 'graphicssystems
8637 DEBUG: Found plugin files ['C:/python36-x64/lib/site-packages/PySide2/plugins\\platforms\\qminimal.dll', 'C:/python36-x64/lib/site-packages/PySide2/plugins\\platforms\\qoffscreen.d
ll', 'C:/python36-x64/lib/site-packages/PySide2/plugins\\platforms\\qwebgl.dll', 'C:/python36-x64/lib/site-packages/PySide2/plugins\\platforms\\qwindows.dll'] for plugin 'platforms
8763 DEBUG: Found plugin files ['C:/python36-x64/lib/site-packages/PySide2/plugins\\styles\\qwindowsvistastyle.dll'] for plugin 'styles
8766 INFO: Loading module hook "hook-PySide2.QtNetwork.py"...
8891 DEBUG: Found plugin files ['C:/python36-x64/lib/site-packages/PySide2/plugins\\bearer\\qgenericbearer.dll'] for plugin 'bearer
8893 INFO: Loading module hook "hook-PySide2.QtWidgets.py"...
8895 INFO: Loading module hook "hook-pythoncom.py"...
9222 INFO: Loading module hook "hook-pywintypes.py"...
9558 INFO: Loading module hook "hook-win32com.py"...
9941 INFO: Loading module hook "hook-xml.py"...
10019 DEBUG: Looking for egg data files...
10019 INFO: Looking for ctypes DLLs
10020 DEBUG: Scanning appdirs for shared libraries or dlls
10026 DEBUG: Scanning uuid for shared libraries or dlls
10035 DEBUG: Scanning multiprocessing.sharedctypes for shared libraries or dlls
10040 INFO: Analyzing run-time hooks ...
10044 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
10050 INFO: Including run-time hook 'pyi_rth_qt5plugins.py'
10063 INFO: Looking for dynamic libraries
10070 DEBUG: Analyzing C:\python36-x64\lib\site-packages\PySide2\plugins\imageformats\qtiff.dll
10082 DEBUG: Skipping KERNEL32.dll dependency of qtiff.dll
10086 DEBUG: Adding Qt5Gui.dll dependency of qtiff.dll from c:\python36-x64\lib\site-packages\PySide2\qt5gui.dll
10092 DEBUG: Adding Qt5Core.dll dependency of qtiff.dll from c:\python36-x64\lib\site-packages\PySide2\qt5core.dll
10097 DEBUG: Adding api-ms-win-crt-utility-l1-1-0.dll dependency of qtiff.dll from C:\ProgramData\Anaconda3\api-ms-win-crt-utility-l1-1-0.dll
10097 DEBUG: Analyzing C:\python36-x64\lib\site-packages\PySide2\plugins\imageformats\qjpeg.dll
10109 DEBUG: Skipping KERNEL32.dll dependency of qjpeg.dll
10116 DEBUG: Analyzing C:\python36-x64\lib\site-packages\PySide2\plugins\imageformats\qicns.dll
10124 DEBUG: Skipping KERNEL32.dll dependency of qicns.dll
10134 DEBUG: Analyzing C:\python36-x64\lib\site-packages\PySide2\plugins\platforms\qwebgl.dll
10146 DEBUG: Skipping KERNEL32.dll dependency of qwebgl.dll
10150 DEBUG: Adding Qt5Quick.dll dependency of qwebgl.dll from c:\python36-x64\lib\site-packages\PySide2\qt5quick.dll
10159 DEBUG: Adding Qt5Network.dll dependency of qwebgl.dll from c:\python36-x64\lib\site-packages\PySide2\qt5network.dll
10163 DEBUG: Skipping USER32.dll dependency of qwebgl.dll
10166 DEBUG: Skipping GDI32.dll dependency of qwebgl.dll
10175 DEBUG: Skipping ole32.dll dependency of qwebgl.dll
10178 DEBUG: Skipping ADVAPI32.dll dependency of qwebgl.dll
10182 DEBUG: Skipping MSVCP140.dll dependency of qwebgl.dll
10186 DEBUG: Adding Qt5WebSockets.dll dependency of qwebgl.dll from c:\python36-x64\lib\site-packages\PySide2\qt5websockets.dll
10186 DEBUG: Analyzing C:\python36-x64\lib\site-packages\PySide2\plugins\imageformats\qwebp.dll
10200 DEBUG: Skipping KERNEL32.dll dependency of qwebp.dll
10213 DEBUG: Analyzing C:\python36-x64\lib\site-packages\PySide2\plugins\imageformats\qtga.dll
10220 DEBUG: Skipping KERNEL32.dll dependency of qtga.dll
10229 DEBUG: Analyzing C:\python36-x64\lib\site-packages\PySide2\plugins\platforms\qoffscreen.dll
10239 DEBUG: Skipping KERNEL32.dll dependency of qoffscreen.dll
10252 DEBUG: Analyzing C:\python36-x64\lib\site-packages\PySide2\plugins\platforms\qwindows.dll
10267 DEBUG: Skipping KERNEL32.dll dependency of qwindows.dll
10270 DEBUG: Skipping MSVCP140.dll dependency of qwindows.dll
10278 DEBUG: Skipping IMM32.dll dependency of qwindows.dll
10283 DEBUG: Skipping USER32.dll dependency of qwindows.dll
10287 DEBUG: Skipping ADVAPI32.dll dependency of qwindows.dll
10295 DEBUG: Skipping SHELL32.dll dependency of qwindows.dll
10298 DEBUG: Skipping dwmapi.dll dependency of qwindows.dll
10302 DEBUG: Skipping GDI32.dll dependency of qwindows.dll
10305 DEBUG: Skipping OLEAUT32.dll dependency of qwindows.dll
10318 DEBUG: Skipping WTSAPI32.dll dependency of qwindows.dll
10323 DEBUG: Skipping ole32.dll dependency of qwindows.dll
10324 DEBUG: Analyzing C:\python36-x64\lib\site-packages\PySide2\plugins\styles\qwindowsvistastyle.dll
10333 DEBUG: Adding Qt5Widgets.dll dependency of qwindowsvistastyle.dll from c:\python36-x64\lib\site-packages\PySide2\qt5widgets.dll
10336 DEBUG: Skipping KERNEL32.dll dependency of qwindowsvistastyle.dll
10343 DEBUG: Skipping USER32.dll dependency of qwindowsvistastyle.dll
10346 DEBUG: Skipping GDI32.dll dependency of qwindowsvistastyle.dll
10353 DEBUG: Skipping UxTheme.dll dependency of qwindowsvistastyle.dll
10353 DEBUG: Analyzing C:\python36-x64\lib\site-packages\PySide2\plugins\imageformats\qgif.dll
10362 DEBUG: Skipping KERNEL32.dll dependency of qgif.dll
10369 DEBUG: Analyzing C:\python36-x64\lib\site-packages\PySide2\plugins\imageformats\qico.dll
10378 DEBUG: Skipping KERNEL32.dll dependency of qico.dll
10386 DEBUG: Analyzing C:\python36-x64\lib\site-packages\PySide2\plugins\imageformats\qwbmp.dll
10395 DEBUG: Skipping KERNEL32.dll dependency of qwbmp.dll
10401 DEBUG: Analyzing C:\python36-x64\lib\site-packages\PySide2\plugins\bearer\qgenericbearer.dll
10409 DEBUG: Skipping KERNEL32.dll dependency of qgenericbearer.dll
10413 DEBUG: Skipping IPHLPAPI.DLL dependency of qgenericbearer.dll
10419 DEBUG: Analyzing C:\python36-x64\lib\site-packages\PySide2\plugins\platforms\qminimal.dll
10431 DEBUG: Skipping KERNEL32.dll dependency of qminimal.dll
10437 DEBUG: Skipping USER32.dll dependency of qminimal.dll
10442 DEBUG: Skipping GDI32.dll dependency of qminimal.dll
10449 DEBUG: Skipping ole32.dll dependency of qminimal.dll
10453 DEBUG: Skipping ADVAPI32.dll dependency of qminimal.dll
10457 DEBUG: Analyzing C:\python36-x64\lib\site-packages\PySide2\plugins\iconengines\qsvgicon.dll
10465 DEBUG: Skipping KERNEL32.dll dependency of qsvgicon.dll
10469 DEBUG: Adding Qt5Svg.dll dependency of qsvgicon.dll from c:\python36-x64\lib\site-packages\PySide2\qt5svg.dll
10477 DEBUG: Analyzing C:\python36-x64\lib\site-packages\PySide2\plugins\imageformats\qsvg.dll
10483 DEBUG: Skipping KERNEL32.dll dependency of qsvg.dll
10496 DEBUG: Analyzing c:\python36-x64\lib\site-packages\PySide2\QtCore.pyd
10529 DEBUG: Adding python3.dll dependency of QtCore.pyd from c:\python36-x64\python3.dll
10533 DEBUG: Skipping KERNEL32.dll dependency of QtCore.pyd
10536 DEBUG: Adding pyside2.dll dependency of QtCore.pyd from c:\python36-x64\lib\site-packages\PySide2\pyside2.dll
10558 DEBUG: Adding shiboken2.dll dependency of QtCore.pyd from C:\Python36-x64\Lib\site-packages\shiboken2\shiboken2.dll
10559 DEBUG: Analyzing c:\python36-x64\lib\site-packages\PySide2\QtGui.pyd
10583 DEBUG: Skipping KERNEL32.dll dependency of QtGui.pyd
10594 DEBUG: Skipping MSVCP140.dll dependency of QtGui.pyd
10597 DEBUG: Analyzing c:\python36-x64\lib\site-packages\PySide2\QtWidgets.pyd
10629 DEBUG: Skipping KERNEL32.dll dependency of QtWidgets.pyd
10642 DEBUG: Skipping MSVCP140.dll dependency of QtWidgets.pyd
10645 DEBUG: Analyzing c:\python36-x64\lib\site-packages\PySide2\QtNetwork.pyd
10663 DEBUG: Skipping KERNEL32.dll dependency of QtNetwork.pyd
10673 DEBUG: Analyzing C:\Python36-x64\Lib\site-packages\shiboken2\shiboken2.pyd
10693 DEBUG: Skipping KERNEL32.dll dependency of shiboken2.pyd
10696 DEBUG: Analyzing c:\python36-x64\DLLs\_decimal.pyd
10698 DEBUG: Dependent assemblies of c:\python36-x64\DLLs\_decimal.pyd:
10699 DEBUG: *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
10700 DEBUG: Skipping assembly *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
10712 DEBUG: Skipping KERNEL32.dll dependency of _decimal.pyd
10712 DEBUG: Analyzing c:\python36-x64\DLLs\_ctypes.pyd
10713 DEBUG: Dependent assemblies of c:\python36-x64\DLLs\_ctypes.pyd:
10714 DEBUG: *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
10715 DEBUG: Skipping assembly *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
10722 DEBUG: Skipping KERNEL32.dll dependency of _ctypes.pyd
10728 DEBUG: Skipping ole32.dll dependency of _ctypes.pyd
10731 DEBUG: Skipping OLEAUT32.dll dependency of _ctypes.pyd
10732 DEBUG: Analyzing c:\python36-x64\DLLs\_multiprocessing.pyd
10734 DEBUG: Dependent assemblies of c:\python36-x64\DLLs\_multiprocessing.pyd:
10734 DEBUG: *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
10735 DEBUG: Skipping assembly *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
10742 DEBUG: Skipping KERNEL32.dll dependency of _multiprocessing.pyd
10746 DEBUG: Skipping WS2_32.dll dependency of _multiprocessing.pyd
10747 DEBUG: Analyzing c:\python36-x64\DLLs\_ssl.pyd
10749 DEBUG: Dependent assemblies of c:\python36-x64\DLLs\_ssl.pyd:
10750 DEBUG: *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
10751 DEBUG: Skipping assembly *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
10763 DEBUG: Skipping KERNEL32.dll dependency of _ssl.pyd
10767 DEBUG: Skipping CRYPT32.dll dependency of _ssl.pyd
10771 DEBUG: Skipping USER32.dll dependency of _ssl.pyd
10777 DEBUG: Skipping GDI32.dll dependency of _ssl.pyd
10780 DEBUG: Skipping WS2_32.dll dependency of _ssl.pyd
10783 DEBUG: Skipping ADVAPI32.dll dependency of _ssl.pyd
10786 DEBUG: Analyzing c:\python36-x64\DLLs\unicodedata.pyd
10788 DEBUG: Dependent assemblies of c:\python36-x64\DLLs\unicodedata.pyd:
10789 DEBUG: *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
10789 DEBUG: Skipping assembly *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
10801 DEBUG: Skipping KERNEL32.dll dependency of unicodedata.pyd
10801 DEBUG: Analyzing c:\python36-x64\DLLs\pyexpat.pyd
10802 DEBUG: Dependent assemblies of c:\python36-x64\DLLs\pyexpat.pyd:
10803 DEBUG: *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
10804 DEBUG: Skipping assembly *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
10814 DEBUG: Skipping KERNEL32.dll dependency of pyexpat.pyd
10815 DEBUG: Analyzing c:\python36-x64\DLLs\_hashlib.pyd
10818 DEBUG: Dependent assemblies of c:\python36-x64\DLLs\_hashlib.pyd:
10819 DEBUG: *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
10819 DEBUG: Skipping assembly *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
10833 DEBUG: Skipping KERNEL32.dll dependency of _hashlib.pyd
10838 DEBUG: Skipping USER32.dll dependency of _hashlib.pyd
10844 DEBUG: Skipping GDI32.dll dependency of _hashlib.pyd
10847 DEBUG: Skipping ADVAPI32.dll dependency of _hashlib.pyd
10850 DEBUG: Analyzing c:\python36-x64\DLLs\select.pyd
10852 DEBUG: Dependent assemblies of c:\python36-x64\DLLs\select.pyd:
10853 DEBUG: *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
10854 DEBUG: Skipping assembly *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
10865 DEBUG: Skipping KERNEL32.dll dependency of select.pyd
10869 DEBUG: Skipping WS2_32.dll dependency of select.pyd
10869 DEBUG: Analyzing c:\python36-x64\DLLs\_bz2.pyd
10870 DEBUG: Dependent assemblies of c:\python36-x64\DLLs\_bz2.pyd:
10871 DEBUG: *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
10871 DEBUG: Skipping assembly *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
10880 DEBUG: Skipping KERNEL32.dll dependency of _bz2.pyd
10880 DEBUG: Analyzing c:\python36-x64\DLLs\_lzma.pyd
10882 DEBUG: Dependent assemblies of c:\python36-x64\DLLs\_lzma.pyd:
10883 DEBUG: *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
10883 DEBUG: Skipping assembly *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
10890 DEBUG: Skipping KERNEL32.dll dependency of _lzma.pyd
10890 DEBUG: Analyzing c:\python36-x64\DLLs\_socket.pyd
10893 DEBUG: Dependent assemblies of c:\python36-x64\DLLs\_socket.pyd:
10894 DEBUG: *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
10895 DEBUG: Skipping assembly *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
10904 DEBUG: Skipping KERNEL32.dll dependency of _socket.pyd
10910 DEBUG: Skipping WS2_32.dll dependency of _socket.pyd
10911 DEBUG: Analyzing c:\python36-x64\lib\site-packages\_ruamel_yaml.cp36-win_amd64.pyd
10921 DEBUG: Skipping KERNEL32.dll dependency of _ruamel_yaml.cp36-win_amd64.pyd
10921 DEBUG: Analyzing c:\python36-x64\lib\site-packages\win32\win32wnet.pyd
10930 DEBUG: Skipping KERNEL32.dll dependency of win32wnet.pyd
10942 DEBUG: Adding pywintypes36.dll dependency of win32wnet.pyd from c:\python36-x64\lib\site-packages\pywin32_system32\pywintypes36.dll
10947 DEBUG: Skipping MPR.dll dependency of win32wnet.pyd
10952 DEBUG: Skipping NETAPI32.dll dependency of win32wnet.pyd
10952 DEBUG: Analyzing c:\python36-x64\lib\site-packages\win32\win32api.pyd
10962 DEBUG: Skipping ADVAPI32.dll dependency of win32api.pyd
10965 DEBUG: Skipping KERNEL32.dll dependency of win32api.pyd
10968 DEBUG: Skipping USER32.dll dependency of win32api.pyd
10977 DEBUG: Skipping SHELL32.dll dependency of win32api.pyd
10982 DEBUG: Skipping VERSION.dll dependency of win32api.pyd
10982 DEBUG: Analyzing c:\python36-x64\lib\site-packages\win32\win32evtlog.pyd
10993 DEBUG: Skipping KERNEL32.dll dependency of win32evtlog.pyd
11002 DEBUG: Skipping ADVAPI32.dll dependency of win32evtlog.pyd
11003 DEBUG: Analyzing c:\python36-x64\lib\site-packages\PySide2\qt5gui.dll
11090 DEBUG: Skipping KERNEL32.dll dependency of qt5gui.dll
11093 DEBUG: Skipping USER32.dll dependency of qt5gui.dll
11097 DEBUG: Skipping GDI32.dll dependency of qt5gui.dll
11102 DEBUG: Skipping ole32.dll dependency of qt5gui.dll
11105 DEBUG: Skipping MSVCP140.dll dependency of qt5gui.dll
11106 DEBUG: Analyzing c:\python36-x64\lib\site-packages\PySide2\qt5core.dll
11186 DEBUG: Skipping MPR.dll dependency of qt5core.dll
11189 DEBUG: Skipping KERNEL32.dll dependency of qt5core.dll
11193 DEBUG: Skipping USERENV.dll dependency of qt5core.dll
11196 DEBUG: Skipping MSVCP140.dll dependency of qt5core.dll
11200 DEBUG: Skipping USER32.dll dependency of qt5core.dll
11205 DEBUG: Skipping ADVAPI32.dll dependency of qt5core.dll
11212 DEBUG: Skipping SHELL32.dll dependency of qt5core.dll
11215 DEBUG: Skipping WS2_32.dll dependency of qt5core.dll
11219 DEBUG: Skipping VERSION.dll dependency of qt5core.dll
11227 DEBUG: Skipping WINMM.dll dependency of qt5core.dll
11231 DEBUG: Skipping ole32.dll dependency of qt5core.dll
11233 DEBUG: Skipping NETAPI32.dll dependency of qt5core.dll
11234 DEBUG: Analyzing C:\ProgramData\Anaconda3\api-ms-win-crt-utility-l1-1-0.dll
11238 DEBUG: Analyzing c:\python36-x64\lib\site-packages\PySide2\qt5quick.dll
11280 DEBUG: Skipping KERNEL32.dll dependency of qt5quick.dll
11283 DEBUG: Skipping MSVCP140.dll dependency of qt5quick.dll
11287 DEBUG: Skipping USER32.dll dependency of qt5quick.dll
11292 DEBUG: Adding Qt5Qml.dll dependency of qt5quick.dll from c:\python36-x64\lib\site-packages\PySide2\Qt5Qml.dll
11294 DEBUG: Analyzing c:\python36-x64\lib\site-packages\PySide2\qt5network.dll
11311 DEBUG: Skipping KERNEL32.dll dependency of qt5network.dll
11317 DEBUG: Skipping CRYPT32.dll dependency of qt5network.dll
11321 DEBUG: Skipping DNSAPI.dll dependency of qt5network.dll
11326 DEBUG: Skipping IPHLPAPI.DLL dependency of qt5network.dll
11331 DEBUG: Skipping WS2_32.dll dependency of qt5network.dll
11335 DEBUG: Skipping ADVAPI32.dll dependency of qt5network.dll
11338 DEBUG: Skipping MSVCP140.dll dependency of qt5network.dll
11338 DEBUG: Analyzing c:\python36-x64\lib\site-packages\PySide2\qt5websockets.dll
11349 DEBUG: Skipping KERNEL32.dll dependency of qt5websockets.dll
11349 DEBUG: Analyzing c:\python36-x64\lib\site-packages\PySide2\qt5widgets.dll
11388 DEBUG: Skipping KERNEL32.dll dependency of qt5widgets.dll
11394 DEBUG: Skipping dwmapi.dll dependency of qt5widgets.dll
11397 DEBUG: Skipping GDI32.dll dependency of qt5widgets.dll
11401 DEBUG: Skipping USER32.dll dependency of qt5widgets.dll
11404 DEBUG: Skipping UxTheme.dll dependency of qt5widgets.dll
11410 DEBUG: Skipping MSVCP140.dll dependency of qt5widgets.dll
11411 DEBUG: Analyzing c:\python36-x64\lib\site-packages\PySide2\qt5svg.dll
11423 DEBUG: Skipping KERNEL32.dll dependency of qt5svg.dll
11423 DEBUG: Analyzing c:\python36-x64\python3.dll
11424 DEBUG: Dependent assemblies of c:\python36-x64\python3.dll:
11425 DEBUG: *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
11426 DEBUG: Skipping assembly *_Microsoft.Windows.Common-Controls_6595b64144ccf1df_6.0.0.0_none
11481 DEBUG: Analyzing c:\python36-x64\lib\site-packages\PySide2\pyside2.dll
11491 DEBUG: Skipping KERNEL32.dll dependency of pyside2.dll
11496 DEBUG: Skipping MSVCP140.dll dependency of pyside2.dll
11499 DEBUG: Analyzing C:\Python36-x64\Lib\site-packages\shiboken2\shiboken2.dll
11509 DEBUG: Skipping KERNEL32.dll dependency of shiboken2.dll
11513 DEBUG: Skipping MSVCP140.dll dependency of shiboken2.dll
11513 DEBUG: Analyzing c:\python36-x64\lib\site-packages\pywin32_system32\pywintypes36.dll
11528 DEBUG: Skipping KERNEL32.dll dependency of pywintypes36.dll
11539 DEBUG: Skipping USER32.dll dependency of pywintypes36.dll
11546 DEBUG: Skipping ole32.dll dependency of pywintypes36.dll
11550 DEBUG: Skipping ADVAPI32.dll dependency of pywintypes36.dll
11553 DEBUG: Skipping OLEAUT32.dll dependency of pywintypes36.dll
11553 DEBUG: Analyzing c:\python36-x64\lib\site-packages\PySide2\Qt5Qml.dll
11585 DEBUG: Skipping KERNEL32.dll dependency of Qt5Qml.dll
11591 DEBUG: Skipping SHELL32.dll dependency of Qt5Qml.dll
11595 DEBUG: Skipping MSVCP140.dll dependency of Qt5Qml.dll
11595 INFO: Looking for eggs
11596 INFO: Using Python library c:\python36-x64\python36.dll
11596 INFO: Found binding redirects:
[]
11812 INFO: Warnings written to C:\Users\teckc\PycharmProjects\FastFlix\build\FastFlix\warn-FastFlix.txt
11884 INFO: Graph cross-reference written to C:\Users\teckc\PycharmProjects\FastFlix\build\FastFlix\xref-FastFlix.html
11926 INFO: Graph drawing written to C:\Users\teckc\PycharmProjects\FastFlix\build\FastFlix\graph-FastFlix.dot
11942 INFO: Appending 'datas' from .spec
11977 INFO: checking PYZ
11977 INFO: Building PYZ because PYZ-00.toc is non existent
11978 INFO: Building PYZ (ZlibArchive) C:\Users\teckc\PycharmProjects\FastFlix\build\FastFlix\PYZ-00.pyz
11980 INFO: Building PYZ (ZlibArchive) C:\Users\teckc\PycharmProjects\FastFlix\build\FastFlix\PYZ-00.pyz completed successfully.
11986 INFO: checking PKG
11987 INFO: Building PKG because PKG-00.toc is non existent
11987 INFO: Building PKG (CArchive) PKG-00.pkg
11998 DEBUG: Compiling c:\python36-x64\lib\site-packages\PyInstaller\loader\pyiboot01_bootstrap.py
11999 DEBUG: Compiling c:\python36-x64\lib\site-packages\PyInstaller\loader\pyiboot01_bootstrap.py
12001 DEBUG: Compiling c:\python36-x64\lib\site-packages\PyInstaller\loader\rthooks\pyi_rth_multiprocessing.py
12003 DEBUG: Compiling c:\python36-x64\lib\site-packages\PyInstaller\loader\rthooks\pyi_rth_multiprocessing.py
12004 DEBUG: Compiling c:\python36-x64\lib\site-packages\PyInstaller\loader\rthooks\pyi_rth_qt5plugins.py
12005 DEBUG: Compiling c:\python36-x64\lib\site-packages\PyInstaller\loader\rthooks\pyi_rth_qt5plugins.py
12007 DEBUG: Compiling C:\Users\teckc\PycharmProjects\FastFlix\flix\gui.py
12008 DEBUG: Compiling C:\Users\teckc\PycharmProjects\FastFlix\flix\gui.py
12017 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
12024 INFO: Bootloader c:\python36-x64\lib\site-packages\PyInstaller\bootloader\Windows-64bit\runw_d.exe
12024 INFO: checking EXE
12025 INFO: Building EXE because EXE-00.toc is non existent
12026 INFO: Building EXE from EXE-00.toc
12038 INFO: Copying icons from ['data\\icon.ico']
12044 INFO: Writing RT_GROUP_ICON 0 resource with 20 bytes
12045 INFO: Writing RT_ICON 1 resource with 270376 bytes
12060 INFO: Appending archive to EXE C:\Users\teckc\PycharmProjects\FastFlix\build\FastFlix\FastFlix.exe
12072 INFO: Building EXE from EXE-00.toc completed successfully.
12079 INFO: checking COLLECT
12080 INFO: Building COLLECT because COLLECT-00.toc is non existent
WARNING: The output directory "C:\Users\teckc\PycharmProjects\FastFlix\dist\FastFlix" and ALL ITS CONTENTS will be REMOVED! Continue? (y/n)Y
17351 INFO: Removing dir C:\Users\teckc\PycharmProjects\FastFlix\dist\FastFlix
17683 INFO: Building COLLECT COLLECT-00.toc
20895 INFO: Building COLLECT COLLECT-00.toc completed successfully.

```

</details>

If there is anything else I can do or provide to make this easier to solve please let me know. 

I did have to apply [this fix](https://github.com/pyinstaller/pyinstaller/issues/4034) to have the `--debug` option working, just in case that changes anything.

Thank you for your time!

**Comment by fgs-dbudwin** [comment]
I am experiencing similar issues to this.  Any updates?

**Comment by madebr** [comment]
I'm seeing a similar issue while trying to freeze [SubDownloader](https://github.com/subdownloader/subdownloader).
Running
`pyinstaller subdownloader.py -d all -w --noupx`
and
`dist\subdownloader\subdownloader.exe`
will create the same error dialog with the text: `failed to execute pyiboot01_bootstrap`.

This is on: PyInstaller 3.5, cpython 3.7.4 and using PyQt5 5.13.0

**Comment by madebr** [comment]
I managed to reduce the problem.
In my case, it happens when the python script I am freezing has the same name as the accompanying python module.

Create the following 2 files:

**projectname.py**
```
if __name__ == '__main__':
    print(__name__)
    from projectname import main
    main()
```

**projectname\__init__.py**
```
def main():
    print(__name__, 'main()')
```

Then execute pyinstaller:

```
pyinstaller projectname.py -d bootloader
```

The resulting `dist\projectname\projectname.exe` will show the error dialog shown in https://github.com/pyinstaller/pyinstaller/issues/4213#issue-440395223

When copying **projectname.py** to **projectname2.py** and running pyinstaller on that file, the resulting exe works fine (apart from it being a cli app packaged as a windowed app).

**Comment by danyeaw** [comment]
I also ran in to this issue, and my python script doesn't have the same name as they python module. I have set debug=True. I am not getting any errors when running with console=True. When I run with console=False, there is no useful error messages, just like @cdgriffith reported. Is there any method to get better debug output?

**Comment by kennyjeffris** [comment]
Also experiencing this problem with --noconsole mode.  I get the message `failed to execute pyiboot01_bootstrap`.  Running python 3.6.8, pyinstaller 3.5, Windows 10, pyqt 5.13.1

**Comment by rafael-mq** [comment]
I'm also facing this problem on some Windows 7 and Windows 10 computers.
Python 3.7.4 - 32bits
PyInstaller 4.0 dev
I'm building my program on a single executable.
I tried building it with debug mode on (--debug all) and at some point an error message appears saying it failed to execute script "pyiboot01_bootstrap".
I'm reaaly looking forward for an answer on this topic.

**Comment by rafael-mq** [comment]
> I'm also facing this problem on some Windows 7 and Windows 10 computers.
> Python 3.7.4 - 32bits
> PyInstaller 4.0 dev
> I'm building my program on a single executable.
> I tried building it with debug mode on (--debug all) and at some point an error message appears saying it failed to execute script "pyiboot01_bootstrap".
> I'm reaaly looking forward for an answer on this topic.

I solved the problem in my case downgrading both Python to 3.6.8 and PyInstaller to 3.4.

**Comment by danyeaw** [comment]
@htgoebel I would like to help try to solve this during my winter break. Do you have any pointers on methods to debug issues when running with --console causes the issue to go away? I have of course gone through the When Things Go Wrong a few times.

**Comment by danyeaw** [comment]
My current plan is to modify the bootloader to display the traceback information using [PyErr_Fetch](https://docs.python.org/3/c-api/exceptions.html#c.PyErr_Fetch) when the pyiboot01_bootstrap message is displayed. In order to accomplish this, I have submitted two PRs which fix bootloader building in MSYS2. We'll see if I can make this work.

**Comment by madebr** [comment]
Better error reporting is always a big win.

**Comment by danyeaw** [comment]
My plan worked, I was able to successfully extract a traceback, which gave me the following error:
```
Traceback (most recent call last):
File "pyinstaller/Pyinstaller/loader/pyiboot01_bootstrap.py", line 18, in <module>
File "pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 796, in install fimp = FrozenImporter()
File "pyinstaller/PyInstaller/loader/pyimod03_imports.py", line 214, in __init__
PyInstaller: FrozenImporter(%s), pyz_filepath
File "pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 58, in trace sys.stderr.write(msg % a), AttributeError: NoneType object has no attribute write
```
With the traceback, I was able to quickly determine that I had an issue in my spec file, I was passing the following [run-time option](https://pythonhosted.org/PyInstaller/spec-files.html#giving-run-time-python-options):
`options = [ ('v', None, 'OPTION') ]`

This was my mistake and it was a simple fix once I knew what the error was. I was getting an AttributeError because PyInstaller was trying to write a message to stderr each time a module was loaded. Since I was running in --windowed, sys.stderr was set to None, and writing to stderr was raising an AttributeError.

Since some of the others who have the same error message are directly executing using the command arguments instead of a spec file, this doesn't sound like it related - unless PyInstaller is itself configuring with this option.  Two things that could be improved here:

1. The spec parsing should flag this as an invalid combination of setting `noconsole=True` and setting `options = [ ('v', None, 'OPTION') ]`.
2. Getting tracebacks of Python errors while the bootloader is executing allows for quickly debugging errors instead of days and days of troubleshooting.

If anyone wants to play with the Tracebacks enabled, you can use my branch:
https://github.com/danyeaw/pyinstaller/tree/modify-bootloader

You will need to [build the bootloader](https://pythonhosted.org/PyInstaller/bootloader-building.htm) to make use of it.

I will work on trying to make a proper PR using these updates, but this will be more work. I am using the Python 3.3+ C-API for Python, so I will need to dig in to more how PyInstaller makes use of the API to support Python 2.7 as well and try make the traceback functionality more atomic so that it can be used to capture all Python errors in the bootloader.

**Comment by danyeaw** [comment]
I created PR #4259. In order to get the full traceback you need to run with `--debug=noarchive`. I also pushed the compiled bootloader as well, so you won't need to build your own version. I would appreciate anyone with pyiboot01_bootloader errors to give it a spin.

**Comment by onsunsl** [comment]
I am also facing this problem on Windows10 64bit
Python 3.6.7
Pyiinstaller 3.6

Solvoed after downgrading Pyinstaller to 3.5.

**Comment by samtanderson** [comment]
Seems like this issue is still lurking. 
When building a file using the following, I get `<NULL>` error and traceback

`pyinstaller --onefile --icon=favicon.ico --noconsole --windowed calcPatch.py --debug all`

Everything works correctly and forms a running application when dropping `--noconsole` . Seems strictly related to this parameter.

**Comment by htgoebel** [comment]
https://github.com/pyinstaller/pyinstaller/issues/4213#issuecomment-524534428 might to be the key:

>  In my case, it happens when the python script I am freezing has the same name as the accompanying python module.

**Comment by TheLukaBoss** [comment]
Hello.
I too have the same issue, and I suspect one of my modules: 'pystray' used to show system tray icons.
I am new to this, so any help would be greatly appreciated. 
I have attached my Python code (you'll need to change the file extension to .py or .pyw to run it, and it will only run on Windows)
[wifiChecker.txt](https://github.com/pyinstaller/pyinstaller/files/5395708/wifiChecker.txt)

Thank you very much,
Luka S

**Comment by Cats-png** [comment]
I had this issue as well with pyinstaller 4.0, but using [this comment](https://github.com/pyinstaller/pyinstaller/issues/4213#issuecomment-569381968) I have found a solution.

The command `pyinstaller -F -d all -i ./assets/favicon.ico -w filename.py` produces a exe file with that 'failed to execute script pyiboot01_bootstrap'. Open the spec file in a text editor and delete `[('v', None, 'OPTION')],` which is found in line 25. Then run `pyinstaller -F -d all -i ./assets/favicon.ico -w filename.spec` (building from a spec file) and you should have a program that runs.

**Comment by haxpak** [comment]
> I had this issue as well with pyinstaller 4.0, but using [this comment](https://github.com/pyinstaller/pyinstaller/issues/4213#issuecomment-569381968) I have found a solution.
> 
> The command `pyinstaller -F -d all -i ./assets/favicon.ico -w filename.py` produces a exe file with that 'failed to execute script pyiboot01_bootstrap'. Open the spec file in a text editor and delete `[('v', None, 'OPTION')],` which is found in line 25. Then run `pyinstaller -F -d all -i ./assets/favicon.ico -w filename.spec` (building from a spec file) and you should have a program that runs.

tried this, but now the error is `Failed to execute script` 
on next window, I get a messagebox
`Fatal error detected

Error : <NULL>
`

Just to mention that my script on start checks for some os details on start using subprocess.check_output("<some wmic command>")

**Comment by pinebud77** [comment]
I have the same problem with Python 3.9.1 and PyInstaller 4.1 on Windows 10.

If I replace runw_d.exe with run_d.exe, there is no issue (of course console appears). I think windowed bootloader has some issue with MS Windows.

**Comment by Mohammed-AhmedAF** [comment]
> I had this issue as well with pyinstaller 4.0, but using [this comment](https://github.com/pyinstaller/pyinstaller/issues/4213#issuecomment-569381968) I have found a solution.
> 
> The command `pyinstaller -F -d all -i ./assets/favicon.ico -w filename.py` produces a exe file with that 'failed to execute script pyiboot01_bootstrap'. Open the spec file in a text editor and delete `[('v', None, 'OPTION')],` which is found in line 25. Then run `pyinstaller -F -d all -i ./assets/favicon.ico -w filename.spec` (building from a spec file) and you should have a program that runs.

Thank you, that worked for me.

**Comment by smartreddit** [comment]
`pyinstaller --onefile --noconsole --debug=bootloader myscript.py`
I've looked into the source (as of the time of writing) and figured out if you add `--debug=bootloader`, should give you the result you require. If you're quite curious about thism this _workaround_ works just like how other fixes above work, additionally, look into this line https://github.com/pyinstaller/pyinstaller/blob/35103b3e158dcc4f062d74bf64aa7860b2d75858/PyInstaller/building/makespec.py#L440

**Comment by Carewen** [comment]
> pyinstaller --onefile --noconsole --debug=bootloader myscript.py

That didn't work for me. It looks like the search continues. PyInstaller is not working in PyCharm for me at all.

**Comment by Legorooj** [comment]
@Carewen please open a new issue; we can help there.

**Comment by Carewen** [comment]
> 
> 
> @Carewen please open a new issue; we can help there.

Entering a new issue is quite a bit of heavy lifting. Particularly for a known issue that has workarounds I've tried that do not work.  I'll have a go but I'm less than month into working with Python and I suspect it's going to take me a while to complete the issue submission.

**Comment by Legorooj** [comment]
It's very likely not the same bug, which is why I'm asking you to open a new one. `Failed to execute script pyiboot01_bootstrap` - this message could be caused by dozens of possible issues. This issue appears to have been fixed, which is why I think your error is a new one.
