### ISSUE TITLE
Pyinstaller can't find dynamically linked libs for Mac OS X Big Sur Beta 

### ISSUE THREAD

**Issue by nbrummel** [pyinstaller/pyinstaller#5107]
## Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.0.dev0```
* Version of Python: 3.8.5
* Platform: OS X 11.0 Beta Big Sur

[Link to Release Note below.](https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11-beta-release-notes/)
From apple: 

New in macOS Big Sur 11 beta, the system ships with a built-in dynamic linker cache of all system-provided libraries. As part of this change, copies of dynamic libraries are no longer present on the filesystem. Code that attempts to check for dynamic library presence by looking for a file at a path or enumerating a directory will fail. Instead, check for library presence by attempting to dlopen() the path, which will correctly check for the library in the cache. (62986286)## Description of the issue

* Did you also try this on another platform? Does it work there?
Works on windows.  This is an issue with the new beta and a change that needs to be made for the new macOS Big Sur

### A minimal example program which shows the error

```
17946 ERROR: Can not find path /usr/lib/<lib> (needed by /usr/local/lib/<lib>.dylib)
...
many many more...
```

### Stacktrace / full error message

```
96 INFO: PyInstaller: 4.0.dev0
96 INFO: Python: 3.8.5
103 INFO: Platform: macOS-10.16-x86_64-i386-64bit
106 INFO: UPX is not available.
107 INFO: Removing temporary files and cleaning cache in /Users/nb/Library/Application Support/pyinstaller
123 INFO: Extending PYTHONPATH with paths
['/Users/nb/emerge/sw/tactile_engine/source/code',
 '/Users/nb/emerge/sw/tactile_engine/source/tactile_engine/source/code']
151 INFO: checking Analysis
151 INFO: Building Analysis because Analysis-00.toc is non existent
151 INFO: Initializing module dependency graph...
155 INFO: Caching module graph hooks...
164 INFO: Analyzing base_library.zip ...
2502 INFO: Processing pre-find module path hook distutils from '/usr/local/lib/python3.8/site-packages/PyInstaller/hooks/pre_find_module_path/hook-distutils.py'.
2504 INFO: distutils: retargeting to non-venv dir '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8'
4923 INFO: Caching module dependency graph...
5021 INFO: running Analysis Analysis-00.toc
5025 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/opt/python@3.8/bin/../Frameworks/Python.framework/Versions/3.8/bin/python3.8)
5028 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/Python)
5028 ERROR: Can not find path /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/Python)
5030 ERROR: Can not find path /usr/lib/libiconv.2.dylib (needed by /usr/local/lib/libintl.8.dylib)
5030 ERROR: Can not find path /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (needed by /usr/local/lib/libintl.8.dylib)
5030 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/lib/libintl.8.dylib)
5030 INFO: Analyzing top/tactile_engine.py
7538 INFO: Processing pre-safe import module hook setuptools.extern.six.moves from '/usr/local/lib/python3.8/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-setuptools.extern.six.moves.py'.
7971 INFO: Processing pre-find module path hook site from '/usr/local/lib/python3.8/site-packages/PyInstaller/hooks/pre_find_module_path/hook-site.py'.
7972 INFO: site: retargeting to fake-dir '/usr/local/lib/python3.8/site-packages/PyInstaller/fake-modules'
9360 INFO: Processing pre-safe import module hook six.moves from '/usr/local/lib/python3.8/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-six.moves.py'.
/usr/local/lib/python3.8/site-packages/pyquaternion/quaternion.py:62: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if s is 0:
/usr/local/lib/python3.8/site-packages/pyquaternion/quaternion.py:104: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(elements) is 1:
/usr/local/lib/python3.8/site-packages/pyquaternion/quaternion.py:113: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif s is 1:
/usr/local/lib/python3.8/site-packages/pyquaternion/quaternion.py:152: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif len(seq) is 0:
11964 INFO: Processing pre-safe import module hook urllib3.packages.six.moves from '/usr/local/lib/python3.8/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-urllib3.packages.six.moves.py'.
13370 INFO: Processing module hooks...
13370 INFO: Loading module hook 'hook-usb.py' from '/usr/local/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
13395 INFO: Loading module hook 'hook-certifi.py' from '/usr/local/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
13400 INFO: Loading module hook 'hook-pytest.py' from '/usr/local/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
14521 INFO: Loading module hook 'hook-pkg_resources.py' from '/usr/local/lib/python3.8/site-packages/PyInstaller/hooks'...
14915 INFO: Processing pre-safe import module hook win32com from '/usr/local/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/pre_safe_import_module/hook-win32com.py'.
15082 WARNING: Hidden import "pkg_resources.py2_warn" not found!
15308 WARNING: Hidden import "pkg_resources.markers" not found!
15310 INFO: Excluding import '__main__'
15311 INFO:   Removing import of __main__ from module pkg_resources
15311 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from '/usr/local/lib/python3.8/site-packages/PyInstaller/hooks'...
15312 INFO: Loading module hook 'hook-lib2to3.py' from '/usr/local/lib/python3.8/site-packages/PyInstaller/hooks'...
15361 INFO: Loading module hook 'hook-encodings.py' from '/usr/local/lib/python3.8/site-packages/PyInstaller/hooks'...
15425 INFO: Loading module hook 'hook-setuptools.py' from '/usr/local/lib/python3.8/site-packages/PyInstaller/hooks'...
/usr/local/lib/python3.8/site-packages/setuptools/distutils_patch.py:25: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  warnings.warn(
16004 INFO: Loading module hook 'hook-xml.dom.domreg.py' from '/usr/local/lib/python3.8/site-packages/PyInstaller/hooks'...
16005 INFO: Loading module hook 'hook-packaging.py' from '/usr/local/lib/python3.8/site-packages/PyInstaller/hooks'...
16006 INFO: Loading module hook 'hook-sysconfig.py' from '/usr/local/lib/python3.8/site-packages/PyInstaller/hooks'...
16013 INFO: Loading module hook 'hook-wcwidth.py' from '/usr/local/lib/python3.8/site-packages/PyInstaller/hooks'...
16020 INFO: Loading module hook 'hook-numpy.core.py' from '/usr/local/lib/python3.8/site-packages/PyInstaller/hooks'...
16120 INFO: Loading module hook 'hook-xml.py' from '/usr/local/lib/python3.8/site-packages/PyInstaller/hooks'...
16121 INFO: Loading module hook 'hook-numpy.py' from '/usr/local/lib/python3.8/site-packages/PyInstaller/hooks'...
16122 INFO: Loading module hook 'hook-distutils.py' from '/usr/local/lib/python3.8/site-packages/PyInstaller/hooks'...
16123 INFO: Loading module hook 'hook-pygments.py' from '/usr/local/lib/python3.8/site-packages/PyInstaller/hooks'...
17773 INFO: Looking for ctypes DLLs
17826 WARNING: library ftd2xx64.dll required via ctypes not found
17863 WARNING: Ignoring /usr/local/lib/libftd2xx.dylib imported from /usr/local/lib/python3.8/site-packages/ftd2xx/_ftd2xx_darwin.py - ctypes imports are only supported using bare filenames
17906 INFO: Analyzing run-time hooks ...
17915 INFO: Including run-time hook '/usr/local/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/rthooks/pyi_rth_usb.py'
17919 INFO: Including run-time hook '/usr/local/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pkgres.py'
17920 INFO: Including run-time hook '/usr/local/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/rthooks/pyi_rth_certifi.py'
17921 INFO: Including run-time hook '/usr/local/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py'
17944 INFO: Looking for dynamic libraries
17946 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/lib/libusb-1.0.dylib)
17947 ERROR: Can not find path /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (needed by /usr/local/lib/libusb-1.0.dylib)
17947 ERROR: Can not find path /usr/lib/libobjc.A.dylib (needed by /usr/local/lib/libusb-1.0.dylib)
17947 ERROR: Can not find path /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (needed by /usr/local/lib/libusb-1.0.dylib)
17949 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/lib/libftd2xx.dylib)
17949 ERROR: Can not find path /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (needed by /usr/local/lib/libftd2xx.dylib)
17949 ERROR: Can not find path /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (needed by /usr/local/lib/libftd2xx.dylib)
17952 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/lib/libftd2xx.dylib)
17952 ERROR: Can not find path /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (needed by /usr/local/lib/libftd2xx.dylib)
17952 ERROR: Can not find path /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (needed by /usr/local/lib/libftd2xx.dylib)
17953 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/select.cpython-38-darwin.so)
17954 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/math.cpython-38-darwin.so)
17955 ERROR: Can not find path /usr/lib/libz.1.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/zlib.cpython-38-darwin.so)
17955 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/zlib.cpython-38-darwin.so)
17957 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/pyexpat.cpython-38-darwin.so)
17958 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_scproxy.cpython-38-darwin.so)
17958 ERROR: Can not find path /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_scproxy.cpython-38-darwin.so)
17958 ERROR: Can not find path /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_scproxy.cpython-38-darwin.so)
17959 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/termios.cpython-38-darwin.so)
17960 ERROR: Can not find path /usr/lib/libz.1.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/binascii.cpython-38-darwin.so)
17960 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/binascii.cpython-38-darwin.so)
17961 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_random.cpython-38-darwin.so)
17963 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_sha512.cpython-38-darwin.so)
17965 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_ssl.cpython-38-darwin.so)
17966 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_hashlib.cpython-38-darwin.so)
17967 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_sha3.cpython-38-darwin.so)
17968 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_blake2.cpython-38-darwin.so)
17969 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_sha256.cpython-38-darwin.so)
17970 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_md5.cpython-38-darwin.so)
17971 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_sha1.cpython-38-darwin.so)
17972 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_bisect.cpython-38-darwin.so)
17974 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/unicodedata.cpython-38-darwin.so)
17976 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_contextvars.cpython-38-darwin.so)
17977 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_decimal.cpython-38-darwin.so)
17978 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_datetime.cpython-38-darwin.so)
17979 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_posixshmem.cpython-38-darwin.so)
17980 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/mmap.cpython-38-darwin.so)
17982 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_ctypes.cpython-38-darwin.so)
17983 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/array.cpython-38-darwin.so)
17984 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_queue.cpython-38-darwin.so)
17985 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/resource.cpython-38-darwin.so)
17986 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/grp.cpython-38-darwin.so)
17987 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_lzma.cpython-38-darwin.so)
17988 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_bz2.cpython-38-darwin.so)
17988 ERROR: Can not find path /usr/lib/libbz2.1.0.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_bz2.cpython-38-darwin.so)
17989 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_csv.cpython-38-darwin.so)
17990 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/readline.cpython-38-darwin.so)
17991 ERROR: Can not find path /usr/lib/libncurses.5.4.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/readline.cpython-38-darwin.so)
17992 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_opcode.cpython-38-darwin.so)
17993 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_pickle.cpython-38-darwin.so)
17994 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_multiprocessing.cpython-38-darwin.so)
17996 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_struct.cpython-38-darwin.so)
17997 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_testcapi.cpython-38-darwin.so)
18000 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_elementtree.cpython-38-darwin.so)
18001 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_asyncio.cpython-38-darwin.so)
18002 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_posixsubprocess.cpython-38-darwin.so)
18003 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_uuid.cpython-38-darwin.so)
18004 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_multibytecodec.cpython-38-darwin.so)
18005 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_codecs_kr.cpython-38-darwin.so)
18006 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_codecs_jp.cpython-38-darwin.so)
18007 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_codecs_tw.cpython-38-darwin.so)
18009 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_codecs_iso2022.cpython-38-darwin.so)
18010 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_codecs_cn.cpython-38-darwin.so)
18011 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_codecs_hk.cpython-38-darwin.so)
18012 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_heapq.cpython-38-darwin.so)
18013 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/lib/python3.8/site-packages/_yaml.cpython-38-darwin.so)
18014 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/syslog.cpython-38-darwin.so)
18016 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_curses.cpython-38-darwin.so)
18016 ERROR: Can not find path /usr/lib/libncurses.5.4.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_curses.cpython-38-darwin.so)
18017 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/fcntl.cpython-38-darwin.so)
18045 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/parser.cpython-38-darwin.so)
18046 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/lib/python3.8/site-packages/numpy/core/_multiarray_tests.cpython-38-darwin.so)
18050 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so)
18050 ERROR: Can not find path /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate (needed by /usr/local/lib/python3.8/site-packages/numpy/core/_multiarray_umath.cpython-38-darwin.so)
18053 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/lib/python3.8/site-packages/numpy/random/mtrand.cpython-38-darwin.so)
18054 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/lib/python3.8/site-packages/numpy/random/_sfc64.cpython-38-darwin.so)
18055 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/lib/python3.8/site-packages/numpy/random/_philox.cpython-38-darwin.so)
18057 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/lib/python3.8/site-packages/numpy/random/_pcg64.cpython-38-darwin.so)
18058 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/lib/python3.8/site-packages/numpy/random/_mt19937.cpython-38-darwin.so)
18059 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/lib/python3.8/site-packages/numpy/random/_bit_generator.cpython-38-darwin.so)
18061 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/lib/python3.8/site-packages/numpy/random/_generator.cpython-38-darwin.so)
18062 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/lib/python3.8/site-packages/numpy/random/_bounded_integers.cpython-38-darwin.so)
18063 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/lib/python3.8/site-packages/numpy/random/_common.cpython-38-darwin.so)
18065 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/lib/python3.8/site-packages/numpy/fft/_pocketfft_internal.cpython-38-darwin.so)
18067 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/lib/python3.8/site-packages/numpy/linalg/_umath_linalg.cpython-38-darwin.so)
18067 ERROR: Can not find path /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate (needed by /usr/local/lib/python3.8/site-packages/numpy/linalg/_umath_linalg.cpython-38-darwin.so)
18068 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/lib/python3.8/site-packages/numpy/linalg/lapack_lite.cpython-38-darwin.so)
18068 ERROR: Can not find path /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate (needed by /usr/local/lib/python3.8/site-packages/numpy/linalg/lapack_lite.cpython-38-darwin.so)
18069 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/lib/python3.8/site-packages/yarl/_quoting_c.cpython-38-darwin.so)
18070 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/lib/python3.8/site-packages/multidict/_multidict.cpython-38-darwin.so)
18071 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_socket.cpython-38-darwin.so)
18072 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload/_json.cpython-38-darwin.so)
18073 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib)
18075 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/opt/openssl@1.1/lib/libcrypto.1.1.dylib)
18077 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/lib/liblzma.5.dylib)
18078 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/opt/readline/lib/libreadline.8.dylib)
18078 ERROR: Can not find path /usr/lib/libncurses.5.4.dylib (needed by /usr/local/opt/readline/lib/libreadline.8.dylib)
18079 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/lib/libyaml-0.2.dylib)
18080 INFO: Looking for eggs
18080 INFO: Using Python library /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/Python
18089 INFO: Warnings written to /Users/nb/emerge/sw/tactile_engine/source/code/build/tactile_engine/warn-tactile_engine.txt
18183 INFO: Graph cross-reference written to /Users/nb/emerge/sw/tactile_engine/source/code/build/tactile_engine/xref-tactile_engine.html
18210 INFO: Appending 'datas' from .spec
18214 INFO: checking PYZ
18214 INFO: Building PYZ because PYZ-00.toc is non existent
18214 INFO: Building PYZ (ZlibArchive) /Users/nb/emerge/sw/tactile_engine/source/code/build/tactile_engine/PYZ-00.pyz
19419 INFO: Building PYZ (ZlibArchive) /Users/nb/emerge/sw/tactile_engine/source/code/build/tactile_engine/PYZ-00.pyz completed successfully.
19445 INFO: checking PKG
19445 INFO: Building PKG because PKG-00.toc is non existent
19445 INFO: Building PKG (CArchive) PKG-00.pkg
19447 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/opt/python@3.8/bin/python3.8)
19464 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
19465 INFO: Bootloader /usr/local/lib/python3.8/site-packages/PyInstaller/bootloader/Darwin-64bit/run
19465 INFO: checking EXE
19465 INFO: Building EXE because EXE-00.toc is non existent
19465 INFO: Building EXE from EXE-00.toc
19465 INFO: Appending archive to EXE /Users/nb/emerge/sw/tactile_engine/source/code/build/tactile_engine/TactileEngine
19473 INFO: Fixing EXE for code signing /Users/nb/emerge/sw/tactile_engine/source/code/build/tactile_engine/TactileEngine
19476 INFO: Building EXE from EXE-00.toc completed successfully.
19477 INFO: checking COLLECT
19477 INFO: Building COLLECT because COLLECT-00.toc is non existent
19477 INFO: Removing dir /Users/nb/emerge/sw/tactile_engine/source/code/dist/tactile_engine
19493 INFO: Building COLLECT COLLECT-00.toc
20707 INFO: Building COLLECT COLLECT-00.toc completed successfully.
20714 INFO: checking BUNDLE
20714 INFO: Building BUNDLE because BUNDLE-00.toc is non existent
20714 INFO: Removing dir /Users/nb/emerge/sw/tactile_engine/source/code/dist/TactileEngine.app
20734 INFO: Building BUNDLE BUNDLE-00.toc
21871 INFO: moving BUNDLE data files to Resource directory
```

**Comment by bwoodsend** [comment]
> Code that attempts to check for dynamic library presence by looking for a file at a path or enumerating a directory will fail. Instead, check for library presence by attempting to dlopen() the path

Can you clarify what you mean here. Are you saying `os.path.exists("/path/to/lib.dyllib")` will always return false? And what would happen if we searched `PATH` variables using `shutil.which()` or `ctypes.util.find_library()`. 

I also notice all those missing libraries in your build log are all (I think) system ones. Is this only applicable to macOS's system libraries or does your test program just not happen to use any others?

**Comment by nbrummel** [comment]
That is true all the files are system ones.  In the new beta, they moved them and made them hidden in the directory structure. 

```
Link to Release Note above.
From apple:

New in macOS Big Sur 11 beta, the system ships with a built-in dynamic linker cache of all system-provided libraries. As part of this change, copies of dynamic libraries are no longer present on the filesystem. Code that attempts to check for dynamic library presence by looking for a file at a path or enumerating a directory will fail. Instead, check for library presence by attempting to dlopen() the path, which will correctly check for the library in the cache. (62986286)## Description of the issue
```


All we have to do is use the command dlopen() which will check the lib for it in the cache. 

Here is the os.path call: 
```
In [2]: os.path.exists("/usr/lib/libSystem.B.dylib")
Out[2]: False
```

**Comment by bwoodsend** [comment]
Can you also check the other commands? Actively loading each dylib is not something we want to do unless we have no choice...

```python
ctypes.utils.find_library("libSystem.B.dylib")
shutil.which("libSystem.B.dylib")
```
And just to confirm that it does work:
```python
ctypes,CDLL("libSystem.B.dylib")._name
```

**Comment by SamSchott** [comment]
I can confirm that the first two return ``None`` but ``ctypes.CDLL("libSystem.B.dylib")._name`` does work.

https://github.com/python/cpython/pull/21241 addresses the issue with ``ctypes.util.find_library`` on macOS Big Sur.

**Comment by bwoodsend** [comment]
Well as `ctypes` is standard lib the best we can hope for is for someone to write a backport if we want to support macOS Big Sur on current versions of Python. Looking at those [changes needed](https://github.com/python/cpython/pull/21241/files), I certainly wouldn't attempt to reproduce this into PyInstaller.

I'm still not clear on the impact of this. Is this specific to built-in system libraries? And if so, do we need to include them? On Windows it's generally a good idea to bring system libraries with you as they often turn out not to be standard - how stable is macOS's system libraries?

**Comment by SamSchott** [comment]
> the best we can hope for is for someone to write a backport

I think it is planned to fully support Big Sur in a future Python 3.8 bugfix release. This still leaves Python 3.7 without the fixes.

> Is this specific to built-in system libraries? 

This is specific to system libraries only and has been the default in iOS for some time. In my experience, macOS libraries are sufficiently stable so that the don't need to be included. But my experience is limited...

**Comment by bwoodsend** [comment]
I suppose the thing to do would be to run the test suite on a Big Sur. Would you be able to do this?

**Comment by SamSchott** [comment]
Done. The output looks pretty grim but many of the failures seem to be related to not finding the system's Tk library and therefore are directly caused by this issue. For reference, I am using Python 3.8 installed with homebrew.

Attached is a (large) file with the test output.

[pyinstaller_test_macOS_11.txt](https://github.com/pyinstaller/pyinstaller/files/5219988/pyinstaller_test_macOS_11.txt)

**Comment by bwoodsend** [comment]
Great, thanks for that. Can I ask which version of PyInstaller you used? I'm guessing you cloned the development branch? But it looks like they're all failing in the same place. Namely that `_find_tcl_tk()` hook which we know to be broken but we have an unmerged fix for #5013. Mind if I @mention you once it's merged and you can run it again?

**Comment by SamSchott** [comment]
I tried both the dev branch and the fix from #5013 with similar results. Still, feel free to @mention me in the PR.

Actually attempting to load the libraries instead of using `macholib.dyld.dyld_find` or `os.path.exists` resolves many of failures. The resulting test output looks much better, however some failures mostly regarding ctypes remain:

[pyinstaller_patched_test_macOS_11.txt](https://github.com/pyinstaller/pyinstaller/files/5221029/pyinstaller_patched_test_macOS_11.txt)

I know that this is something which you would rather avoid. Nevertheless, the patch goes as follows:

```diff
diff --git a/PyInstaller/depend/bindepend.py b/PyInstaller/depend/bindepend.py
index 95660b5dcef0f7167bf62007422233daefb758a7..854947b364b4242f2bea89ee6cbd9cd7c382879a 100644
--- a/PyInstaller/depend/bindepend.py
+++ b/PyInstaller/depend/bindepend.py
@@ -21,6 +21,7 @@ from glob import glob
 # Required for extracting eggs.
 import zipfile
 import collections
+from ctypes import cdll
 
 from .. import compat
 from ..compat import (is_win, is_win_10, is_unix,
@@ -692,10 +693,17 @@ def _getImports_macholib(pth):
                 if not os.path.isabs(run_path):
                     run_path = os.path.join(exec_path, run_path)
                 # Stop looking for lib when found in first location.
-                if os.path.exists(os.path.join(run_path, lib)):
-                    final_lib = os.path.abspath(os.path.join(run_path, lib))
+                
+                try:
+                    candidate = os.path.exists(os.path.join(run_path, lib))
+                    cdll.LoadLibrary(candidate)
+                except OSError:
+                    pass
+                else:
+                    final_lib = candidate
                     rslt.add(final_lib)
                     break
+
             # Log error if no existing file found.
             if not final_lib:
                 logger.error('Can not find path %s (needed by %s)', lib, pth)
@@ -707,11 +715,13 @@ def _getImports_macholib(pth):
             # It is also replaced by 'exec_path'.
             if lib.startswith('@loader_path'):
                 lib = lib.replace('@loader_path', '@executable_path')
+            
             try:
-                lib = dyld_find(lib, executable_path=exec_path)
-                rslt.add(lib)
-            except ValueError:
+                cdll.LoadLibrary(lib)
+            except OSError:
                 logger.error('Can not find path %s (needed by %s)', lib, pth)
+            else:
+                rslt.add(lib)
 
     return rslt
 
```

**Comment by SamSchott** [comment]
Ah, damn. There was a typo in the patch. It should be `candidate = os.path.join(run_path, lib)` instead of `candidate = os.path.exists(os.path.join(run_path, lib))`. This gets rid of a few strange TypeErrors.

The correct patch:

[bindepend_patch_macos_11.txt](https://github.com/pyinstaller/pyinstaller/files/5221395/bindepend_patch_macos_11.txt)

And the test results:

[pyinstaller_patched_test_2_macOS_11.txt](https://github.com/pyinstaller/pyinstaller/files/5221392/pyinstaller_patched_test_2_macOS_11.txt)

Already a bit better. I will leave you to figure our the remaining failures but I'm happy to run tests for future fixes if helpful.

**Comment by bwoodsend** [comment]
Thanks @SamSchott, that's really helpful. That gives us a pretty good idea of what we need to do - although I don't feel any better about doing it.

**Comment by bwoodsend** [comment]
Actually one thing - surely 
```diff
+            else:
+                rslt.add(lib)
```
would only add the library's name rather than its path? In which case they would not end up in the final build.

**Comment by SamSchott** [comment]
Fair point. Finding the actual path however will be more difficult. Personally, I am using the following workaround for system libraries:

```Python
def find_library(name):
    paths = [
        f'/System/Library/Frameworks/{name}.framework/{name}',
        f'/usr/lib/lib{name}.dylib',
        f'{name}.dylib',
    ]

    for path in paths:
        try:
            cdll.LoadLibrary(path)
            return path
        except OSError:
            pass

    return None
```

but it's probably better to wait for the official fix of `find_library`.

**Comment by silbo** [comment]
> I tried both the dev branch and the fix from #5013 with similar results. Still, feel free to @mention me in the PR.
> 
> Actually attempting to load the libraries instead of using `macholib.dyld.dyld_find` or `os.path.exists` resolves many of the failures. The resulting test output looks much better, however some failures mostly regarding ctypes remain:
> 
> [pyinstaller_patched_test_macOS_11.txt](https://github.com/pyinstaller/pyinstaller/files/5221029/pyinstaller_patched_test_macOS_11.txt)
> 
> I know that this is something which you would rather avoid. Nevertheless, the patch goes as follows:
> 
> ```diff
> diff --git a/PyInstaller/depend/bindepend.py b/PyInstaller/depend/bindepend.py
> index 95660b5dcef0f7167bf62007422233daefb758a7..854947b364b4242f2bea89ee6cbd9cd7c382879a 100644
> --- a/PyInstaller/depend/bindepend.py
> +++ b/PyInstaller/depend/bindepend.py
> @@ -21,6 +21,7 @@ from glob import glob
>  # Required for extracting eggs.
>  import zipfile
>  import collections
> +from ctypes import cdll
>  
>  from .. import compat
>  from ..compat import (is_win, is_win_10, is_unix,
> @@ -692,10 +693,17 @@ def _getImports_macholib(pth):
>                  if not os.path.isabs(run_path):
>                      run_path = os.path.join(exec_path, run_path)
>                  # Stop looking for lib when found in first location.
> -                if os.path.exists(os.path.join(run_path, lib)):
> -                    final_lib = os.path.abspath(os.path.join(run_path, lib))
> +                
> +                try:
> +                    candidate = os.path.exists(os.path.join(run_path, lib))
> +                    cdll.LoadLibrary(candidate)
> +                except OSError:
> +                    pass
> +                else:
> +                    final_lib = candidate
>                      rslt.add(final_lib)
>                      break
> +
>              # Log error if no existing file found.
>              if not final_lib:
>                  logger.error('Can not find path %s (needed by %s)', lib, pth)
> @@ -707,11 +715,13 @@ def _getImports_macholib(pth):
>              # It is also replaced by 'exec_path'.
>              if lib.startswith('@loader_path'):
>                  lib = lib.replace('@loader_path', '@executable_path')
> +            
>              try:
> -                lib = dyld_find(lib, executable_path=exec_path)
> -                rslt.add(lib)
> -            except ValueError:
> +                cdll.LoadLibrary(lib)
> +            except OSError:
>                  logger.error('Can not find path %s (needed by %s)', lib, pth)
> +            else:
> +                rslt.add(lib)
>  
>      return rslt
>  
> ```

This patch works for me, thanks a lot for an early workaround 👍

**Comment by sergei2009op** [comment]
I have the same issue. I'm using Mac OS Big Sur and python 3.9 with 4.1 version of pyinstaller. How this problem could be fixed?

**Comment by SomberNight** [comment]
@sergei2009op note that you probably would not want to build on Big Sur anyway if you want your users on older macs to be able to run the binary.

see
https://github.com/pyinstaller/pyinstaller/issues/1191
https://pyinstaller.readthedocs.io/en/stable/usage.html#making-mac-os-x-apps-forward-compatible

> The only way to be certain your app supports an older version of Mac OS X is to run PyInstaller in the oldest version of the OS you need to support.

**Comment by sergei2009op** [comment]
> @sergei2009op note that you probably would not want to build on Big Sur anyway if you want your users on older macs to be able to run the binary.
> 
> see
> #1191
> https://pyinstaller.readthedocs.io/en/stable/usage.html#making-mac-os-x-apps-forward-compatible
> 
> > The only way to be certain your app supports an older version of Mac OS X is to run PyInstaller in the oldest version of the OS you need to support.

Thank you for your answer. But I need to run my app on Big Sur in "onefile" mode without such errors. Do you know how it could be fixed?

**Comment by kentletor** [comment]
@SamSchott patch helped fixed a majority of my lib errors thank you!

Only having a problem with libopenblas.0.dylib which I need for numpy

` ERROR: Can not find path @executable_path/../.dylibs/libopenblas.0.dylib`

is the specific error. Strangely enough libopenblas.0.dylib is in the pyinstaller "binchache" folder that was created. I temporarily directing the path in bindepend to directly lead to it but still getting the same errors.

**Comment by DEMO0130** [comment]
any work in progress??meet the same problem

**Comment by yairchu** [comment]
Here are details from Apple in the [macOS Big Sur Release Notes](https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_0_1-release-notes):

> New in macOS Big Sur 11.0.1, the system ships with a built-in dynamic linker cache of all system-provided libraries. As part of this change, copies of dynamic libraries are no longer present on the filesystem. Code that attempts to check for dynamic library presence by looking for a file at a path or enumerating a directory will fail. Instead, check for library presence by attempting to dlopen() the path, which will correctly check for the library in the cache. (62986286)

(which I found from the [same issue for Haskell/GHC](https://gitlab.haskell.org/ghc/ghc/-/issues/18446))

**Comment by matteomm** [comment]
I am having the same issue trying to create a simple app with PyInstaller, like other people I'd need this to run on Big Sur as I don't care about lack of retro compatibility with previous Mac versions...isn't there really a fix to this since August?

**Comment by matteomm** [comment]
> Here are details from Apple in the [macOS Big Sur Release Notes](https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_0_1-release-notes):
> 
> > New in macOS Big Sur 11.0.1, the system ships with a built-in dynamic linker cache of all system-provided libraries. As part of this change, copies of dynamic libraries are no longer present on the filesystem. Code that attempts to check for dynamic library presence by looking for a file at a path or enumerating a directory will fail. Instead, check for library presence by attempting to dlopen() the path, which will correctly check for the library in the cache. (62986286)
> 
> (which I found from the [same issue for Haskell/GHC](https://gitlab.haskell.org/ghc/ghc/-/issues/18446))

@yairchu Have you found any easy fix to this issue?

**Comment by SamSchott** [comment]
It looks like Python 3.9.1 has been released now with the necessary fixes for `ctypes.find_libary` and support to build universal binaries for macOS 11. There even is a universal binary build of Python 3.9 available to download from https://www.python.org/downloads/release/python-391, built on Big Sur with deployment target of OS X 10.9. I am sure a backport to Python 3.8 will follow soon.

Provided there are no other issues with building on macOS 11, it might be easier to point users to a newer Python release instead of making changes to PyInstaller.

**Comment by jaymegordo** [comment]
@SamSchott I'm on Python 3.9.1 and Pyinstaller 4.1 but still getting erros like:
```
10253 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/opt/python@3.9/bin/../Frameworks/Python.framework/Versions/3.9/bin/python3.9)
10261 ERROR: Can not find path /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (needed by /usr/local/Cellar/python@3.9/3.9.1/Frameworks/Python.framework/Versions/3.9/Python)
10264 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.9/3.9.1/Frameworks/Python.framework/Versions/3.9/Python)
```

Is there anything else I might need to change?

**Comment by SamSchott** [comment]
Apologies, my comment was clearly premature. I haven't used PyInstaller for some time.

It appears there are still changes required, namely actually using `ctypes.util.find_libary` instead of `dyld_find` from `macholib`. But at least this avoids loading each dylib!

**Comment by rokm** [comment]
Well, for what is worth, these error messages:
> 10253 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/opt/python@3.9/bin/../Frameworks/Python.framework/Versions/3.9/bin/python3.9)
10261 ERROR: Can not find path /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (needed by /usr/local/Cellar/python@3.9/3.9.1/Frameworks/Python.framework/Versions/3.9/Python)
10264 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /usr/local/Cellar/python@3.9/3.9.1/Frameworks/Python.framework/Versions/3.9/Python)

are very likely completely harmless, because PyInstaller does not bundle shared libraries from macOS system frameworks (nor does failure to find the library affect the dependency resolution, because those shared libraries depend only on other system framework shared libraries).

One scenario where the inability to find the system shared library on Big Sur may lead to an error is if a PyInstaller hook contains logic for collecting additional resources that depends on the the library's path (i.e., the resource location is determined relatively to the shared library's path). We used to have this issue with homebrew python that still used system Tcl/Tk, where the Tcl modules could not be collected because the Tcl shared library file could not be found on Big Sur (#5040) - but this has since been fixed (#5217).

So while those error messages are annoying, their impact should be quite limited, and the issues described in follow-up comments are actually different issues conflated and erroneously attributed to this one.

**Comment by yairchu** [comment]
> @yairchu Have you found any easy fix to this issue?

I did make a work-around for the same problem in Haskell - https://yairchu.github.io/posts/intercept-to-fix
(note that the problem was already solved in GHC repo but I wanted to use older GHC versions)

It should be possible with some tweaks to make the same work-around fit for this use case as well, the `my_stat` function should be changed to also fake the existence of the files in question here (`/usr/lib/libSystem.B.dylib` etc)

**Comment by m3nu** [comment]
> Apologies, my comment was clearly premature. I haven't used PyInstaller for some time.
> 
> It appears there are still changes required, namely actually using `ctypes.util.find_libary` instead of `dyld_find` from `macholib`. But at least this avoids loading each dylib!

Pyinstaller 4.2 with Python 3.9.1 still gets the same errors, but the resulting app is still usable.

**Comment by papr** [comment]
I would like to add another (more complex) example. The application uses PyOpenGL 3.1.5.

PyInstaller: 4.2
Python: 3.9.1 (installed via "installer")
Application created on macOS 10.14 Mojave

When running the application on Big Sur:
```py
Traceback (most recent call last):
  File "PyInstaller/loader/pyiboot01_bootstrap.py", line 144, in __init__
  File "ctypes/__init__.py", line 374, in __init__
OSError: dlopen(OpenGL, 10): no suitable image found.  Did find:
	file system relative paths not allowed in hardened programs

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "OpenGL/platform/darwin.py", line 35, in GL
  File "OpenGL/platform/ctypesloader.py", line 36, in loadLibrary
  File "OpenGL/platform/ctypesloader.py", line 89, in _loadLibraryWindows
  File "PyInstaller/loader/pyiboot01_bootstrap.py", line 146, in __init__
PyInstallerImportError: ("Failed to load dynlib/dll 'OpenGL'. Most probably this dynlib/dll was not found when the application was frozen.", 'OpenGL', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "launchables/world.py", line 120, in world
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "OpenGL/GL/__init__.py", line 3, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "OpenGL/error.py", line 12, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "OpenGL/platform/__init__.py", line 36, in <module>
  File "OpenGL/platform/__init__.py", line 33, in _load
  File "OpenGL/platform/baseplatform.py", line 97, in install
  File "OpenGL/platform/baseplatform.py", line 15, in __get__
  File "OpenGL/platform/darwin.py", line 62, in GetCurrentContext
  File "OpenGL/platform/baseplatform.py", line 15, in __get__
  File "OpenGL/platform/darwin.py", line 45, in CGL
  File "OpenGL/platform/baseplatform.py", line 15, in __get__
  File "OpenGL/platform/darwin.py", line 41, in GL
ImportError: ('Unable to load OpenGL library', "Failed to load dynlib/dll 'OpenGL'. Most probably this dynlib/dll was not found when the application was frozen.", 'OpenGL', None)
```

My apologies should this example be misplaced.

**Comment by rokm** [comment]
> Pyinstaller 4.2 with Python 3.9.1 still gets the same errors, but the resulting app is still usable.

Yes, those missing system library error messages are harmless, as PyInstaller does not collect system libraries anyway. So this issue is more or less a cosmetic one, and I have a PR ready that will suppress those error messages (which didn't make it to 4.2).

So the built program should still be usable; if not, that is likely caused by another, unrelated issue.

**Comment by papr** [comment]
@rokm Thank you for your quick response.
> So the built program should still be usable

I am not sure if I understood you correctly or if I am missing something.

Currently, PyInstaller is raising an exception (`PyInstallerImportError`), causing the program to shutdown. Is there a way around that exception other than using your PR or the next PyInstaller release that includes the PR?

**Comment by m3nu** [comment]
It's not a cosmetic error for Python versions <3.9.1. I also tried with 3.7.8 and the resulting app wouldn't start.

If the issue is with a Python library that PyInstaller users, we may need to wait for more minor Python updates.

**Comment by rokm** [comment]
> I am not sure if I understood you correctly or if I am missing something.

Your issue very likely has nothing to do with system libraries not being visible on Big Sur. This issue is dealing with error messages during application *build*, not at runtime - see the original report.

**Comment by rokm** [comment]
> It's not a cosmetic error for Python versions <3.9.1. I also tried with 3.7.8 and the resulting app wouldn't start.

What's the error message, then? Does it imply that the cause are hidden system libraries on Big Sur?

**Comment by papr** [comment]
> This issue is dealing with error messages during application build, not at runtime

Oh, you are right. My issue appears during runtime, not during build. (Build is on macOS 10.14 Mojave which is why I do not get the error message which this issue is about.) Thank you for taking the time to elaborate on your initial response.

**Comment by cperezabo** [comment]
Why this issue is closed? This is still happening in Python 3.9.1 + PyInstaller 4.2

**Comment by papr** [comment]
@cperezabo This issue was closed because the fix for it was merged in #5464. It will be included in the next PyInstaller release.

**Comment by cperezabo** [comment]
Thanks @papr, I wasn't aware of that fix!

**Comment by cperezabo** [comment]
Well.. I've been looking at the changes in that PR and it just silent the message, so maybe I'm having another issue, because since updated to Big Sur, I've not been able to build my app again, it just freezes and I have to force quit it. If I run it in CLI I have no errors so I don't know exactly how to debug it, any idea?

**Comment by papr** [comment]
@cperezabo Well, I suggest having a look at the other macOS Big Sur related issues, https://github.com/pyinstaller/pyinstaller/issues/5315 and https://github.com/pyinstaller/pyinstaller/issues/5491. Also, if you open a [new bug report](https://github.com/pyinstaller/pyinstaller/issues/new?assignees=&labels=&template=bug_report.md&title=), there is a list of steps to follow in this kind of situation. I suggest following it and if the issue persists to file the issue.

**Comment by JapinderSandhu** [comment]
> @cperezabo This issue was closed because the fix for it was merged in #5464. It will be included in the next PyInstaller release.

when will this new release come out?

**Comment by PyMarc2** [comment]
+1

**Comment by imperialguy** [comment]
This issue is clearly still not fixed. Same errors.

**Comment by Legorooj** [comment]
> This issue is clearly still not fixed. Same errors.

@imperialguy have you tried running the development version? You might need to rebuild the bootloaders too.

**Comment by jdson7** [comment]
Same errors here, using developer version too

> > @cperezabo This issue was closed because the fix for it was merged in #5464. It will be included in the next PyInstaller release.
> 
> when will this new release come out?
> 
> Running into this error on MacOS 10.15.7 Catalina
> My Env:
> 
> INFO: PyInstaller: 4.2
> INFO: Python: 3.9.2 (conda)
> INFO: Platform: macOS-10.15.7-x86_64-i386-64bit
> 
> I am using anaconda version: conda 4.8.2
> 
> [50576] Error loading Python lib '/var/folders/6z/snnb75fd7h734dd51kbdjntw0000gn/T/_MEIspzQDS/libpython3.9.dylib': dlopen: dlopen(/var/folders/6z/snnb75fd7h734dd51kbdjntw0000gn/T/_MEIspzQDS/libpython3.9.dylib, 10): no suitable image found. Did find:
> /var/folders/6z/snnb75fd7h734dd51kbdjntw0000gn/T/_MEIspzQDS/libpython3.9.dylib: code signature in (/var/folders/6z/snnb75fd7h734dd51kbdjntw0000gn/T/_MEIspzQDS/libpython3.9.dylib) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
> 
> **Update:**
> 
> I tried it with the developer version of pyinstaller
> pip install https://github.com/pyinstaller/pyinstaller/archive/develop.tar.gz
> 
> pyinstaller 5.0.dev0
> pyinstaller-hooks-contrib 2021.1
> 
> It suppressed the errors when I package using --onefile
> 
> but I am still getting the same error when I run my executable
> 
> ```shell
> [40125] Error loading Python lib '/var/folders/0r/jz_vw8vn54b85gh437lwcgdw0000gn/T/_MEIjzyz9g/libpython3.9.dylib': dlopen: dlopen(/var/folders/0r/jz_vw8vn54b85gh437lwcgdw0000gn/T/_MEIjzyz9g/libpython3.9.dylib, 10): no suitable image found.  Did find:
> 	/var/folders/0r/jz_vw8vn54b85gh437lwcgdw0000gn/T/_MEIjzyz9g/libpython3.9.dylib: code signature in (/var/folders/0r/jz_vw8vn54b85gh437lwcgdw0000gn/T/_MEIjzyz9g/libpython3.9.dylib) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
> ```

**Comment by bwoodsend** [comment]
Have you recompiled the bootloaders?

**Comment by rokm** [comment]
> Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.

Looks like x86_64 is now starting to require at least ad-hoc code-signing. This is a different issue than hidden system libraries (which is what this issue was about), and will be fixed once we implement ad-hoc re-signing as part of M1 support.

**Comment by rokm** [comment]
The problem with missing signature on libpython might be already fixed by WIP macos11-arm64-support-cleanup branch in #5581 (but there may or may not be additional issues with invalidated signatures on other collected shared libraries, depending on how strict x86_64 actually is).

**Comment by jdson7** [comment]
> Have you recompiled the bootloaders?

Yes, I have.

The exact error message when I run executable is this:
[1537] Error loading Python lib '/Users/myuser/Workspace/myproject/Darwin/x86_64/build/projectname/Python': dlopen: dlopen(/Users/myuser/Workspace/myproject/Darwin/x86_64/build/projectname/Python, 10): image not found

**Comment by rokm** [comment]
>  [1537] Error loading Python lib '/Users/myuser/Workspace/myproject/Darwin/x86_64/build/projectname/Python': dlopen: dlopen(/Users/myuser/Workspace/myproject/Darwin/x86_64/build/projectname/Python, 10): image not found

Ah, you're just trying to run the partial bundle from `build` directory instead of complete one in the `dist` directory...

**Comment by jdson7** [comment]
> > [1537] Error loading Python lib '/Users/myuser/Workspace/myproject/Darwin/x86_64/build/projectname/Python': dlopen: dlopen(/Users/myuser/Workspace/myproject/Darwin/x86_64/build/projectname/Python, 10): image not found
> 
> Ah, you're just trying to run the partial bundle from `build` directory instead of complete one in the `dist` directory...

My mistake, sorry guys and thank you for your support!!

**Comment by stesalati** [comment]
I'm trying to build a very basic app that uses PyQt5 on Big Sur and I have the same problem with libraries.
Here's my configuration:
```
37 INFO: PyInstaller: 5.0.dev0
37 INFO: Python: 3.9.4
46 INFO: Platform: macOS-11.2.3-x86_64-i386-64bit
```
I compiled the bootloader as indicated here: [https://github.com/pyinstaller/pyinstaller](https://github.com/pyinstaller/pyinstaller).
All I get is a waterfall of errors, most of the of the "cannot find path ..." type. I.e. `13859 ERROR: Can not find path /usr/lib/libSystem.B.dylib`.

I don't think it's the app I'm building. It runs correctly if I launch it from terminal. I get errors even with the basic:
```
app = QApplication(sys.argv)
win = QMainWindow()
win.setGeometry(200, 200, 400, 200)
win.setFixedSize(400, 200)
win.setWindowTitle("FotoPDF")
win.show()
sys.exit(app.exec_())
```

**Comment by cowquant** [comment]
I built a basic app , just one code : print('a')
PyInstaller version: 5.1
Python 3.10.4 
pyinstaller --onedir --noupx 
Platform: macOS-12.1-x86_64-i386-64bit

The app run normal in most computers. 
Failed on macOS13(I work in apple factory, so yes, it's macOS13)

The error message is : Library not loaded /usr/lib/libSystem.B.dylib

I searched a lot of issues.
This is due to a change Apple made where the system doenst have copies
of the libraries anymore but rather a DYLD cache.
This isn't the first time Apple has changed the way of doing dylib loading.

How to fix this myself?
I use --add-binary this lib(copy from another computer), not work.
