### ISSUE TITLE
inspect.getmodule fails for pyinstaller executable

### ISSUE THREAD

**Issue by hacki11** [pyinstaller/pyinstaller#5963]
### I have added jsonargparse to my program and they are using the following code:
`caller = inspect.getmodule(inspect.stack()[1][0]).__package__`
https://github.com/omni-us/jsonargparse/blob/9ae29b940285a4fa1ff7cba55099ab884874127a/jsonargparse/core.py#L241

`inspect.getmodule()` will return `None` for programs packaged with pyinstaller only. The program quits with the error:
```
Traceback (most recent call last):
  File "main.py", line 28, in <module>
    main()
  File "main.py", line 24, in main
    cfg = parser.parse_args()
  File "jsonargparse\core.py", line 379, in parse_args
  File "jsonargparse\core.py", line 242, in parse_known_args
AttributeError: 'NoneType' object has no attribute '__package__'
[3456] Failed to execute script main
```

* Output of `pyinstaller --version`: ```4.3```
* Version of Python: 3.8.6
* Platform: Windows 10 german
* How you installed Python: e.g. python.org/downloads
* Did you also try this on another platform? Does it work there?
No other platform available

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```
No changes with latest version.

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.
No matter if -F or not

### A minimal example program which shows the error
The minimal code removed even the jsonargparse library and added the command which should return the module but does only return None.
```
import inspect

def main():
    print("stack[1][0]:")
    print(inspect.stack()[1][0])
    print("getmodule(stack[1][0]):")
    module = inspect.getmodule(inspect.stack()[1][0])
    print(module)
    assert(module is not None)


if __name__ == '__main__':
    main()
```

### Stacktrace / full error message

```
stack[1][0]:
<frame at 0x00000220014812C0, file 'main.py', line 13, code <module>>
getmodule(stack[1][0]):
None <<< Should not be None (e.g. running directly: <module '__main__' from 'C:/git/pyinstaller-jsonargparse/main.py'>

Traceback (most recent call last):
  File "main.py", line 13, in <module>
    main()
  File "main.py", line 9, in main
    assert(module is not None)
AssertionError
```

Log Output of direct python call:
```
C:\git\pyinstaller-jsonargparse\venv\Scripts\python.exe C:/git/pyinstaller-jsonargparse/main.py
stack[1][0]:
<frame at 0x00000237AD899840, file 'C:/git/pyinstaller-jsonargparse/main.py', line 13, code <module>>
getmodule(stack[1][0]):
<module '__main__' from 'C:/git/pyinstaller-jsonargparse/main.py'>

Process finished with exit code 0
```

`inspect.getmodule()` has several module detection mechanisms but it seems no one is compatible with pyinstaller.
Currently it returns because the following expression returns true:     if not hasattr(object, '__name__')`
```
def getmodule(object, _filename=None):
    """Return the module an object was defined in, or None if not found."""
    if ismodule(object):
        return object
    if hasattr(object, '__module__'):
        return sys.modules.get(object.__module__)
    # Try the filename to modulename cache
    if _filename is not None and _filename in modulesbyfile:
        return sys.modules.get(modulesbyfile[_filename])
    # Try the cache again with the absolute file name
    try:
        file = getabsfile(object, _filename)
    except TypeError:
        return None
    if file in modulesbyfile:
        return sys.modules.get(modulesbyfile[file])
    # Update the filename to module name cache and check yet again
    # Copy sys.modules in order to cope with changes while iterating
    for modname, module in sys.modules.copy().items():
        if ismodule(module) and hasattr(module, '__file__'):
            f = module.__file__
            if f == _filesbymodname.get(modname, None):
                # Have already mapped this module, so skip it
                continue
            _filesbymodname[modname] = f
            f = getabsfile(module)
            # Always map to the name the module knows itself by
            modulesbyfile[f] = modulesbyfile[
                os.path.realpath(f)] = module.__name__
    if file in modulesbyfile:
        return sys.modules.get(modulesbyfile[file])
    # Check the main module
    main = sys.modules['__main__']
    if not hasattr(object, '__name__'):
        return None
    if hasattr(main, object.__name__):
        mainobject = getattr(main, object.__name__)
        if mainobject is object:
            return main
    # Check builtins
    builtin = sys.modules['builtins']
    if hasattr(builtin, object.__name__):
        builtinobject = getattr(builtin, object.__name__)
        if builtinobject is object:
            return builtin
```

**Comment by rokm** [comment]
This looks like a (slightly different) variant of #5897 and probably due to behavior of `__main__` in frozen application not fully conforming to python's behavior. 

Running the provided test program as `python program.py` returns `module` as <module '__main__' from '[...]/program.py'>, whereas running it as `cat program.py | python` returns `<module '__main__' (built-in)>`. Running as frozen application, however, returns `None`.

**Comment by rokm** [comment]
It turns out that the problem here is not `__main__` per-se, but rather the path handling in `inspect` when it tries to resolve the calling module from stack frame (in this case, `__main__`).

The stack-frame object seems to provide only base-name of the "source" file (e.g., `program.py`), and `getabsfile`/`getsourcefile` seem to be trying to find it in current working directory.

That's why the test snippet seems to work if called from within `dist/program` folder (because then resolved name `[fullpath/]dist/program/program.py` coincides with `__main__.__file__`). It does not work from any other location, as
`[cur_location]/program.py` does not match `__main__.__file__`. And notably, it fails if called from directory containing the original source `program.py`, because then the latter "shadows" the fictious `program.py` declared in `__main__.__file__`.

One way (or rather, the only one I can think of) to solve this is by rthook that overrides the `inspect.getsourcefile` to always return `__main__.__file__` if the given filename matches `basename(__main__.__file__)`. Although, this also begs the question how `module = inspect.getmodule(inspect.stack()[1][0])` behaves when called from any other module...

**Comment by hacki11** [comment]
Thank you for the insights! Can you give me a hint how i do such a hook? Can i do that on my own or this something which has to be done within the project?

**Comment by rokm** [comment]
> Thank you for the insights! Can you give me a hint how i do such a hook? Can i do that on my own or needs this be done within the project?

You can try using the branch from #5964, which should fix the problem with modules not being resolved. 

I also tried a simple `jsonargparse` example, and it seems to work now (as long as you pass `components` to `CLI()`; the auto-discovery from globals does not work, because PyInstaller's bootstrap script and rthooks create global objects, which get pulled in as components, and then fail due to lack of typing/annotations).

**Comment by hacki11** [comment]
> as long as you pass components to CLI()
Is that related to pyinstaller? I did not get what i have to do here.
I have pulled your fix but the issue is not solved.

**Comment by rokm** [comment]
The "Basic usage" example from `jsonargparse`'s README:

```python
from jsonargparse import CLI

def command(
    name: str,
    prize: int = 100
):
    """
    Args:
        name: Name of winner.
        prize: Amount won.
    """
    print(f'{name} won {prize}€!')

if __name__ == '__main__':
    CLI()
```

does not work as-is, even using branch from #5964:
```
$ ./dist/program/program Lucky --prize=1000
Traceback (most recent call last):
  File "program.py", line 15, in <module>
    CLI()
  File "jsonargparse/cli.py", line 78, in CLI
  File "jsonargparse/cli.py", line 109, in _add_component_to_parser
  File "jsonargparse/signatures.py", line 69, in add_class_arguments
  File "jsonargparse/signatures.py", line 242, in _add_signature_arguments
  File "jsonargparse/signatures.py", line 355, in _add_signature_parameter
ValueError: Required parameter without a type for Popen parameter process_obj.
[76070] Failed to execute script program
```
because if `CLI()` is used without arguments, it [takes all variables from the context as potential arguments/components](https://github.com/omni-us/jsonargparse/blob/a135ebf38007adf2cc989ea08628c6475c7576f2/jsonargparse/cli.py#L46-L54). 

And in a frozen application, PyInstaller's bootstrap script and rthooks add some additional variables (e.g., the `components` in frozen application thus become `[<class '__main__.NullWriter'>, <function _freeze_support at 0x7f4aa5b92c10>, <class '__main__.FrozenSupportMixIn'>, <class '__main__._Popen'>, <class '__main__._Spawning_Popen'>, <function _pyi_getsourcefile at 0x7f4aa5b09430>, <function command at 0x7f4aa593fe50>]` instead of just `[<function command at 0x7f4aa593fe50>]` in unfrozen script).

------

Modifying the program so that `components` are explicitly defined, i.e.,
```python
from jsonargparse import CLI

def command(
    name: str,
    prize: int = 100
):
    """
    Args:
        name: Name of winner.
        prize: Amount won.
    """
    print(f'{name} won {prize}€!')

if __name__ == '__main__':
    CLI([command])
```
makes it work in the frozen form:
```
$ ./dist/program/program Lucky --prize=1000
Lucky won 1000€!
```

-----

The other example from README, with Main class,

```python
from random import randint
from jsonargparse import CLI

class Main:
    def __init__(
        self,
        max_prize: int = 100
    ):
        """
        Args:
            max_prize: Maximum prize that can be awarded.
        """
        self.max_prize = max_prize

    def person(
        self,
        name: str
    ):
        """
        Args:
            name: Name of winner.
        """
        return f'{name} won {randint(0, self.max_prize)}€!'

if __name__ == '__main__':
    print(CLI(Main))
```

works out-of-the box (with #5964) as it specifies `components`:

```
$ ./dist/program2/program2 --max_prize=1000 person Lucky
Lucky won 782€!
```

**Comment by hacki11** [comment]
I'm using it with the ArgumentParser and it works perfectly:
```
from jsonargparse import ArgumentParser
parser = ArgumentParser()

parser.add_argument('--opt1')

if __name__ == '__main__':
    cfg = parser.parse_args()
```
Run with #5964 
```
$ dist\main.exe --help
usage: main.exe [-h] [--opt1 OPT1]

optional arguments:
  -h, --help   Show this help message and exit.
  --opt1 OPT1  (default: null)
```

Great work!
