### ISSUE TITLE
Permission denied error on MacOS Big Sur

### ISSUE THREAD

**Issue by fladd** [pyinstaller/pyinstaller#8690]
## Description of the issue
I installed PyInstaller into the virtual environment of the programme I want to pack. I run `python -m PyInstaller --windowed myapp/__main__.py`, and I get the error `PermissionError: [Errno 13] Permission denied: '/Users/floriankrause/Library/Python/3.12/lib/python/site-packages'`.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.9.0```
* Version of Python: 3.12.0 
* Platform: MacOS 11.0.7 
* How you installed Python: python.org 
* Did you also try this on another platform? Does it work there? I did not.

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it - **it doesn't freeze...**
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file. - **`--debug` option doesn't exist**

### A minimal example program which shows the error

```

import sys

print(sys.platform())

```

### Stacktrace / full error message

```
1 floriankrause~/Documents/GitHub/zap (git)-[main] % python -m PyInstaller --windowed --onedir --noupx zap/test.py  :(
244 INFO: PyInstaller: 6.9.0, contrib hooks: 2024.7
244 INFO: Python: 3.12.0
262 INFO: Platform: macOS-11.7.10-x86_64-i386-64bit
263 INFO: Python environment: /Users/floriankrause/envs/zap
264 INFO: wrote /Users/floriankrause/Documents/GitHub/zap/test.spec
271 INFO: UPX is available but is disabled on non-Windows due to known compatibility problems.
273 INFO: Module search paths (PYTHONPATH):
['/Users/floriankrause/Documents/GitHub/zap',
 '/Library/Frameworks/Python.framework/Versions/3.12/lib/python312.zip',
 '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12',
 '/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/lib-dynload',
 '/Users/floriankrause/envs/zap/lib/python3.12/site-packages',
 '/Users/floriankrause/envs/zap/lib/python3.12/site-packages/setuptools/_vendor',
 '/Users/floriankrause/Documents/GitHub/zap']
457 INFO: checking Analysis
457 INFO: Building Analysis because Analysis-00.toc is non existent
457 INFO: Running Analysis Analysis-00.toc
458 INFO: Target bytecode optimization level: 0
458 INFO: Initializing module dependency graph...
460 INFO: Caching module graph hooks...
477 INFO: Analyzing base_library.zip ...
1962 INFO: Loading module hook 'hook-encodings.py' from '/Users/floriankrause/envs/zap/lib/python3.12/site-packages/PyInstaller/hooks'...
4033 INFO: Loading module hook 'hook-pickle.py' from '/Users/floriankrause/envs/zap/lib/python3.12/site-packages/PyInstaller/hooks'...
5385 INFO: Loading module hook 'hook-heapq.py' from '/Users/floriankrause/envs/zap/lib/python3.12/site-packages/PyInstaller/hooks'...
5983 INFO: Caching module dependency graph...
6126 INFO: Looking for Python shared library...
6132 INFO: Using Python shared library: /Library/Frameworks/Python.framework/Versions/3.12/Python
6133 INFO: Analyzing /Users/floriankrause/Documents/GitHub/zap/zap/test.py
6134 INFO: Processing module hooks...
6144 INFO: Performing binary vs. data reclassification (3 entries)
6158 INFO: Looking for ctypes DLLs
6165 INFO: Analyzing run-time hooks ...
6167 INFO: Including run-time hook '/Users/floriankrause/envs/zap/lib/python3.12/site-packages/PyInstaller/hooks/rthooks/pyi_rth_inspect.py'
6174 INFO: Looking for dynamic libraries
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/floriankrause/envs/zap/lib/python3.12/site-packages/PyInstaller/__main__.py", line 308, in <module>
    run()
  File "/Users/floriankrause/envs/zap/lib/python3.12/site-packages/PyInstaller/__main__.py", line 215, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/Users/floriankrause/envs/zap/lib/python3.12/site-packages/PyInstaller/__main__.py", line 70, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/Users/floriankrause/envs/zap/lib/python3.12/site-packages/PyInstaller/building/build_main.py", line 1216, in main
    build(specfile, distpath, workpath, clean_build)
  File "/Users/floriankrause/envs/zap/lib/python3.12/site-packages/PyInstaller/building/build_main.py", line 1156, in build
    exec(code, spec_namespace)
  File "/Users/floriankrause/Documents/GitHub/zap/test.spec", line 4, in <module>
    a = Analysis(
        ^^^^^^^^^
  File "/Users/floriankrause/envs/zap/lib/python3.12/site-packages/PyInstaller/building/build_main.py", line 556, in __init__
    self.__postinit__()
  File "/Users/floriankrause/envs/zap/lib/python3.12/site-packages/PyInstaller/building/datastruct.py", line 184, in __postinit__
    self.assemble()
  File "/Users/floriankrause/envs/zap/lib/python3.12/site-packages/PyInstaller/building/build_main.py", line 923, in assemble
    self.binaries.extend(find_binary_dependencies(self.binaries, collected_packages))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/floriankrause/envs/zap/lib/python3.12/site-packages/PyInstaller/building/build_main.py", line 288, in find_binary_dependencies
    return bindepend.binary_dependency_analysis(binaries, search_paths=extra_libdirs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/floriankrause/envs/zap/lib/python3.12/site-packages/PyInstaller/depend/bindepend.py", line 120, in binary_dependency_analysis
    parent_dir_preservation_paths = _get_paths_for_parent_directory_preservation()
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/floriankrause/envs/zap/lib/python3.12/site-packages/PyInstaller/depend/bindepend.py", line 84, in _get_paths_for_parent_directory_preservation
    if not path.is_dir():
           ^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/pathlib.py", line 876, in is_dir
    return S_ISDIR(self.stat().st_mode)
                   ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/pathlib.py", line 841, in stat
    return os.stat(self, follow_symlinks=follow_symlinks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/Users/floriankrause/Library/Python/3.12/lib/python/site-packages'
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
And what are permissions on `/Users/floriankrause/Library/Python/3.12/lib/python/site-packages`?

**Comment by rokm** [comment]
> And what are permissions on `/Users/floriankrause/Library/Python/3.12/lib/python/site-packages`?

Or rather, does that directory exist at all (it is probably pulled in via `site.getusersitepackages()` call [here](https://github.com/pyinstaller/pyinstaller/blob/68ca73cb3361bd6bc6fa2b43c8f65c1a3cc2dc7b/PyInstaller/depend/bindepend.py#L61))? If it does, do permissions on it somehow prevent your user the access to it? If it does not exist, does whatever part of the path that does happen to exist have permissions that prevent your user account the access to it?

**Comment by fladd** [comment]
No, that directory does not exist. I have not idea where PyInstaller gets that location from. I have no user packages installed. There are global site-packages (`/Library/Frameworks/Python.framework/Versions/3.12/bin/python3.12`, but there is only `pip` here) and the ones in my venv (`~/envs/zap/lib/python3.12/site-packages`, everything my app needs is here, and also PyInstaller itself).

**Comment by rokm** [comment]
>  I have not idea where PyInstaller gets that location from.

It's probably returned by `site.getusersitepackages()`. As a work-around, you can probably try commenting out this line
https://github.com/pyinstaller/pyinstaller/blob/68ca73cb3361bd6bc6fa2b43c8f65c1a3cc2dc7b/PyInstaller/depend/bindepend.py#L61
in your local PyInstaller copy.

But my guess would be that you have a path with invalid permissions somewhere. If you run python interpreter and execute the following lines one by one, which (if any) do raise an error (instead of returning True/False):

```python
import pathlib
print(pathlib.Path('/Users').is_dir())
print(pathlib.Path('/Users/floriankrause').is_dir())
print(pathlib.Path('/Users/floriankrause/Library').is_dir())
print(pathlib.Path('/Users/floriankrause/Library/Python').is_dir())
print(pathlib.Path('/Users/floriankrause/Library/Python/3.12').is_dir())
print(pathlib.Path('/Users/floriankrause/Library/Python/3.12/lib').is_dir())
print(pathlib.Path('/Users/floriankrause/Library/Python/3.12/lib/python').is_dir())
print(pathlib.Path('/Users/floriankrause/Library/Python/3.12/lib/python/site-packages').is_dir())
```

**Comment by fladd** [comment]
As expected, the Python 3.12 ones do not exist:

```
>>> import pathlib
>>> print(pathlib.Path('/Users').is_dir())
True
>>> print(pathlib.Path('/Users/floriankrause').is_dir())
True
>>> print(pathlib.Path('/Users/floriankrause/Library').is_dir())
True
>>> print(pathlib.Path('/Users/floriankrause/Library/Python').is_dir())
True
>>> print(pathlib.Path('/Users/floriankrause/Library/Python/3.12').is_dir())
False
>>> print(pathlib.Path('/Users/floriankrause/Library/Python/3.12/lib').is_dir())
False
>>> print(pathlib.Path('/Users/floriankrause/Library/Python/3.12/lib/python').is_dir())
False
>>> print(pathlib.Path('/Users/floriankrause/Library/Python/3.12/lib/python/site-packages').is_dir())
False
>>>
```

**Comment by rokm** [comment]
Hmm, odd, would expect one of them to raise the same `PermissionError`...

Does it help if you comment [`orig_paths.append(site.getusersitepackages()) `](https://github.com/pyinstaller/pyinstaller/blob/68ca73cb3361bd6bc6fa2b43c8f65c1a3cc2dc7b/PyInstaller/depend/bindepend.py#L61) in your local PyInstaller copy?

Is `/Users/floriankrause/Library/Python` empty? Does it help if you temporarily rename it to something else (or remove it)?

**Comment by fladd** [comment]
Yes, commenting that out got me a bit further.

I then ran into an issue with relative imports in the __main__.py script, which I solved.

But now I get another permission error a bit later in the process:

```
PermissionError: [Errno 13] Permission denied: '/Users/floriankrause/Library/Application Support/pyinstaller/bincache00py31264bit/x86_64/adhoc/no-entitlements/lib-dynload/_ctypes.cpython-312-darwin.so'
```

The stuff in there belongs to root.

Do I need to call pyinstaller as root?

**Comment by bwoodsend** [comment]
>The stuff in there belongs to root.
>
> Do I need to call pyinstaller as root?

No, it and probably only got that way because you ran as root before. Just delete it.

**Comment by bwoodsend** [comment]
It really doesn't make sense that PyInstaller running `pathlib.Path().is_dir()` on `'/Users/floriankrause/Library/Python/3.12/lib/python/site-packages'` causes a permission error but `print(pathlib.Path('/Users/floriankrause/Library/Python/3.12/lib/python/site-packages').is_dir())` doesn't.

**Comment by rokm** [comment]
Indeed; the only way I can trigger this error is if I create `~/Library/Python` and deliberately restrict access to it.

I.e.,

```
$ ls -ld /Users/rok/Library/Python/
ls: /Users/rok/Library/Python/: No such file or directory
```

```
$ python3.12
Python 3.12.4 (v3.12.4:8e8a4baf65, Jun  6 2024, 17:33:18) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pathlib
>>> import site
>>> pathlib.Path(site.getusersitepackages()).is_dir()
False
```

This is the default scenario; user site-packages location does not exist by default, and we get no error.

Now we create the base directory, and restrict access to root only:

```
$ mkdir /Users/rok/Library/Python
$ sudo chown root:staff /Users/rok/Library/Python
$ sudo chmod 700 /Users/rok/Library/Python
```

```
$ ls -ld /Users/rok/Library/Python/
drwx------  2 root  staff  64 Jul 27 19:30 /Users/rok/Library/Python/
```

```
$ python3.12
Python 3.12.4 (v3.12.4:8e8a4baf65, Jun  6 2024, 17:33:18) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pathlib
>>> import site
>>> pathlib.Path(site.getusersitepackages()).is_dir()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/pathlib.py", line 875, in is_dir
    return S_ISDIR(self.stat().st_mode)
                   ^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/pathlib.py", line 840, in stat
    return os.stat(self, follow_symlinks=follow_symlinks)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/Users/rok/Library/Python/3.12/lib/python/site-packages'
```

One scenario I can see where user might accidentally end up with root-owned ~/Library/Python is if they used `sudo pythonX.Y -m pip install --user <package-name` in the past, and this ended up creating ~/Library/Python (note that it might have been a different version of python, too - that's why "3.12" directory does not exist but some "X.Y" might). With 3.12, pip seems to create directory that is accessible by user albeit being owned by root, but perhaps some older version of pip did not.

That's why I would like @fladd to tell us:
- what are the contents of `/Users/floriankrause/Library`
- what are the directory's owner and permissions, i.e., what is the output of `ls -ld /Users/floriankrause/Library/Python`)
- was the earlier manual path test ran as regular user or via sudo?

**Comment by fladd** [comment]
The folder indeed had other (older) Python versions in there. I fixed the issue now by (1) changing ownership of the `/Users/floriankrause/Library/Python` folder recursively to the user (instead of root) and (2) creating an empty `3.12` directory within.

**Comment by bwoodsend** [comment]
Shall we just leave this as is then? I'd prefer not to add `try/except PermssionError` guards around every *file exists* query.

**Comment by rokm** [comment]
> Shall we just leave this as is then? I'd prefer not to add `try/except PermssionError` guards around every _file exists_ query.

Yep. The irregularities in users' build environments should be fixed by users themselves.

**Comment by fladd** [comment]
> Shall we just leave this as is then? I'd prefer not to add `try/except PermssionError` guards around every _file exists_ query.

Well, this would still fail if someone has other (previous) versions of Python installed, right? Because the folder `Users/floriankrause/Library/Python` would exist, but not the folder `Users/floriankrause/Library/Python/<current_Python_version>`, if I understand this correctly.

**Comment by rokm** [comment]
> Well, this would still fail if someone has other (previous) versions of Python installed, right?

Nope. Only if they ran pip using sudo to install into that user site-packages location (so that `~/Library/Python` ends up created as root). The problem is not presence/absence of any of those directories per se, but them being present and have incorrect ownership/permissions.

**Comment by bwoodsend** [comment]
Specifically at some point you must have run `sudo pip install --user xxx` (which, in a happier world, pip would have blocked).

**Comment by fladd** [comment]
> Specifically at some point you must have run `sudo pip install --user xxx` (which, in a happier world, pip would have blocked).

The folder dates back to 2017, which was a time when installing into global Python was still quite common (at least for me), so accidentally typing `sudo` for that one time I did install into user space is entirely possible. 😆
